Repository livecode/livecode, pull requests merged in 2018-08, with the labels that each got.

#6632 [9.0.2-rc-1] Updated version
  version
Labels: vulcan/reviewed

#6630 [[ Bug 21469 ]] Recursively sign frameworks in iOS apps
  docs/notes/bugfix-21469.md
  ide-support/revsaveasiosstandalone.livecodescript
Labels: bug, vulcan/reviewed

#6627 Update ParseStringAsNumber dictionary
  libscript/src/arithmetic.lcb
Labels: vulcan/reviewed

#6620 [[ Bug 21443 ]] Dirty rect even if layer id is 0
  docs/notes/bugfix-21443.md
  engine/src/redraw.cpp
Labels: bug, vulcan/reviewed

#6625 Update .gitignore to exclude more build files
  .gitignore
Labels: vulcan/reviewed

#6618 [[ Bug 18395 ]] Handle return correctly in fileds on Android
  docs/notes/bugfix-18395.md
  engine/src/java/com/runrev/android/Engine.java
Labels: bug, vulcan/reviewed

#6617 [9.0.1-rc-2] Updated version
  version
Labels: vulcan/reviewed

#6635 [[Bug 21488]] Fix automatic architecture detection on some Linux systems
  Makefile.common
  docs/notes/bugfix-21488.md
Labels: bug, vulcan/reviewed

#6640 [[ Bug 21417 ]] Remove externals list from emscripten deploy params
  docs/notes/bugfix-21417.md
  ide-support/revsaveasemscriptenstandalone.livecodescript
Labels: bug, vulcan/reviewed

#6639 [[ Bug 21496 ]] Ensure emscripten startup_script is suitable for capsule section
  docs/notes/bugfix-21496.md
  engine/rsrc/emscripten-startup-template.livecodescript
  ide-support/revsaveasemscriptenstandalone.livecodescript
Labels: bug, vulcan/reviewed

#6631 [[ Bug ]] Fix definition of natural float on 64 bit systems
  libfoundation/src/foundation-foreign.cpp
Labels: bug, vulcan/reviewed

#6622 [[ Bug 21396 ]] Fix crash on startup in iOS 12 beta
  docs/notes/bugfix-21396.md
  engine/src/cgimageutil.cpp
  engine/src/mac-cursor.mm
  engine/src/mac-surface.mm
  engine/src/mbliphonegfx.mm
Labels: bug, vulcan/reviewed

#6642 [[Docs]] Updated Testing.md to include all requirement options of TestSkipIf and TestSkipIfNot
  docs/development/testing.md
Labels: vulcan/reviewed

#6645 [[ Bug 21507 ]] Fix incorrect parameter order in com.livecode.math function atan2
  docs/lcb/notes/21507.md
  libscript/src/math.lcb
Labels: vulcan/reviewed

#6649 [21500] Fix crash when moving a group before calling quit
  docs/notes/bugfix-21500.md
  engine/src/globals.cpp
  tests/lcs/core/engine/_ungroupandquit.livecodescript
  tests/lcs/core/engine/engine.livecodescript
Labels: bug, vulcan/reviewed

#6638 [[Bugfix 19619]] Add color to the clock widget
  extensions/widgets/clock/clock.lcb
  extensions/widgets/clock/docs/guide/guide.md
  extensions/widgets/clock/notes/19619.md
  extensions/widgets/clock/tests/properties.livecodescript
  tests/lcs/core/engine/extension.livecodescript
  tests/lcs/core/files/save.livecodescript
Labels: vulcan/reviewed

#6537 [[ KeyIsDown ]] Implement key is down
  docs/lcb/notes/feature-keyisdown.md
  engine/src/engine.lcb
  engine/src/module-engine.cpp
Labels: LCB, enhancement, vulcan/reviewed

#6623 [[ LCB ]] [[ Docs ]] Add OS and Platforms to LCB Metadata
  docs/guides/LiveCode Builder Language Reference.md
  docs/guides/LiveCode Builder Style Guide.md
  extensions/libraries/androidaudiorecorder/androidaudiorecorder.lcb
  extensions/libraries/androidbgaudio/androidbgaudio.lcb
  extensions/libraries/toast/toast.lcb
  extensions/modules/android-utils/android-utils.lcb
  extensions/script-libraries/extension-utils/extension-utils.livecodescript
  extensions/widgets/androidbutton/androidbutton.lcb
  extensions/widgets/androidfield/androidfield.lcb
  extensions/widgets/html5button/html5button.lcb
  extensions/widgets/iosbutton/iosbutton.lcb
  extensions/widgets/macbutton/macbutton.lcb
  extensions/widgets/mactextfield/mactextfield.lcb
  ide-support/revdocsparser.livecodescript
  ide-support/revsblibrary.livecodescript
  toolchain/lc-compile/src/generate.g
Labels: vulcan/reviewed

#6587 [Dictionary] From mobileGetLocationHistory to mobileStartTrakingSensor
  docs/dictionary/command/mobilePickMedia.lcdoc
  docs/dictionary/command/mobilePickPhoto.lcdoc
  docs/dictionary/command/mobilePlaySoundOnChannel.lcdoc
  docs/dictionary/command/mobileSetLocationHistoryLimit.lcdoc
  docs/dictionary/command/mobileStartTrackingSensor.lcdoc
  docs/dictionary/function/mobileGetLocationHistory.lcdoc
  docs/dictionary/function/mobileOrientation.lcdoc
  docs/dictionary/function/mobilePixelDensity.lcdoc
  docs/dictionary/function/mobilePreferredLanguages.lcdoc
  docs/dictionary/function/mobileSoundChannelStatus.lcdoc
Labels: vulcan/reviewed

#6654 [Bugfix 21494] Correct missing text issue in Round entry
  docs/dictionary/function/round.lcdoc
  docs/notes/bugfix-21494.md
Labels: vulcan/reviewed

#6651 Dictionary updates
  engine/src/canvas.lcb
  engine/src/widget.lcb
Labels: bug, documentation, vulcan/reviewed

#6650 [[ Android Archs ]] Add multiple android archs to IDE
  Installer/package.txt
  builder/builder_utilities.livecodescript
  builder/tools_builder.livecodescript
  docs/notes/feature-androidarchs.md
  ide-support/revdeploylibraryandroid.livecodescript
  ide-support/revsaveasandroidstandalone.livecodescript
  ide-support/revsblibrary.livecodescript
Labels: enhancement, vulcan/reviewed

#6655 [[ Bug 21527 ]] Include iPadPro splash image in plist file
  docs/notes/bugfix-21527.md
  ide-support/revsaveasiosstandalone.livecodescript
Labels: vulcan/reviewed

#6658 Merge release 9.0.1 27 08 2018
  docs/dictionary/command/androidRequestPermission.lcdoc
  docs/dictionary/function/androidHasPermission.lcdoc
  docs/dictionary/function/androidPermissionExists.lcdoc
  docs/notes/bugfix-21396.md
  docs/notes/bugfix-21417.md
  docs/notes/bugfix-21434.md
  docs/notes/bugfix-21443.md
  docs/notes/bugfix-21496.md
  docs/notes/feature-android_runtime_permissions.md
  engine/rsrc/emscripten-startup-template.livecodescript
  engine/src/cgimageutil.cpp
  engine/src/exec-misc.cpp
  engine/src/exec.h
  engine/src/executionerrors.h
  engine/src/java/com/runrev/android/Engine.java
  engine/src/java/com/runrev/android/LiveCodeActivity.java
  engine/src/java/com/runrev/android/SensorModule.java
  engine/src/mac-cursor.mm
  engine/src/mac-surface.mm
  engine/src/mblandroidcamera.cpp
  engine/src/mblandroidcontact.cpp
  engine/src/mblandroiddc.cpp
  engine/src/mblandroidfs.cpp
  engine/src/mblandroidmisc.cpp
  engine/src/mblandroidsensor.cpp
  engine/src/mblandroidutil.h
  engine/src/mblhandlers.cpp
  engine/src/mbliphonegfx.mm
  engine/src/mbliphonemisc.mm
  engine/src/mblsyntax.h
  engine/src/redraw.cpp
  ide-support/revsaveasemscriptenstandalone.livecodescript
Labels: vulcan/reviewed

#6636 [21476] Ensure "the extents of tArray" returns empty when keys are not integers
  docs/notes/bugfix-21476.md
  engine/src/exec-array.cpp
  libfoundation/include/foundation.h
  libfoundation/src/foundation-number.cpp
  tests/lcs/core/array/array.livecodescript
Labels: bug, vulcan/reviewed

#6637 [Bug 21491] Ensure pageRanges and pageHeights return correct results
  docs/notes/bugfix-21491.md
  engine/src/paragraf.cpp
  tests/lcs/core/field/_pageHeightsFieldContent.txt
  tests/lcs/core/field/pageHeights.livecodescript
Labels: bug, vulcan/reviewed

#6662 [[ Bug 21532 ]] Move dragboard rebind to mousedown
  docs/notes/bugfix-21532.md
  engine/src/desktop.cpp
Labels: bug, vulcan/reviewed

#6666 [9.0.1 RC3] Updated version
  version
Labels: vulcan/reviewed

#6667 [Dictionary] mobileStoreProductProperty to nameChanged
  docs/dictionary/command/mobileStoreRestorePurchases.lcdoc
  docs/dictionary/command/modal.lcdoc
  docs/dictionary/command/modeless.lcdoc
  docs/dictionary/command/move.lcdoc
  docs/dictionary/function/mobileStoreProductProperty.lcdoc
  docs/dictionary/function/mouseCharChunk.lcdoc
  docs/dictionary/function/mouseChunk.lcdoc
  docs/dictionary/function/mouseText.lcdoc
  docs/dictionary/keyword/modemcolon.lcdoc
  docs/dictionary/message/mouseLeave.lcdoc
  docs/dictionary/message/mouseMove.lcdoc
  docs/dictionary/message/mouseStillDown.lcdoc
  docs/dictionary/message/mouseUpInBackdrop.lcdoc
  docs/dictionary/message/mouseWithin.lcdoc
  docs/dictionary/message/nameChanged.lcdoc
  docs/dictionary/property/multipleHilites.lcdoc
  docs/dictionary/property/name.lcdoc
Labels: vulcan/reviewed

#6634 Bugfix 21458 - Document "number of elements of tArray"
  docs/dictionary/function/number.lcdoc
  docs/notes/bugfix-21458.md
Labels: vulcan/reviewed
