Repository livecode/livecode, pull requests merged in 2018-05, with the labels that each got.

#6503 [[ Bug 21155 ]] Fix JS error when closing stack window
  docs/notes/bugfix-21155.md
  engine/src/em-dc.js
Labels: LCS, bug, vulcan/reviewed

#6424 [Dictionary] "implicit focus" to "is in"
  docs/dictionary/command/iphoneClearTouches.lcdoc
  docs/dictionary/function/interrupt.lcdoc
  docs/dictionary/function/intersect.lcdoc
  docs/dictionary/keyword/in.lcdoc
  docs/dictionary/keyword/int1.lcdoc
  docs/dictionary/keyword/int2.lcdoc
  docs/dictionary/keyword/int4.lcdoc
  docs/dictionary/operator/is-among-the-keys-of.lcdoc
  docs/dictionary/operator/is-in.lcdoc
  docs/dictionary/property/ink.lcdoc
  docs/dictionary/property/innershadow.lcdoc
  docs/glossary/i/implicit-focus.lcdoc
Labels: vulcan/reviewed

#6493 [bugfix-15614] (Take two) Fix display issue with URLEncode code example
  docs/dictionary/function/URLEncode.lcdoc
Labels: vulcan/reviewed

#6505 [Dictionary] Changes from licenced to load extension
  docs/dictionary/command/load-extension.lcdoc
  docs/dictionary/command/load.lcdoc
  docs/dictionary/function/licensed.lcdoc
  docs/dictionary/function/ln.lcdoc
  docs/dictionary/keyword/line.lcdoc
  docs/dictionary/property/listBehavior.lcdoc
  docs/dictionary/property/listStyle.lcdoc
  docs/glossary/l/LiveCode-Builder-extension.lcdoc
  docs/glossary/l/LiveCode-Builder-language.lcdoc
  docs/glossary/l/LiveCode-custom-library.lcdoc
Labels: vulcan/reviewed

#6514 [Dictionary] lossless compression to md5Digest
  docs/dictionary/function/macToISO.lcdoc
  docs/dictionary/function/mainStacks.lcdoc
  docs/dictionary/function/md5Digest.lcdoc
  docs/dictionary/keyword/LPT1colon.lcdoc
  docs/dictionary/message/mainStackChanged.lcdoc
  docs/dictionary/property/margins.lcdoc
  docs/glossary/l/lossless-compression.lcdoc
  docs/glossary/m/MacBinary.lcdoc
  docs/glossary/m/master-profile.lcdoc
Labels: vulcan/reviewed

#6517 [[ Bug 20570 ]] Fix MySQL errors after calling stored procedures
  docs/notes/bugfix-20570.md
  revdb/src/mysql_connection.cpp
Labels: LCS, bug, vulcan/reviewed

#6478 [[ Bug ]] Fix PointerToObjcObject
  libscript/src/objc.lcb
Labels: bug, vulcan/reviewed

#6516 LCIDL iOS build script tweaks
  lcidlc/lclink.sh
Labels: vulcan/reviewed

#6312 [Dictionary] changes from hilitedLine to imageSource
  docs/dictionary/function/hostNameToAddress.lcdoc
  docs/dictionary/keyword/http.lcdoc
  docs/dictionary/keyword/https.lcdoc
  docs/dictionary/message/IDChanged.lcdoc
  docs/dictionary/property/HTMLText.lcdoc
  docs/dictionary/property/ID.lcdoc
  docs/dictionary/property/hilitePattern.lcdoc
  docs/dictionary/property/hilitedLine.lcdoc
  docs/dictionary/property/icon.lcdoc
  docs/dictionary/property/iconic.lcdoc
  docs/dictionary/property/imageSource.lcdoc
Labels: vulcan/reviewed

#6515 [Bug 12675] Ensure sound can be queued with mobilePlaySoundOnChannel
  docs/notes/bugfix-12675.md
  engine/src/java/com/runrev/android/SoundModule.java
Labels: bug, vulcan/reviewed

#6520 [Dictionary] menubar to mobileClearTouches
  docs/dictionary/command/mobileCancelAllLocalNotifications.lcdoc
  docs/dictionary/command/mobileClearTouches.lcdoc
  docs/dictionary/function/menuButton.lcdoc
  docs/dictionary/function/messageDigest.lcdoc
  docs/dictionary/keyword/middle.lcdoc
  docs/dictionary/keyword/minimize.lcdoc
  docs/dictionary/message/menuPick.lcdoc
  docs/dictionary/property/menuHistory.lcdoc
  docs/dictionary/property/menuMode.lcdoc
  docs/dictionary/property/menubar.lcdoc
  docs/dictionary/property/mimeText.lcdoc
  docs/dictionary/property/minHeight.lcdoc
  docs/dictionary/property/minimizeBox.lcdoc
Labels: vulcan/reviewed

#6513 [Dictionary] loadedExtensions to lookAndFeel
  docs/dictionary/command/local.lcdoc
  docs/dictionary/command/lock-error-dialogs.lcdoc
  docs/dictionary/command/lock-messages.lcdoc
  docs/dictionary/function/loadedExtensions.lcdoc
  docs/dictionary/function/localNames.lcdoc
  docs/dictionary/function/longFilePath.lcdoc
  docs/dictionary/property/location.lcdoc
  docs/dictionary/property/lockMessages.lcdoc
  docs/dictionary/property/lockMoves.lcdoc
  docs/dictionary/property/lockRecent.lcdoc
  docs/dictionary/property/lockScreen.lcdoc
  docs/dictionary/property/longWindowTitles.lcdoc
  docs/dictionary/property/lookAndFeel.lcdoc
Labels: vulcan/reviewed

#6526 [8.1.10-rc2] Updated version
  version
Labels: vulcan/reviewed

#6528 Merge release 8.1.10 15.05.2018
  docs/notes/bugfix-21228.md
  engine/src/mblandroiddc.cpp
  version
Labels: clean merge, vulcan/reviewed

#6529 Merge develop 8.1 15.05.2018
  docs/notes/bugfix-21228.md
  engine/src/mblandroiddc.cpp
Labels: vulcan/reviewed

#6504 [Dictionary] Changes from is not strictly to libURLSetStatusCallback
  docs/dictionary/command/libURLSetStatusCallback.lcdoc
  docs/dictionary/function/libURLLastHTTPHeaders.lcdoc
  docs/dictionary/function/libURLftpCommand.lcdoc
  docs/dictionary/keyword/it.lcdoc
  docs/dictionary/keyword/item.lcdoc
  docs/dictionary/keyword/last.lcdoc
  docs/dictionary/operator/is-not-strictly.lcdoc
  docs/glossary/k/keyboard-equivalent.lcdoc
  docs/glossary/l/library-extension.lcdoc
  docs/glossary/l/library.lcdoc
Labels: vulcan/reviewed

#6507 [[ Bug 21246 ]] Fix crash on windows clipboard
  docs/notes/bugfix-21246.md
  engine/src/w32-clipboard.cpp
  engine/src/w32-clipboard.h
Labels: blocker, bug, vulcan/reviewed

#6538 Updated version for 8.1.10
  version
Labels: vulcan/reviewed

#6508 [[ Bug 21207 ]] Make sure scripts are compiled when testing if object handles message
  docs/notes/bugfix-21207.md
  engine/src/object.cpp
Labels: LCS, bug, vulcan/reviewed

#6523 [21271] Fix crash when setting markerpoints of a grc in repeat loop
  docs/notes/bugfix-21271.md
  engine/src/exec-interface-graphic.cpp
Labels: bug, vulcan/reviewed

#6510 [[ Bug 21051 ]] Handle wchar_t size differences for ODBC
  docs/notes/bugfix-21051.md
  revdb/src/dbodbc.h
  revdb/src/odbc_connection.cpp
  revdb/src/odbc_cursor.cpp
Labels: bug, vulcan/reviewed

#6499 [[ Bug 19465 ]] Force orientation when setting allowed orientations
  docs/notes/bugfix-19465.md
  engine/src/mblandroidorientation.cpp
Labels: bug, vulcan/reviewed

#6509 [10694] Ensure S/B throws an error if Android SDK is not set or is invalid
  docs/notes/bugfix-10694.md
  ide-support/revsaveasandroidstandalone.livecodescript
Labels: vulcan/reviewed

#6541 [[ LCB ]] [[ Emscripten ]] Fix issues resolving foreign handlers and types in emscripten
  libscript/src/script-module.cpp
  toolchain/lc-compile/src/emit.cpp
Labels: LCB, bug, vulcan/reviewed

#6501 [[ Emscripten ]] Update emscripten deployment to use livecode capsule format
  engine/rsrc/emscripten-startup-template.livecodescript
  engine/src/deploy_emscripten.cpp
  engine/src/mode_standalone.cpp
  engine/src/stacksecurity.cpp
  engine/src/stacksecurity.h
  ide-support/revsaveasemscriptenstandalone.livecodescript
Labels: LCS, enhancement, vulcan/reviewed

#6539 [[ Bug 21297 ]] Fix issue with importing foreign value types that require conversion
  docs/lcb/notes/21297.md
  libscript/src/script-execute.hpp
Labels: LCB, bug, vulcan/reviewed

#6527 [21278] Ensure playrate is respected when looping or when starting player after a pause
  docs/notes/bugfix-21278.md
  engine/src/mac-av-player.mm
  engine/src/player-platform.cpp
Labels: bug, vulcan/reviewed

#6545 [Bugfix 15086] Add mention of usePixelScaling's Android error throwing
  docs/dictionary/property/usePixelScaling.lcdoc
  docs/notes/bugfix-15086.md
Labels: vulcan/reviewed

#6544 [[ Bug 21302 ]] Make message box 'put' immune to 'lock messsages'
  docs/notes/bugfix-21302.md
  engine/src/debug.cpp
Labels: bug, vulcan/reviewed

#6547 [[ Bug 21234 ]] Dictionary: revDataFromQuery / revQueryDatabase
  docs/dictionary/function/revDataFromQuery.lcdoc
  docs/dictionary/function/revQueryDatabase.lcdoc
  docs/notes/bugfix-21234.md
Labels: bug, vulcan/reviewed

#6519 [[ Bug 15443 ]] Don't clobber macroman casing tables on mac
  docs/notes/bugfix-15443.md
  engine/src/dskmac.cpp
  engine/src/sysspec.cpp
  tests/lcs/core/strings/filter.livecodescript
Labels: bug, vulcan/reviewed

#6550 Revert "[[ Emscripten ]] Fix unresolved foreign handlers in certain modules"
  toolchain/lc-compile/src/emit.cpp
Labels: blocker, vulcan/reviewed

#6533 [[ Bug 21250 ]] Fix crash which may occur when selected objects are deleted
  docs/notes/bugfix-21250.md
  engine/src/sellst.cpp
Labels: LCS, bug, vulcan/reviewed

#6546 [[ Bug ]] Fix MCCanvasImageGetPixels
  engine/src/module-canvas.cpp
Labels: bug, vulcan/reviewed

#6522 [[ Bug 19651 ]] Fix mirroring issues with video displayed using non-ARGB32 bitmap formats
  docs/notes/bugfix-19651.md
  engine/src/w32-ds-player.cpp
Labels: LCS, bug, vulcan/reviewed

#6551 Added support for building with Xcode9.4 / iOS 11.4 SDK
  Installer/package.txt
  Makefile
  buildbot.py
  docs/notes-base/platforms.md
  ide-support/revdeploylibraryios.livecodescript
  prebuilt/fetch-libraries.sh
  prebuilt/scripts/ios.inc
  tools/setup_xcode_sdks.py
Labels: vulcan/reviewed

#6531 [Dictionary] Changes from mobileCanMakePurchase to mobileLocationAuthorizationStatus
  docs/dictionary/command/mobileComposeHtmlMail.lcdoc
  docs/dictionary/command/mobileComposeUnicodeMail.lcdoc
  docs/dictionary/command/mobileControlCreate.lcdoc
  docs/dictionary/command/mobileCreateLocalNotification.lcdoc
  docs/dictionary/function/mobileCanMakePurchase.lcdoc
  docs/dictionary/function/mobileControlGet.lcdoc
  docs/dictionary/function/mobileGetLaunchData.lcdoc
  docs/dictionary/function/mobileGetLocationHistoryLimit.lcdoc
  docs/dictionary/function/mobileGetNotificationDetails.lcdoc
  docs/dictionary/function/mobileLocationAuthorizationStatus.lcdoc
Labels: vulcan/reviewed
