Repository livecode/livecode, pull requests merged in 2018-06, with the labels that each got.

#6521 [[ SVG ]] Add support for 'currentColor' paint type
  engine/src/idraw.cpp
  engine/src/image.cpp
  engine/src/image.h
  engine/src/image_rep.cpp
  engine/src/module-canvas-internal.h
  engine/src/module-canvas.cpp
  engine/src/module-canvas.h
  extensions/script-libraries/drawing/drawing.livecodescript
  libgraphics/include/graphics.h
  libgraphics/src/context.cpp
  libgraphics/src/drawing.cpp
  libgraphics/src/utils.cpp
Labels: enhancement, vulcan/reviewed

#6494 [Bug 21217] Prevent crash when calling quit from a stack with a non empty imagesource
  docs/notes/bugfix-21217.md
  engine/src/field.cpp
Labels: bug, vulcan/reviewed

#6554 [Bug 21321] Throw error when getting the hostnametoaddress with no param
  docs/notes/bugfix-21321.md
  engine/src/express.cpp
  tests/lcs/parser/unary-function.parsertest
Labels: bug, vulcan/reviewed

#6555 [[ Bug 20631 ]] Don't assume Intent action is non-null
  docs/notes/bugfix-20631.md
  engine/src/java/com/runrev/android/NFCModule.java
Labels: bug, vulcan/reviewed

#6557 [[ Docs ]] Clarify the role of angle brackets in the syntax element
  docs/guides/LiveCode Documentation Format Reference.md
Labels: vulcan/reviewed

#6559 [[ mergExt ]] update pointer
  builder/builder_utilities.livecodescript
Labels: vulcan/reviewed

#6561 [[ Buildbot ]] Move platform triples to config.py
  buildbot.py
  config.py
  prebuilts-buildbot.py
Labels: cleanup, vulcan/reviewed

#6553 [[ Bug 19094 ]] Ensure single codepoint grapheme clusters are checked
  docs/notes/bugfix-19094.md
  libgraphics/src/harfbuzztext.cpp
Labels: bug, vulcan/reviewed

#6564 [[ Bug 21326 ]] Preserve binary when modifying with data exec value
  docs/notes/bugfix-21326.md
  engine/src/exec-engine.cpp
  engine/src/variable.cpp
  tests/lcs/core/engine/put.livecodescript
Labels: bug, vulcan/reviewed

#6562 [[ Bug 21333 ]] Allow aggregates to contain nullptrs
  docs/lcb/notes/feature-nullable_aggregate_fields.md
  libfoundation/src/foundation-foreign.cpp
  tests/lcb/vm/foreign-aggregate.lcb
Labels: enhancement, vulcan/reviewed

#6310 [[ Bug 20931 ]] Bridge values in LCB assign-array and assign-list ops
  docs/guides/LiveCode Builder Language Reference.md
  docs/lcb/notes/20931.md
  libscript/src/script-bytecode.hpp
  libscript/src/script-execute.cpp
  libscript/src/script-execute.hpp
  tests/lcb/compiler/frontend/variadic.compilertest
  tests/lcb/vm/assign-ops.lcb
  toolchain/lc-compile/src/check.g
  toolchain/lc-compile/src/support.g
  toolchain/libcompile/src/report.c
Labels: LCB, bug, vulcan/reviewed

#6549 [[ ClipToPath ]] Implement clip to path
  docs/lcb/notes/feature-cliptopath.md
  engine/src/canvas.lcb
  engine/src/module-canvas.cpp
  engine/src/module-canvas.h
  libgraphics/include/graphics.h
  libgraphics/src/context.cpp
Labels: LCB, enhancement, vulcan/reviewed

#6567 [19900] Ensure tsNet can be unloaded
  docs/notes/bugfix-19900.md
  ide-support/revsblibrary.livecodescript
Labels: bug, vulcan/reviewed

#6568 [[ Drawing ]] Fallback to relative resource path
  extensions/script-libraries/drawing/drawing.livecodescript
Labels: vulcan/reviewed

#6566 [[ Bug 20552 ]] Use content:// uris to transfer file data to/from other apps
  docs/notes/bugfix-20552.md
  engine/AndroidManifest.xml
  engine/engine-sources.gypi
  engine/src/java/AppProvider.java
  engine/src/java/com/runrev/android/AppProvider.java
  engine/src/java/com/runrev/android/AttachmentProvider.java
  engine/src/java/com/runrev/android/Email.java
  engine/src/java/com/runrev/android/Engine.java
  engine/src/java/com/runrev/android/FileProvider.java
  ide-support/revsaveasandroidstandalone.livecodescript
Labels: LCS, bug, vulcan/reviewed

#6574 [[ Bug 19420 ]] Android: fix crash on relaunch when calling extension handler from script
  docs/notes/bugfix-19420_extensionshandlermap.md
  engine/src/exec-extension.cpp
Labels: LCS, bug, vulcan/reviewed

#6575 [[ Bug 21352 ]] fix potential crash on relaunch due to uninitialized static variable
  docs/notes/bugfix-21352.md
  libfoundation/src/system-library.cpp
Labels: LCS, bug, vulcan/reviewed

#6577 [[ Bug 21253 ]] Add release note
  docs/notes/bugfix-21253.md
Labels: vulcan/reviewed

#6576 [[ tsNet ]] Update pointer
  builder/builder_utilities.livecodescript
Labels: vulcan/reviewed

#6571 [[ Foundation ]] Ensure true and false names are finalized
  libfoundation/src/foundation-name.cpp
Labels: bug, vulcan/reviewed

#6578 [Bug 13266] Ensure option menu works on Android
  docs/notes/bugfix-13266.md
  engine/src/button.cpp
  engine/src/mblandroidmisc.cpp
Labels: bug, enhancement, vulcan/reviewed

#6580 [21345] Ensure horizontal property of segmented control is saved
  extensions/widgets/segmented/notes/21345.md
  extensions/widgets/segmented/segmented.lcb
Labels: bug, vulcan/reviewed

#6556 [[ API 26 ]] Update android compile sdk to API 26
  config.py
  config/android.gypi
  docs/development/build-android.md
  docs/notes/bugfix-20550.md
  engine/src/java/com/runrev/android/nativecontrol/ExtVideoView.java
  ide-support/revdeploylibraryandroid.livecodescript
  libcore/src/filesystem.cpp
  prebuilt/build-libraries.sh
  prebuilt/fetch-libraries.sh
  prebuilt/libicu.gyp
  prebuilt/libopenssl.gyp
  prebuilt/package-libs.sh
  prebuilt/scripts/android.inc
  prebuilt/scripts/build-icu.sh
  prebuilt/scripts/build-openssl.sh
Labels: bug, vulcan/reviewed

#6585 Merge develop 9.0 21.06.18
  builder/builder_utilities.livecodescript
  config.py
  config/android.gypi
  docs/development/build-android.md
  docs/guides/LiveCode Builder Language Reference.md
  docs/lcb/notes/20931.md
  docs/notes/bugfix-13266.md
  docs/notes/bugfix-19420_extensionshandlermap.md
  docs/notes/bugfix-19900.md
  docs/notes/bugfix-20550.md
  docs/notes/bugfix-20552.md
  docs/notes/bugfix-21253.md
  docs/notes/bugfix-21352.md
  engine/AndroidManifest.xml
  engine/engine-sources.gypi
  engine/src/button.cpp
  engine/src/exec-extension.cpp
  engine/src/java/AppProvider.java
  engine/src/java/com/runrev/android/AppProvider.java
  engine/src/java/com/runrev/android/AttachmentProvider.java
  engine/src/java/com/runrev/android/Email.java
  engine/src/java/com/runrev/android/Engine.java
  engine/src/java/com/runrev/android/FileProvider.java
  engine/src/mblandroidmisc.cpp
  extensions/widgets/segmented/notes/21345.md
  extensions/widgets/segmented/segmented.lcb
  ide-support/revdeploylibraryandroid.livecodescript
  ide-support/revsaveasandroidstandalone.livecodescript
  ide-support/revsblibrary.livecodescript
  libcore/src/filesystem.cpp
  libfoundation/src/foundation-name.cpp
  libfoundation/src/system-library-mac.hpp
  libfoundation/src/system-library.cpp
  libscript/src/script-bytecode.hpp
  libscript/src/script-execute.cpp
  libscript/src/script-execute.hpp
  prebuilt/build-libraries.sh
  prebuilt/fetch-libraries.sh
  prebuilt/libicu.gyp
  prebuilt/libopenssl.gyp
  prebuilt/package-libs.sh
  prebuilt/scripts/android.inc
  prebuilt/scripts/build-icu.sh
  prebuilt/scripts/build-openssl.sh
  tests/lcb/compiler/frontend/variadic.compilertest
  tests/lcb/vm/assign-ops.lcb
  toolchain/lc-compile/src/check.g
  toolchain/lc-compile/src/support.g
  toolchain/libcompile/src/report.c
Labels: vulcan/reviewed

#6581 Accelerated rendering issues
  docs/notes/bugfix-16366.md
  docs/notes/bugfix-16736.md
  docs/notes/bugfix-21279.md
  docs/notes/bugfix-21336.md
  docs/notes/bugfix-21356.md
  engine/src/em-dc.cpp
  engine/src/java/com/runrev/android/Engine.java
  engine/src/mblandroiddc.cpp
  engine/src/mblandroidmisc.cpp
  engine/src/mbldc.cpp
  engine/src/redraw.cpp
  engine/src/stack.cpp
  engine/src/stack.h
  engine/src/stack2.cpp
  engine/src/stack3.cpp
  engine/src/stackview.cpp
Labels: STG Stack, bug, vulcan/reviewed

#6589 Force targetSdkVersion to API 26
  engine/rsrc/android-manifest.xml
Labels: bug, vulcan/reviewed

#6588 [[ API 26 ]] Use app platform 16 with target sdk 26
  config.py
  config/android.gypi
  docs/development/build-android.md
  prebuilt/fetch-libraries.sh
  prebuilt/libicu.gyp
  prebuilt/libopenssl.gyp
Labels: blocker, vulcan/reviewed

#6586 [[ mergExt ]] android archs
  builder/builder_utilities.livecodescript
  ide-support/revsaveasandroidstandalone.livecodescript
Labels: enhancement, vulcan/reviewed

#6590 [[ ExtensionUtils ]] Don't load externals in standalone mode
  extensions/script-libraries/extension-utils/extension-utils.livecodescript
Labels: bug, vulcan/reviewed

#6598 [[ Bug 21386 ]] Set clipsToBounds of native container layer
  docs/notes/bugfix-21386.md
  engine/src/native-layer-ios.mm
Labels: bug, vulcan/reviewed

#6596 [[ Bug ]] Redraw the entire stack before hiding bitmap view
  engine/src/mblandroiddc.cpp
Labels: bug, vulcan/reviewed

#6599 Remove unsupported Android min versions
  ide-support/revdeploylibraryandroid.livecodescript
Labels: vulcan/reviewed

#6593 [Bug 21368] Ensure device can register for and receive remote notifications on Android
  docs/notes/bugfix-21368.md
  engine/src/java/com/runrev/android/NotificationModule.java
Labels: bug, vulcan/reviewed

#6560 [[ Bug 21304 ]] Clear unshared data when compacting stack
  docs/notes/bugfix-21304.md
  engine/src/stack2.cpp
Labels: bug, vulcan/reviewed

#6535 [21171] Ensure unicode characters in app label are shown correctly
  docs/notes/bugfix-21171.md
  ide-support/revsaveasandroidstandalone.livecodescript
Labels: bug, vulcan/reviewed
