Repository livecode/livecode, pull requests merged in 2018-09, with the labels that each got.

#6672 [[ Bug 21532 ]] Move clear before creation of clipboard item
  engine/src/clipboard.cpp
Labels: bug, vulcan/reviewed

#6673 [[ Bug 21532 ]] Remove AutoLock from AddTextToItem
  engine/src/clipboard.cpp
Labels: bug, vulcan/reviewed

#6652 [[ Bug 20193 ]] Retain mouse focus when taking snapshot
  docs/notes/bugfix-20193.md
  engine/src/w32dcs.cpp
Labels: bug, vulcan/reviewed

#6679 Merge release 9.0.1 07.09.2018
  docs/notes/bugfix-21532.md
  engine/src/clipboard.cpp
  engine/src/desktop.cpp
Labels: vulcan/reviewed

#6675 [[ Bug 21567 ]] Tree View Widget hilitedElement execution error
  extensions/widgets/treeview/notes/21567.md
  extensions/widgets/treeview/treeview.lcb
Labels: vulcan/reviewed

#6670 [21529] Fixed typo and example in Release notes
  docs/notes-base/breaking_changes.md
  docs/notes/bugfix-21529.md
Labels: vulcan/reviewed

#6680 [9.0.1] Updated version
  version
Labels: vulcan/reviewed

#6684 [Bugfix-21406] Add missing keyboard types to mobileSetKeyboardType
  docs/dictionary/command/mobileSetKeyboardType.lcdoc
  docs/notes/bugfix-21406.md
Labels: bug, vulcan/reviewed

#6685 [Bugfix 21104] Remove extraneous text from syntax in print entry
  docs/dictionary/command/print.lcdoc
  docs/notes/bugfix-21104.md
Labels: vulcan/reviewed

#6677 [Bugfix-21436] Clarify the behaviour of repeat with in docs
  docs/dictionary/control_st/repeat.lcdoc
  docs/notes/bugfix-21436.md
Labels: vulcan/reviewed

#6687 [Bugfix-21270] Add requirement note for using SQLite with revOpenDatabase
  docs/dictionary/function/revOpenDatabase.lcdoc
  docs/notes/bugfix-21270.md
Labels: bug, enhancement, vulcan/reviewed

#6678 [21552] Check if the name is taken before creating the standalone folder
  docs/notes/bugfix-21552.md
  ide-support/revsaveasstandalone.livecodescript
  tests/ide-support/standalonebuilder/_support.livecodescript
Labels: bug, vulcan/reviewed

#6692 [21453] Fix crash when calling 'open process'
  docs/notes/bugfix-21453.md
  engine/src/dskmac.cpp
Labels: bug, vulcan/reviewed

#6689 [[ Deploy ]] Handle payload and project out of order on windows
  engine/src/deploy_windows.cpp
Labels: bug, vulcan/reviewed

#6694 Correct code example and clarify about close/open messages
  docs/notes-base/breaking_changes.md
Labels: vulcan/reviewed

#6691 [[ Bug 19670 ]] Fix effective working screenrect on Android
  docs/notes/bugfix-19670.md
  engine/src/java/com/runrev/android/Engine.java
Labels: bug, vulcan/reviewed

#6698 [[Android Browser]] Allow cross-origin requests for "file:" protocol scheme
  docs/notes/bugfix-21595.md
  engine/src/java/com/runrev/android/libraries/LibBrowser.java
  engine/src/java/com/runrev/android/nativecontrol/BrowserControl.java
Labels: bug, vulcan/reviewed

#6624 [[ Cleanup ]] Remove unused variable
  config.py
  config/WorkspaceSettings.xcsettings
  libgraphics/src/drawing.cpp
Labels: cleanup, vulcan/reviewed

#6695 [Bugfix-21592] Correct typos in revOpenDatabase
  docs/dictionary/function/revOpenDatabase.lcdoc
  docs/notes/Bugfix-21592.md
Labels: vulcan/reviewed
