Repository livecode/livecode, pull requests merged in 2018-12, with the labels that each got.

#6806 [21720] Ensure revsecurity and revpdfprinter are of the correct arch
  docs/notes/bugfix-21720.md
  ide-support/revsaveasstandalone.livecodescript
  ide-support/revsblibrary.livecodescript
Labels: blocker, vulcan/reviewed

#6814 [9.0.2] Updated version
  version
Labels: vulcan/reviewed

#6818 [Dictionary] revSetSpeechPitch to revXMLAddNote
  docs/dictionary/command/revSetSpeechPitch.lcdoc
  docs/dictionary/command/revSetSpeechSpeed.lcdoc
  docs/dictionary/command/revSetSpeechVoice.lcdoc
  docs/dictionary/command/revSetStackFileProfile.lcdoc
  docs/dictionary/command/revSetVideoGrabSettings.lcdoc
  docs/dictionary/command/revSetVideoGrabberRect.lcdoc
  docs/dictionary/command/revUpdateGeometry.lcdoc
  docs/dictionary/command/revVideoGrabDialog.lcdoc
  docs/dictionary/command/revVideoGrabIdle.lcdoc
  docs/dictionary/command/revVideoGrabSettings.lcdoc
  docs/dictionary/command/revXMLAddDTD.lcdoc
  docs/dictionary/command/revXMLAddNode.lcdoc
  docs/dictionary/function/revUnixFromMacPath.lcdoc
Labels: vulcan/reviewed

#6820 [Bugfix-21718] Mention calling mobileSensorAvailable before mobileCurrentLocation
  docs/dictionary/function/mobileCurrentLocation.lcdoc
  docs/notes/bugfix-21718.md
Labels: vulcan/reviewed

#6780 [21663] Fix error in S/B for Android when TimeZone lib is included
  docs/notes/bugfix-21663.md
  ide-support/revsaveasandroidstandalone.livecodescript
Labels: bug, vulcan/reviewed

#6823 [21738] Ensure hide with visual effect scroll does actually scroll
  docs/notes/bugfix-21738.md
  engine/src/stacke.cpp
Labels: bug, vulcan/reviewed

#6822 [21378] Ensure adding/deleting/moving items does not change the existing itemNames
  extensions/widgets/navbar/navbar.lcb
  extensions/widgets/navbar/notes/21378.md
Labels: bug, vulcan/reviewed

#6825 [[ Bug 21674 ]] Apply redirect to resource path on macOS
  docs/notes/bugfix-21674.md
  engine/src/dskmac.cpp
  engine/src/mode_standalone.cpp
Labels: bug, vulcan/reviewed

#6817 [20711] Ensure the tooltip of tree widget can be set more than once
  extensions/widgets/treeview/notes/20711.md
  extensions/widgets/treeview/treeview.lcb
Labels: bug, vulcan/reviewed

#6816 [21728] Ensure one can set the image filename to a relative path
  docs/notes/bugfix-21728.md
  engine/src/ifile.cpp
Labels: bug, vulcan/reviewed

#6826 [Bugfix-21744] Remove duplicate code example from format entry
  docs/dictionary/function/format.lcdoc
  docs/notes/bugfix-21744.md
Labels: bug, vulcan/reviewed

#6827 [Bugfix 21340] Update setup docs for replaced argument.
  docs/notes-base/setup.md
  docs/notes/bugfix-21340.md
Labels: bug, vulcan/reviewed

#6815 [19277] Ensure the effective rect is fetched correctly when screen is locked
  docs/notes/bugfix-19277.md
  engine/src/desktop-stack.cpp
  engine/src/lnxstack.cpp
  engine/src/w32stack.cpp
  tests/lcs/core/engine/engine.livecodescript
Labels: bug, vulcan/reviewed

#6824 [Dictionary] revXMLAttribute to revXMLPreviousSibling
  docs/dictionary/function/revXMLAttribute.lcdoc
  docs/dictionary/function/revXMLAttributeValues.lcdoc
  docs/dictionary/function/revXMLChildContents.lcdoc
  docs/dictionary/function/revXMLChildNames.lcdoc
  docs/dictionary/function/revXMLDataFromXPathQuery.lcdoc
  docs/dictionary/function/revXMLEvaluateXPath.lcdoc
  docs/dictionary/function/revXMLFirstChild.lcdoc
  docs/dictionary/function/revXMLNextSibling.lcdoc
  docs/dictionary/function/revXMLNodeContents.lcdoc
  docs/dictionary/function/revXMLParent.lcdoc
  docs/dictionary/function/revXMLPreviousSibling.lcdoc
Labels: vulcan/reviewed

#6833 [Dictionary] save to serialControlString
  docs/dictionary/command/save.lcdoc
  docs/dictionary/command/secure-socket.lcdoc
  docs/dictionary/command/select.lcdoc
  docs/dictionary/command/send-to-program.lcdoc
  docs/dictionary/function/screenDepth.lcdoc
  docs/dictionary/function/selectedLoc.lcdoc
  docs/dictionary/message/scrollbarPageDec.lcdoc
  docs/dictionary/message/scrollbarPageInc.lcdoc
  docs/dictionary/message/searchKey.lcdoc
  docs/dictionary/property/screenMouseLoc.lcdoc
  docs/dictionary/property/secureMode.lcdoc
  docs/dictionary/property/serialControlString.lcdoc
Labels: vulcan/reviewed
