Repository livecode/livecode, pull requests merged in 2018-02, with the labels that each got.

#6321 [20946] Remove 32bit slice from Mac externals if we build for 64bit only
  docs/notes/bugfix-20946.md
  ide-support/revsaveasstandalone.livecodescript
  ide-support/revsblibrary.livecodescript
Labels: blocker, bug, vulcan/reviewed

#6324 [Bug 20963] Make md5() private
  ide-support/revliburl.livecodescript
Labels: vulcan/reviewed

#6268 [[ TileCache ]] Selection Layer
  engine/src/card.cpp
  engine/src/card.h
  engine/src/control.cpp
  engine/src/edittool.cpp
  engine/src/edittool.h
  engine/src/exec-interface-graphic.cpp
  engine/src/graphic.cpp
  engine/src/graphic.h
  engine/src/group.cpp
  engine/src/group.h
  engine/src/mccontrol.h
  engine/src/player-legacy.cpp
  engine/src/player-srv-stubs.cpp
  engine/src/redraw.cpp
  engine/src/tilecache.cpp
Labels: bug, vulcan/reviewed

#6318 [[ Bug 20952 ]] Init system correctly on windows server
  docs/notes/bugfix-20952.md
  engine/src/dskw32.cpp
Labels: bug, vulcan/reviewed

#6326 [[ Prebuilts ]] Update download url for ICU
  prebuilt/scripts/build-icu.bat
  prebuilt/scripts/build-icu.sh
Labels: vulcan/reviewed

#6319 [[ Bug 20953 ]] Fix specialfolderpath of engine on windows
  docs/notes/bugfix-20953.md
  engine/src/dskw32.cpp
Labels: bug, vulcan/reviewed

#6331 [[ Bug ]] Sign iOS dylibs
  builder/tools_builder.livecodescript
  tools/build-extension-ios.sh
Labels: bug, vulcan/reviewed

#6333 [[ Bug 20269 ]] Error when dispatch cmd has 'with' and no params
  docs/notes/bugfix-20269.md
  engine/src/cmdse.cpp
  engine/src/scriptpt.h
  tests/lcs/parser/parser.livecodescript
Labels: bug, vulcan/reviewed

#6313 [[ WidgetTouch ]] Add support for touch events in widgets
  docs/notes/lcb/feature-widget_touch.md
  engine/src/eventqueue.cpp
  engine/src/widget-events.cpp
  engine/src/widget-events.h
  engine/src/widget-ref.cpp
  engine/src/widget-ref.h
  engine/src/widget-syntax.cpp
  engine/src/widget.h
  engine/src/widget.lcb
  libfoundation/include/foundation.h
Labels: LCB, enhancement, vulcan/reviewed

#6332 [[ Bug ]] Add packaged_extensions to dist_aux_files
  extensions/extensions.gyp
Labels: bug, vulcan/reviewed

#6339 [[ WidgetTouch ]] Move release note to correct folder
  docs/lcb/feature-widget_touch.md
Labels: bug, vulcan/reviewed

#6330 [[ MCLog ]] Use NSLog for MCLog on macOS and iOS
  libfoundation/src/foundation-debug.cpp
  libfoundation/src/system-library-posix.hpp
Labels: enhancement, vulcan/reviewed

#6338 [[ Bug 20991 ]] Use win32 in code library path
  common.gypi
  docs/notes/bugfix-20991.md
  ide-support/revsblibrary.livecodescript
Labels: bug, vulcan/reviewed

#6337 [[ MyPixelScale ]] Implement my pixel scale expression
  docs/lcb/notes/feature-my_pixel_scale.md
  engine/src/widget-syntax.cpp
  engine/src/widget.lcb
Labels: enhancement, vulcan/reviewed

#6295 [[ Bug 20875 ]] Return Typeface object from MCCanvasFontGetHandle on Android
  docs/notes/bugfix-20875.md
  engine/src/font.cpp
  engine/src/java/com/runrev/android/Engine.java
  engine/src/mblandroidfont.cpp
Labels: LCB, bug, enhancement, vulcan/reviewed

#6336 [Bug 20986] Ensure mobileSoundOnChannel returns correct value
  docs/notes/bugfix-20986.md
  engine/src/mbliphonesound.mm
Labels: bug, vulcan/reviewed

#6296 [[ Bug 20883 ]] Allow per-extension standalone settings to be required
  ide-support/revsaveasandroidstandalone.livecodescript
  ide-support/revsaveasiosstandalone.livecodescript
  ide-support/revsaveasstandalone.livecodescript
  ide-support/revsblibrary.livecodescript
Labels: bug, vulcan/reviewed

#6345 [[ Bug ]] Fix variable shadowing in tools builder stack
  builder/tools_builder.livecodescript
Labels: bug, vulcan/reviewed

#6348 [[ Bug ]] Add lib prefix to libraries if they don't have it
  ide-support/revsaveasandroidstandalone.livecodescript
Labels: bug, vulcan/reviewed

#6351 [[ SOSBehavior ]] Do deferred behavior resolution in installer mode startup
  engine/src/mode_installer.cpp
Labels: blocker, bug, vulcan/reviewed

#6347 [[ Bug 20898 ]] Ensure malloc'd pointer is not incremented before free
  docs/notes/bugfix-20898.md
  libexternal/src/osxsupport.cpp
Labels: bug, vulcan/reviewed

#6359 [[ Bug 18669 ]] Fix rotated text rendering on Linux
  docs/notes/bugfix-18669.md
  libgraphics/src/lnxtext.cpp
Labels: LCB, bug, vulcan/reviewed

#6349 [[ Bug 20839 ]] Fix font rendering appearance in HTML5
  docs/notes/bugfix-20839.md
  libgraphics/src/harfbuzztext.cpp
Labels: LCS, bug, vulcan/reviewed

#6297 [[ Bug 20276 ]] Use selected font in android field and button widgets
  extensions/widgets/androidbutton/androidbutton.lcb
  extensions/widgets/androidbutton/notes/20276.md
  extensions/widgets/androidfield/androidfield.lcb
  extensions/widgets/androidfield/notes/20276.md
Labels: bug, vulcan/reviewed

#6307 [[ Emscripten ]] Native HTML5 Button Widget
  docs/notes/feature-emscripten_native_layer.md
  engine/engine-sources.gypi
  engine/src/em-dc.cpp
  engine/src/em-dc.h
  engine/src/em-dc.js
  engine/src/em-event.js
  engine/src/em-javascript.cpp
  engine/src/em-javascript.h
  engine/src/em-liburl.js
  engine/src/em-native-layer.cpp
  engine/src/em-native-layer.h
  engine/src/em-system.cpp
  engine/src/em-system.js
  engine/src/em-util.js
  engine/src/emscripten.lcb
  engine/src/graphics_util.h
  engine/src/jsobject.cpp
  engine/src/jsobject.h
  engine/src/module-emscripten.cpp
  extensions/extensions.gyp
  extensions/widgets/html5button/html5button.lcb
  extensions/widgets/html5button/notes/feature-emscripten_native_button.md
  libscript/src/script-builder.cpp
Labels: LCB, LCS, enhancement, vulcan/reviewed

#6358 [[Bug 21003]] mobileGetContactData Dictionary entry has been truncated
  docs/dictionary/function/mobileGetContactData.lcdoc
  docs/notes/bugfix-21003.md
Labels: vulcan/reviewed

#6342 Merge develop 8.1 20.02.18
  docs/dictionary/property/clipboardData.lcdoc
  docs/dictionary/property/fullClipboardData.lcdoc
  docs/dictionary/property/rawClipboardData.lcdoc
  docs/dictionary/property/scriptOnly.lcdoc
  docs/glossary/s/script-only-stack.lcdoc
  docs/glossary/s/stack-file.lcdoc
  docs/glossary/s/stack-version.lcdoc
  docs/notes/bugfix-19206.md
  docs/notes/bugfix-19580.md
  docs/notes/bugfix-19652.md
  docs/notes/bugfix-20269.md
  docs/notes/bugfix-20293.md
  docs/notes/bugfix-20811.md
  docs/notes/bugfix-20946.md
  docs/notes/bugfix-20952.md
  docs/notes/feature-script_only_stack_behavior.md
  engine/src/chunk.cpp
  engine/src/clipboard.cpp
  engine/src/cmdse.cpp
  engine/src/dispatch.cpp
  engine/src/dskw32.cpp
  engine/src/exec-interface-field-chunk.cpp
  engine/src/exec-interface-object.cpp
  engine/src/exec.cpp
  engine/src/fieldstyledtext.cpp
  engine/src/mode_standalone.cpp
  engine/src/object.cpp
  engine/src/object.h
  engine/src/scriptpt.h
  engine/src/util.cpp
  engine/src/util.h
  engine/src/w32-ds-player.cpp
  ide-support/revliburl.livecodescript
  ide-support/revsaveasstandalone.livecodescript
  ide-support/revsblibrary.livecodescript
  tests/ide-support/standalonebuilder/_support.livecodescript
  tests/ide-support/standalonebuilder/execution.livecodescript
  tests/ide-support/standalonebuilder/savingstandalone.livecodescript
  tests/ide-support/standalonebuilder/script-only.livecodescript
  tests/ide-support/standalonebuilder/stackfiles.livecodescript
  tests/ide-support/standalonebuilder/test.db
  tests/lcs/core/engine/clipboard.livecodescript
  tests/lcs/core/field/encoding.livecodescript
  tests/lcs/core/field/styledText.livecodescript
  tests/lcs/parser/chunks.parsertest
Labels: vulcan/reviewed

#6355 Updated Mac Build Docs
  docs/development/build-mac.md
Labels: documentation, enhancement, vulcan/reviewed
