Repository livecode/livecode, pull requests merged in 2018-03, with the labels that each got.

#6361 Fixed errors in config script for android
  config.py
Labels: vulcan/reviewed

#6363 [[ Emscripten ]] Replace ES6 code features not supported by js optimizer
  engine/src/em-util.js
Labels: LCS, blocker, bug, vulcan/reviewed

#6360 [[ Bug 20876 ]] Remove -S parameter trailing slash in aapt call
  docs/notes/bugfix-20876.md
  ide-support/revsaveasandroidstandalone.livecodescript
Labels: bug, vulcan/reviewed

#6356 [[ Bug 20928 ]] MultipleHilites is MultipleLines where it should not
  docs/dictionary/property/multipleHilites.lcdoc
  docs/notes/bugfix-20928.md
Labels: bug, vulcan/reviewed

#6353 [[ Bug 20888]] Tree view doesn't allow comma in keys
  docs/notes/bugfix-20888.md
  extensions/widgets/treeview/treeview.lcb
Labels: bug, vulcan/reviewed

#6367 Update multipleHilites.lcdoc
  docs/dictionary/property/multipleHilites.lcdoc
Labels: vulcan/reviewed

#6366 [[ Bug 21027 ]] Fix android shell commands with space
  docs/notes/bugfix-21027.md
  ide-support/revsaveasandroidstandalone.livecodescript
Labels: bug, vulcan/reviewed

#6350 [[ VersionScript ]] Generate version script from stubs
  util/list_stub_symbols.pl
Labels: enhancement, vulcan/reviewed

#6370 [[ Bug 20196 ]] Ensure missing extension produces warning
  docs/notes/bugfix-20196.md
  ide-support/revsaveasemscriptenstandalone.livecodescript
  ide-support/revsblibrary.livecodescript
  tests/ide-support/standalonebuilder/_support.livecodescript
  tests/ide-support/standalonebuilder/inclusion.livecodescript
Labels: bug, vulcan/reviewed

#6335 [[ Bug 20814 ]] Fix print to pdf
  docs/notes/bugfix-20814.md
  engine/src/customprinter.cpp
  engine/src/exec-printing.cpp
  engine/src/lnxpsprinter.cpp
  engine/src/printer.h
  engine/src/util.cpp
  tests/_testlib.livecodescript
  tests/lcs/core/printing/printing.livecodescript
Labels: bug, vulcan/reviewed

#6362 [Bug 21016] Add support for Local Storage to Android browser
  docs/notes/bugfix-21016.md
  engine/src/java/com/runrev/android/libraries/LibBrowser.java
  engine/src/java/com/runrev/android/nativecontrol/BrowserControl.java
Labels: enhancement, vulcan/reviewed

#6368 [[ Bug 20430 ]] Swap LCB exponentiation and unary operator precedence
  builder/release_notes_builder.livecodescript
  docs/lcb/notes/20430.md
  docs/notes-base/breaking_changes.md
  docs/specs/lcb-precedence.md
  tests/lcb/stdlib/math.lcb
  toolchain/lc-compile/src/syntax.g
Labels: bug, vulcan/reviewed

#6309 Bugfix extension build scripts
  extensions/extensions.gyp
  extensions/libraries/canvas/canvas.lcb
  extensions/script-libraries/extension-utils/extension-utils.livecodescript
  extensions/script-libraries/extension-utils/notes/feature-extension_utils.md
  extensions/script-libraries/extension-utils/resources/extension-utils.lc
  extensions/widgets/colorswatch/colorswatch.lcb
  extensions/widgets/gradientrampeditor/gradientrampeditor.lcb
  extensions/widgets/header/header.lcb
  extensions/widgets/iconpicker/iconpicker.lcb
  extensions/widgets/navbar/navbar.lcb
  extensions/widgets/paletteactions/paletteactions.lcb
  extensions/widgets/segmented/segmented.lcb
  extensions/widgets/switchbutton/switchbutton.lcb
  extensions/widgets/tile/tile.lcb
  tests/Makefile
  util/build-extensions.sh
  util/extract-docs.livecodescript
  util/package_extension.livecodescript
Labels: vulcan/reviewed

#5538 [[ Travis ]] Use JDK 1.8 on Travis
  .travis.yml
Labels: vulcan/reviewed

#6344 [[ Bug 19868 ]] Automatically break wait after post
  docs/notes/feature-break_wait.md
  engine/src/module-engine.cpp
  engine/src/module-engine.h
  extensions/widgets/androidbutton/androidbutton.lcb
  extensions/widgets/androidfield/androidfield.lcb
  extensions/widgets/iosbutton/iosbutton.lcb
  extensions/widgets/macbutton/macbutton.lcb
Labels: enhancement, vulcan/reviewed

#5461 Remove -Wno-error=maybe-uninitialized
  config/linux-settings.gypi
  engine/src/bitmapeffect.cpp
  engine/src/block.cpp
  engine/src/buttondraw.cpp
  engine/src/deploy.cpp
  engine/src/deploy_linux.cpp
  engine/src/field.cpp
  engine/src/fields.cpp
  engine/src/graphicscontext.cpp
  engine/src/hc.cpp
  engine/src/ibmp.cpp
  engine/src/idraw.cpp
  engine/src/igif.cpp
  engine/src/image.cpp
  engine/src/imagelist.cpp
  engine/src/opensslsocket.cpp
  engine/src/scriptpt.cpp
  engine/src/variable.cpp
  libfoundation/src/foundation-locale.cpp
Labels: vulcan/reviewed

#6354 [[Bug 21010]] Use PAC file found via WPAD protocol to resolve proxy server settings for url requests
  docs/notes/bugfix-21010.md
  ide-support/revliburl.livecodescript
Labels: vulcan/reviewed

#6372 [[ Bug 20792 ]] Send touch messages when scroller disabled
  docs/dictionary/command/mobileControlSet.lcdoc
  docs/notes/bugfix-20792.md
  engine/src/java/com/runrev/android/nativecontrol/ScrollerControl.java
Labels: bug, vulcan/reviewed

#6369 [[ Bug 20992 ]] Use local frame for interface proxy creation
  docs/notes/bugfix-20992.md
  libfoundation/src/foundation-java-private.cpp
Labels: bug, vulcan/reviewed

#6340 [[ Bug 20482 ]] Use replacement chars on a cluster rather than glyph basis
  docs/notes/bugfix-20482.md
  libgraphics/src/harfbuzztext.cpp
Labels: bug, vulcan/reviewed

#6377 [[ Bug 20898 ]] Ensure malloc'd pointer is not incremented before free
  docs/notes/bugfix-20898.md
  libexternal/src/osxsupport.cpp
Labels: bug, vulcan/reviewed

#6343 [[ Bug 20971 ]] Unary function parsing does not check for EOL
  docs/notes/bugfix-20971.md
  engine/src/funcs.h
  tests/lcs/parser/unary-function.parsertest
Labels: bug, vulcan/reviewed

#6378 Fixed error flagged after removing -Wno-error=maybe-uninitialized
  libfoundation/src/foundation-pickle.cpp
Labels: vulcan/reviewed

#6315 [[ Bug 20576 ]] Add Cancel button to OAuth2 dialog
  extensions/script-libraries/oauth2/notes/20576.md
  extensions/script-libraries/oauth2/oauth2.livecodescript
Labels: bug, vulcan/reviewed

#6376 [[ mergExt ]] update pointer
  builder/builder_utilities.livecodescript
Labels: bug, enhancement, vulcan/reviewed

#6379 [[ Bug 20790 ]] Add breaking change note about S/B messages
  docs/notes-base/breaking_changes.md
Labels: documentation, vulcan/reviewed

#6314 [[ Bug 19427 ]] Fix browser process not closing
  extensions/widgets/browser/notes/19427.md
  libbrowser/src/libbrowser_cef.cpp
Labels: bug, vulcan/reviewed

#6380 Fix new errors flagged after removing -Wno-error=maybe-uninitialized
  libfoundation/src/foundation-string-native.cpp.h
  libfoundation/src/foundation-string.cpp
Labels: vulcan/reviewed

#6382 Reinstate -Wno-error=maybe-uninitialized
  config/linux-settings.gypi
Labels: vulcan/reviewed

#6383 [[ Bug 20790 ]] Tweak auto-updater text so it looks better
  builder/release_notes_builder.livecodescript
  docs/notes/bugfix-20790.md
Labels: bug, vulcan/reviewed

#6371 [[ AndroidUtils ]] Add android utility library
  Installer/package.txt
  extensions/extensions.gyp
  extensions/libraries/androidbgaudio/androidbgaudio.lcb
  extensions/modules/android-utils/android-utils.lcb
  extensions/modules/android-utils/notes/feature-android_utils.md
  extensions/widgets/androidbutton/androidbutton.lcb
  extensions/widgets/androidfield/androidfield.lcb
  extensions/widgets/androidfield/tests/properties.livecodescript
Labels: vulcan/reviewed

#6387 [[ ExtensionUtils ]] Add extension-utils to installer
  Installer/package.txt
Labels: bug, vulcan/reviewed

#6386 Html5 button tweaks
  Installer/package.txt
  extensions/widgets/html5button/html5button.lcb
Labels: vulcan/reviewed

#6388 Merge develop 8.1 07.03.2018
  builder/builder_utilities.livecodescript
  docs/notes/bugfix-20986.md
  docs/notes/bugfix-21016.md
  engine/src/java/com/runrev/android/libraries/LibBrowser.java
  engine/src/java/com/runrev/android/nativecontrol/BrowserControl.java
  engine/src/mbliphonesound.mm
  engine/src/mode_installer.cpp
Labels: vulcan/reviewed

#6393 Fixed indentation
  Installer/package.txt
Labels: blocker, vulcan/reviewed

#6391 [[ Bug 13935 ]] Ensure modal dialogs have parent on Linux
  docs/notes/bugfix-13935.md
  engine/src/lnxstack.cpp
Labels: bug, vulcan/reviewed

#6392 [[ Bug 20565 ]] Fix linux fullscreen window manager issues
  docs/notes/bugfix-20565.md
  engine/src/lnxstack.cpp
Labels: bug, vulcan/reviewed

#6398 Fix crash when saving a stack that has legacy widget
  engine/src/widget.cpp
Labels: blocker, vulcan/reviewed

#6397 [[ Bug ]] EngineRunloopBreakWait is no-op if notify api is not present
  engine/src/module-engine.cpp
Labels: blocker, bug, vulcan/reviewed

#6399 [[ Bug 20971 ]] Ensure error is as was previously
  engine/src/funcs.h
  tests/lcs/parser/unary-function.parsertest
Labels: vulcan/reviewed

#6396 [[ Bug ]] Support files passed into compile should be full paths
  extensions/script-libraries/extension-utils/extension-utils.livecodescript
Labels: bug, vulcan/reviewed

#6400 [[ Bug ]] Resolve behaviors for auxiliary stacks
  engine/src/dispatch.cpp
  engine/src/dispatch.h
  engine/src/mode_installer.cpp
  engine/src/mode_standalone.cpp
Labels: blocker, bug, vulcan/reviewed

#6381 [[ Bug 20996 ]] Fix Segmented Control perimeter when it has one segment
  docs/notes/bugfix-20996.md
  extensions/widgets/segmented/segmented.lcb
Labels: bug, vulcan/reviewed

#6394 [[ Bug 21026 ]] Fix handling of binary URL data in HTML5
  docs/notes/bugfix-21026.md
  engine/src/em-liburl.js
  engine/src/em-system.cpp
  engine/src/em-util.js
  ide-support/revhtml5urllibrary.livecodescript
Labels: LCS, blocker, bug, vulcan/reviewed

#6401 [[ Bug 21036 ]] Add containing div in template html to center canvas on page
  engine/rsrc/emscripten-html-template.html
Labels: LCS, bug, vulcan/reviewed

#6406 [[ Bug 19731 ]] Remove documentation for no longer supported inks
  docs/dictionary/keyword/adMin.lcdoc
  docs/dictionary/keyword/addMax.lcdoc
  docs/dictionary/keyword/addOver.lcdoc
  docs/dictionary/keyword/addPin.lcdoc
  docs/dictionary/keyword/blend.lcdoc
  docs/dictionary/keyword/clear.lcdoc
  docs/dictionary/keyword/noOp.lcdoc
  docs/dictionary/keyword/notSrcAnd.lcdoc
  docs/dictionary/keyword/notSrcAndReverse.lcdoc
  docs/dictionary/keyword/notSrcBic.lcdoc
  docs/dictionary/keyword/notSrcCopy.lcdoc
  docs/dictionary/keyword/notSrcOr.lcdoc
  docs/dictionary/keyword/notSrcOrReverse.lcdoc
  docs/dictionary/keyword/notSrcXOr.lcdoc
  docs/dictionary/keyword/reverse.lcdoc
  docs/dictionary/keyword/set.lcdoc
  docs/dictionary/keyword/srcAnd.lcdoc
  docs/dictionary/keyword/srcAndReverse.lcdoc
  docs/dictionary/keyword/srcBic.lcdoc
  docs/dictionary/keyword/srcCopy.lcdoc
  docs/dictionary/keyword/srcOr.lcdoc
  docs/dictionary/keyword/srcOrReverse.lcdoc
  docs/dictionary/keyword/srcXOr.lcdoc
  docs/dictionary/keyword/subOver.lcdoc
  docs/dictionary/keyword/subPin.lcdoc
  docs/dictionary/keyword/transparent.lcdoc
  docs/dictionary/property/ink.lcdoc
  docs/glossary/t/transfer-mode.lcdoc
  docs/notes/bugfix-19731.md
Labels: cleanup, vulcan/reviewed

#6405 [[ Bug 19536 ]] Fix menu not closing when clicking on other side
  docs/notes/bugfix-19536.md
  engine/src/button.cpp
Labels: bug, vulcan/reviewed

#6402 [[ Bug 21050 ]] Add html5 button icon
  extensions/widgets/html5button/html5button.lcb
Labels: vulcan/reviewed

#6403 [[ Bug ]] Remove library mapping for static libs
  ide-support/revsaveasiosstandalone.livecodescript
Labels: bug, vulcan/reviewed

#6384 [[ Bug 20200 ]] Navigate to target=_blank links in widget
  extensions/widgets/browser/notes/20200.md
  libbrowser/src/libbrowser_cef.cpp
  libbrowser/src/libbrowser_osx_webview.mm
Labels: bug, vulcan/reviewed

#6408 Merge develop 8.1 12.03.18
  docs/notes/bugfix-13935.md
  docs/notes/bugfix-20565.md
  engine/src/lnxstack.cpp
Labels: clean merge, vulcan/reviewed

#6373 [[ Bug 20272 ]] Fix crash binding variables for ODBC db
  docs/notes/bugfix-20272.md
  revdb/src/odbc_connection.cpp
  revdb/src/revdb.cpp
Labels: bug, vulcan/reviewed

#6409 [[ Bug ]] Ensure emscripten build uses correct module filename
  ide-support/revsaveasemscriptenstandalone.livecodescript
Labels: blocker, bug, vulcan/reviewed

#6395 [[ Bug 20976 ]] Set the hidden of multiple lines when last line is empty
  docs/notes/bugfix-20976.md
  engine/src/exec-interface-field-chunk.cpp
  tests/lcs/core/field/line-chunk-hidden.livecodescript
  tests/lcs/core/field/styledText.livecodescript
Labels: bug, vulcan/reviewed

#6374 [Bug 13180] Allow GPS access from Android Browser Control
  docs/notes/bugfix-13180.md
  engine/src/java/com/runrev/android/libraries/LibBrowser.java
  engine/src/java/com/runrev/android/nativecontrol/BrowserControl.java
Labels: enhancement, vulcan/reviewed

#6412 [[ Bug 21008 ]] Fix crash on execution error in ask dialog
  docs/notes/bugfix-21008.md
  engine/src/exec-dialog.cpp
Labels: bug, vulcan/reviewed

#6410 Set the executable bit of the downloaded installer on Linux
  builder/installer/installeruiupdatedownloadcardbehavior.livecodescript
Labels: vulcan/reviewed

#6420 [[ WidgetModule ]] MCWidgetGetStackNativeViewOfWidget out param can be nil
  engine/src/widget.lcb
Labels: bug, vulcan/reviewed

#6419 [[ Bug ]] EvalJavaScriptWithArguments returns optional any
  engine/src/emscripten.lcb
Labels: bug, vulcan/reviewed

#6417 [[ EmscriptenModules ]] Ensure module file is found
  engine/rsrc/emscripten-startup-template.livecodescript
  ide-support/revsaveasemscriptenstandalone.livecodescript
Labels: bug, vulcan/reviewed

#6421 [[ Bug 19536 ]] Ensure parent is submenu
  engine/src/button.cpp
Labels: bug, vulcan/reviewed

#6416 [[ Bug 20677 ]] Fix crash calling mobilePickPhoto
  docs/notes/bugfix-20677.md
  engine/src/mblhandlers.cpp
Labels: bug, vulcan/reviewed

#6423 [[ Bug 21067 ]] Fix IDE error when recursively searching for extensions
  extensions/script-libraries/extension-utils/extension-utils.livecodescript
  extensions/script-libraries/extension-utils/notes/21067.md
Labels: bug, vulcan/reviewed

#6426 [[ 9.0.0 RC2 ]] Update version
  version
Labels: vulcan/reviewed

#6428 [[ Bug 21074 ]] revDocsFormatLibraryArrayAsJSON omits dictionary data
  docs/notes/bugfix-21074.md
  ide-support/revdocsparser.livecodescript
Labels: vulcan/reviewed

#6430 [[ ExtensionUtils ]] Move code to validate package to extension utils
  extensions/script-libraries/extension-utils/extension-utils.livecodescript
  extensions/script-libraries/extension-utils/tests/package.livecodescript
  extensions/script-libraries/extension-utils/tests/package/test.lce
Labels: bug, vulcan/reviewed

#6418 [[ Emscripten ]] Implement GetNativeWindowHandle for emscripten
  engine/src/em-dc.cpp
  engine/src/em-dc.h
Labels: vulcan/reviewed

#6435 [9.0.1 RC-1] Updated version
  version
Labels: vulcan/reviewed

#6429 [[ Bug 21078 ]] Ensure LCB android permission metadata is applied
  docs/notes/bugfix-21078.md
  ide-support/revsaveasstandalone.livecodescript
  ide-support/revsblibrary.livecodescript
  tests/ide-support/standalonebuilder/_support.livecodescript
  tests/ide-support/standalonebuilder/androidpermissions.livecodescript
  tests/lcs/extensions/libraries/android-permissions/androidpermissionstest.lcb
Labels: bug, vulcan/reviewed

#6436 [9.1.0 DP-1] Updated version
  version
Labels: vulcan/reviewed

#6433 [[ Bug 21069 ]] Use html5 button name for label if empty
  extensions/widgets/html5button/html5button.lcb
  extensions/widgets/html5button/notes/21069.md
Labels: vulcan/reviewed

#6434 [[ Bug 21096 ]] Include extension guide folders in packages
  extensions/script-libraries/extension-utils/extension-utils.livecodescript
  extensions/script-libraries/extension-utils/notes/21096.md
Labels: bug, vulcan/reviewed

#6439 [[ ExtensionUtils ]] Enable fetching of requirements from lce package
  extensions/script-libraries/extension-utils/extension-utils.livecodescript
Labels: vulcan/reviewed

#6431 [[ Bugfix 21066 ]] Modify libUrlSetDriver to ensure behavior is not set while behavior is running
  docs/notes/bugfix-21066.md
  ide-support/revliburl.livecodescript
Labels: vulcan/reviewed

#6385 [[ Cleanup ]] Fix maybe-uninitialized warnings in release build
  engine/src/exec-engine.cpp
  engine/src/exec-extension.cpp
  engine/src/exec-files.cpp
  engine/src/exec-filters.cpp
  engine/src/exec-interface-field-chunk.cpp
  engine/src/exec-interface2.cpp
  engine/src/exec-strings.cpp
  engine/src/exec.cpp
  engine/src/itransform.cpp
  engine/src/lnxdc.cpp
  engine/src/lnxdcs.cpp
  engine/src/lnxelevate.cpp
  engine/src/lnxflst.cpp
  engine/src/module-canvas.cpp
  engine/src/object.cpp
  engine/src/objectpropsets.cpp
  engine/src/paragraf.cpp
  engine/src/rtf.cpp
  engine/src/widget-popup.cpp
  libfoundation/src/foundation-string.cpp
  libfoundation/src/foundation-typeinfo.cpp
  libfoundation/src/foundation-unicode.cpp
  libfoundation/src/system-stream.cpp
  libgraphics/src/context.cpp
Labels: cleanup, vulcan/reviewed

#6414 [[ Bug 20961 ]] Reset the menu object when swapping menus
  docs/notes/bugfix-20961.md
  engine/src/button.cpp
Labels: bug, vulcan/reviewed

#6411 [[ Bug 21049 ]] Add errors for fontLanguage
  docs/notes/bugfix-21049.md
  engine/src/executionerrors.h
  engine/src/funcs.h
  engine/src/parseerrors.h
  engine/src/scriptpt.cpp
  tests/lcs/parser/unary-function.parsertest
Labels: enhancement, vulcan/reviewed

#6425 [Bug 21063] Ensure the standalone can find the postgresql external
  docs/notes/bugfix-21063.md
  ide-support/revsaveasstandalone.livecodescript
Labels: bug, vulcan/reviewed

#6438 [[ Bug 21105 ]] Ensure interface file is found
  extensions/script-libraries/extension-utils/extension-utils.livecodescript
  extensions/script-libraries/extension-utils/notes/21105.md
Labels: bug, vulcan/reviewed

#6452 Merge develop 8.1 26.03.18
  builder/builder_utilities.livecodescript
  docs/notes/bugfix-13180.md
  docs/notes/bugfix-20961.md
  engine/src/button.cpp
  engine/src/java/com/runrev/android/libraries/LibBrowser.java
  engine/src/java/com/runrev/android/nativecontrol/BrowserControl.java
  prebuilt/fetch-libraries.sh
  tests/lcs/ext/ext-urls.livecodescript
Labels: vulcan/reviewed

#6444 [[ Bug 21109 ]] Limit clipboard clear setting fullClipboardData["text"]
  docs/dictionary/property/fullClipboardData.lcdoc
  docs/notes/bugfix-21109.md
  engine/src/clipboard.cpp
  tests/lcs/core/engine/clipboard.livecodescript
Labels: blocker, bug, vulcan/reviewed

#6453 [[ Emscripten ]] Update HTML5 deployment guide
  docs/guides/HTML5 Deployment.md
Labels: documentation, vulcan/reviewed

#6440 [[ Bug 21085 ]] Fix handling of unknown url scheme
  extensions/widgets/browser/browser.lcb
  extensions/widgets/browser/notes/21085.md
  libbrowser/src/libbrowser_cef.cpp
Labels: blocker, bug, vulcan/reviewed

#6441 [[ Bug 21101 ]] Fix openField and exitField not sent
  extensions/widgets/androidfield/androidfield.lcb
Labels: blocker, bug, vulcan/reviewed

#6450 [[ Bug 21099 ]] Fix crash closing browser
  extensions/widgets/browser/notes/21099.md
  libbrowser/src/libbrowser_cef.cpp
  libbrowser/src/libbrowser_cef.h
  libbrowser/src/libbrowser_cef_lnx.cpp
  libbrowser/src/libbrowser_cef_win.cpp
Labels: blocker, bug, vulcan/reviewed

#6455 [Bug 21124] Ensure folders are copied in html5 standalone
  docs/notes/bugfix-21124.md
  ide-support/revsaveasemscriptenstandalone.livecodescript
Labels: bug, vulcan/reviewed

#6454 [[ Bug 14554 ]] Add user guides for widgets
  extensions/widgets/browser/docs/guide/guide.md
  extensions/widgets/browser/docs/guide/images/browser.png
  extensions/widgets/clock/docs/guide/guide.md
  extensions/widgets/clock/docs/guide/images/clock.png
  extensions/widgets/clock/docs/guide/images/clocks.png
  extensions/widgets/graph/docs/guide/guide.md
  extensions/widgets/graph/docs/guide/images/data-hilited-coordinates.png
  extensions/widgets/graph/docs/guide/images/data-no-lines.png
  extensions/widgets/graph/docs/guide/images/data-no-markers.png
  extensions/widgets/graph/docs/guide/images/data.png
  extensions/widgets/graph/docs/guide/images/graph.png
  extensions/widgets/graph/docs/guide/images/pi.png
  extensions/widgets/header/docs/guide/guide.md
  extensions/widgets/header/docs/guide/images/android-messages.png
  extensions/widgets/header/docs/guide/images/android-notes.png
  extensions/widgets/header/docs/guide/images/clock.png
  extensions/widgets/header/docs/guide/images/header-change-1.png
  extensions/widgets/header/docs/guide/images/header-change-2.png
  extensions/widgets/header/docs/guide/images/header.png
  extensions/widgets/header/docs/guide/images/icon-picker.png
  extensions/widgets/header/docs/guide/images/ios-messages.png
  extensions/widgets/header/docs/guide/images/ios-notes.png
  extensions/widgets/header/docs/guide/images/mac-header.png
  extensions/widgets/header/docs/guide/images/pi-1.png
  extensions/widgets/header/docs/guide/images/pi-2.png
  extensions/widgets/navbar/docs/guide/guide.md
  extensions/widgets/navbar/docs/guide/images/bmi-app.png
  extensions/widgets/navbar/docs/guide/images/icon-picker.png
  extensions/widgets/navbar/docs/guide/images/label.png
  extensions/widgets/navbar/docs/guide/images/multiple-choice-1.png
  extensions/widgets/navbar/docs/guide/images/multiple-choice-2.png
  extensions/widgets/navbar/docs/guide/images/multiple-choice.png
  extensions/widgets/navbar/docs/guide/images/navbar.png
  extensions/widgets/navbar/docs/guide/images/pi-editor.png
  extensions/widgets/navbar/docs/guide/images/pi.png
  extensions/widgets/segmented/docs/guide/guide.md
  extensions/widgets/segmented/docs/guide/images/pi-text.png
  extensions/widgets/segmented/docs/guide/images/segmented.png
  extensions/widgets/segmented/docs/guide/images/star-rating.png
  extensions/widgets/segmented/docs/guide/images/text-align.png
  extensions/widgets/spinner/docs/guide/guide.md
  extensions/widgets/spinner/docs/guide/images/spinner.gif
  extensions/widgets/svgpath/docs/guide/guide.md
  extensions/widgets/svgpath/docs/guide/images/aspect.png
  extensions/widgets/svgpath/docs/guide/images/fill-rule.png
  extensions/widgets/svgpath/docs/guide/images/fireext.png
  extensions/widgets/svgpath/docs/guide/images/hilite.png
  extensions/widgets/svgpath/docs/guide/images/rotated.png
  extensions/widgets/svgpath/docs/guide/images/svgpath.png
  extensions/widgets/switchbutton/docs/guide/guide.md
  extensions/widgets/switchbutton/docs/guide/images/switchbutton-ios.png
  extensions/widgets/switchbutton/docs/guide/images/switchbutton.png
  extensions/widgets/treeview/docs/guide/guide.md
  extensions/widgets/treeview/docs/guide/images/action-inspect.png
  extensions/widgets/treeview/docs/guide/images/edit-add-new-subelement.png
  extensions/widgets/treeview/docs/guide/images/edit-add-new.png
  extensions/widgets/treeview/docs/guide/images/edit-delete-confirm.png
  extensions/widgets/treeview/docs/guide/images/edit-delete.png
  extensions/widgets/treeview/docs/guide/images/treeview.png
Labels: documentation, vulcan/reviewed

#6443 [[ CheatSheets ]] Add LCB cheat sheet and generate new combinations
  docs/cheat-sheet/cheat-sheet.livecodescript
  docs/cheat-sheet/cheat-sheet.yml
Labels: documentation, vulcan/reviewed

#6459 Update version
  version
Labels: vulcan/reviewed

#6460 Merge release 9.0.0 28.03.2018
  docs/dictionary/property/fullClipboardData.lcdoc
  docs/guides/HTML5 Deployment.md
  docs/notes/bugfix-21109.md
  docs/notes/bugfix-21124.md
  engine/src/clipboard.cpp
  extensions/widgets/androidfield/androidfield.lcb
  extensions/widgets/browser/browser.lcb
  extensions/widgets/browser/notes/21085.md
  extensions/widgets/browser/notes/21099.md
  ide-support/revsaveasemscriptenstandalone.livecodescript
  libbrowser/src/libbrowser_cef.cpp
  libbrowser/src/libbrowser_cef.h
  libbrowser/src/libbrowser_cef_lnx.cpp
  libbrowser/src/libbrowser_cef_win.cpp
  tests/lcs/core/engine/clipboard.livecodescript
Labels: vulcan/reviewed

#6445 [[ Bug 21107 ]] Further support for blank target links
  extensions/widgets/browser/notes/21107.md
  libbrowser/src/libbrowser_cef.cpp
  libbrowser/src/libbrowser_osx_webview.mm
Labels: bug, vulcan/reviewed

#6457 [[ Bug 21121 ]] Use temp directory for CEF cache
  engine/src/widget-ref.cpp
  engine/src/widget-ref.h
  extensions/widgets/browser/browser.lcb
  extensions/widgets/browser/notes/21121.md
  libbrowser/src/libbrowser_cef.cpp
Labels: bug, vulcan/reviewed
