Repository livecode/livecode, pull requests merged in 2018-10, with the labels that each got.

#6665 Added support for building with Xcode10 / iOS 12 SDK
  Installer/package.txt
  Makefile
  config.py
  docs/notes-base/platforms.md
  ide-support/revdeploylibraryios.livecodescript
  prebuilt/fetch-libraries.sh
  prebuilt/scripts/ios.inc
  tools/setup_xcode_sdks.py
Labels: vulcan/reviewed

#6697 Ensure right-click on run mode does not unhilite a radio button
  docs/notes/bugfix-9711.md
  engine/src/group.cpp
Labels: bug, vulcan/reviewed

#6706 Fixed error when building for iOS device with min_ios_version = 12
  engine/src/deploy_macosx.cpp
Labels: blocker, bug, vulcan/reviewed

#6700 [[Bug 21602]] Remove duplicate handler
  extensions/script-libraries/drawing/drawing.livecodescript
  extensions/script-libraries/drawing/notes/21602.md
Labels: vulcan/reviewed

#6709 [[ Bug ]] Ensure result mode is not clobbered by debugger messages
  engine/src/debug.cpp
  tests/lcs/core/engine/_trace.livecodescript
  tests/lcs/core/engine/return.livecodescript
Labels: bug, vulcan/reviewed

#6711 [[ tsNet ]] Update pointer
  builder/builder_utilities.livecodescript
Labels: vulcan/reviewed

#6707 [[ Bug 21623 ]] Handle stack scroll in open in window
  docs/notes/bugfix-21623.md
  engine/src/stack2.cpp
Labels: blocker, bug, vulcan/reviewed

#6708 [Dictionary] 'of' to 'pageHeights'
  docs/dictionary/command/open-driver.lcdoc
  docs/dictionary/command/open-file.lcdoc
  docs/dictionary/command/open-printing-to-pdf.lcdoc
  docs/dictionary/command/open-printing.lcdoc
  docs/dictionary/command/open-process.lcdoc
  docs/dictionary/command/option.lcdoc
  docs/dictionary/function/openFiles.lcdoc
  docs/dictionary/keyword/of.lcdoc
  docs/dictionary/message/openControl.lcdoc
  docs/dictionary/message/openField.lcdoc
  docs/dictionary/message/optionKeyDown.lcdoc
  docs/dictionary/message/orientationChanged.lcdoc
  docs/dictionary/property/opaque.lcdoc
  docs/dictionary/property/outerglow.lcdoc
  docs/dictionary/property/pageHeights.lcdoc
Labels: vulcan/reviewed

#6714 Androidfixes
  config/android-settings.gypi
  engine/src/java/com/runrev/android/Engine.java
  engine/src/mblandroiddc.cpp
Labels: bug, vulcan/reviewed

#6716 [Dictionary] pointerFocus to processID
  docs/dictionary/command/post.lcdoc
  docs/dictionary/function/processID.lcdoc
  docs/dictionary/keyword/printercolon.lcdoc
  docs/dictionary/message/preOpenControl.lcdoc
  docs/dictionary/property/pointerFocus.lcdoc
  docs/dictionary/property/printColors.lcdoc
  docs/dictionary/property/printCopies.lcdoc
  docs/dictionary/property/printDuplex.lcdoc
  docs/dictionary/property/printFontTable.lcdoc
  docs/dictionary/property/printPaperOrientation.lcdoc
  docs/dictionary/property/printPaperScale.lcdoc
  docs/dictionary/property/printPaperSize.lcdoc
  docs/dictionary/property/printRanges.lcdoc
  docs/dictionary/property/printTextSize.lcdoc
  docs/dictionary/property/printTextStyle.lcdoc
  docs/dictionary/property/printTitle.lcdoc
  docs/dictionary/property/printerName.lcdoc
  docs/dictionary/property/printerOutput.lcdoc
  docs/dictionary/property/printerSettings.lcdoc
Labels: vulcan/reviewed

#6696 [Bugfix-11792] Add note in docs about copying objects on mobile
  docs/dictionary/command/copy.lcdoc
  docs/notes/bugfix-11792.md
Labels: vulcan/reviewed

#6713 [[ Bug 20640 ]] [Docs] Update orientation docs for iPhone X
  docs/dictionary/command/mobileSetAllowedOrientations.lcdoc
  docs/dictionary/function/mobileAllowedOrientations.lcdoc
  docs/dictionary/function/mobileDeviceOrientation.lcdoc
  docs/dictionary/function/mobileOrientation.lcdoc
  docs/notes/bugfix-20640.md
Labels: bug, vulcan/reviewed

#6720 [[Bug 20943]][Docs] Explicit RegEx escape examples
  docs/dictionary/function/replaceText.lcdoc
  docs/notes/bugfix-20943.md
Labels: need-rebase, vulcan/reviewed

#6719 [[Bug 19597]][docs] Open Socket summary edit
  docs/dictionary/command/open-socket.lcdoc
  docs/notes/bugfix-19597.md
Labels: need-rebase, vulcan/reviewed

#6686 [21582] Fix crash when saving a stack that has a colorswatch widget
  docs/notes/bugfix-21582.md
  engine/src/widget.cpp
Labels: bug, vulcan/reviewed

#6721 [[ Bug 21623 ]] Fix height calcuation in takewindow
  engine/src/osxstack.cpp
  engine/src/stack.h
  engine/src/stack2.cpp
  engine/src/stack3.cpp
Labels: bug, vulcan/reviewed

#6724 Fix link to LiveCode Builder coding style file
  CONTRIBUTING.md
Labels: vulcan/reviewed

#6729 [[ Bug 20480 ]] shell command should separate return value and the result
  docs/dictionary/function/shell.lcdoc
Labels: vulcan/reviewed

#6725 [[ Community Docs ]] Fix link to LiveCode Documentation Format Reference
  docs/contributing_to_docs.md
Labels: vulcan/reviewed

#6715 [Dictionary] palindromeFrames to pointer
  docs/dictionary/constant/pi.lcdoc
  docs/dictionary/control_st/pass.lcdoc
  docs/dictionary/function/param.lcdoc
  docs/dictionary/function/params.lcdoc
  docs/dictionary/keyword/pointer.lcdoc
  docs/dictionary/message/playStopped.lcdoc
  docs/dictionary/object/player.lcdoc
  docs/dictionary/property/palindromeFrames.lcdoc
  docs/dictionary/property/password.lcdoc
  docs/dictionary/property/pixels.lcdoc
  docs/glossary/p/PICT.lcdoc
  docs/glossary/p/pass-by-reference.lcdoc
  docs/glossary/p/pass.lcdoc
Labels: vulcan/reviewed

#6723 Bugfix 19597 backport
  docs/dictionary/command/open-socket.lcdoc
  docs/notes/bugfix-19597.md
Labels: vulcan/reviewed

#6727 Document develop-9.0 as recommended docs fix target branch
  docs/contributing_to_docs.md
  docs/images/branch-dropdown.png
  docs/images/develop-branch.png
Labels: vulcan/reviewed

#6722 Bugfix 20943 backport
  docs/dictionary/function/replaceText.lcdoc
  docs/notes/bugfix-20943.md
Labels: vulcan/reviewed

#6731 [[Docs]] ContributeToDocs update link references
  docs/contributing_to_docs.md
Labels: vulcan/reviewed

#6718 [[ Bug 21312 ]] [Docs] Repair Unlock Screen doc
  docs/dictionary/command/unlock-screen.lcdoc
  docs/dictionary/command/visual-effect.lcdoc
  docs/glossary/q/QuickTime.lcdoc
  docs/notes/bugfix-21312.md
Labels: need-rebase, vulcan/reviewed

#6730 [[ Bug 21624 ]] Fix blendlevel + disabled button issue for Motif
  docs/notes/bugfix-21624.md
  engine/src/buttondraw.cpp
Labels: blocker, bug, vulcan/reviewed

#6732 [[Bugfix-20529]] MouseEnter MouseLeave infinite loop trap - docs update
  docs/dictionary/message/mouseEnter.lcdoc
  docs/dictionary/message/mouseLeave.lcdoc
  docs/notes/bugfix-20529
Labels: vulcan/reviewed

#6733 Backport bugfix 21312
  docs/dictionary/command/unlock-screen.lcdoc
  docs/dictionary/command/visual-effect.lcdoc
  docs/glossary/q/QuickTime.lcdoc
  docs/notes/bugfix-21312.md
Labels: vulcan/reviewed

#6717 Mention that MacOS Mojave is supported
  docs/notes-base/platforms.md
Labels: vulcan/reviewed

#6743 Create bugfix-20283.md
  docs/notes/bugfix-20283.md
Labels: vulcan/reviewed

#6737 [[ Bug 20283 ]] Replace dead openssl.org links
  docs/dictionary/command/decrypt-using-rsa.lcdoc
Labels: vulcan/reviewed

#6744 [[ Bug 21608 ]] Remove second break wait from invoke handler block
  docs/notes/bugfix-21608.md
  libbrowser/src/libbrowser_uiwebview.mm
Labels: blocker, bug, vulcan/reviewed

#6736 [[ Bug 20283 ]] Replace dead openssl.org links
  docs/dictionary/command/encrypt-using-rsa.lcdoc
Labels: vulcan/reviewed

#6745 [[ Bug 21629 ]] Fix display update on iOS 12
  docs/notes/bugfix-21629.md
  engine/src/mbliphonegfx.mm
Labels: blocker, bug, vulcan/reviewed

#6746 [Dictionary] proportionalThumbs to read from process
  docs/dictionary/command/pulldown.lcdoc
  docs/dictionary/command/put.lcdoc
  docs/dictionary/command/quit.lcdoc
  docs/dictionary/command/read-from-process.lcdoc
  docs/dictionary/function/propertyNames.lcdoc
  docs/dictionary/function/random.lcdoc
  docs/dictionary/message/rawKeyDown.lcdoc
  docs/dictionary/message/rawKeyUp.lcdoc
  docs/dictionary/property/proportionalThumbs.lcdoc
  docs/dictionary/property/radioBehavior.lcdoc
  docs/dictionary/property/rawDragData.lcdoc
Labels: vulcan/reviewed

#6741 [[ Bug 21644 ]] Setting the beepsound to a .mp3 file is not supported on iPhone
  docs/dictionary/property/beepSound.lcdoc
  docs/notes/bugfix-21644.md
Labels: vulcan/reviewed

#6646 [[ iOS Frameworks ]] Copy frameworks to the Frameworks subdirectory
  ide-support/revsaveasiosstandalone.livecodescript
Labels: bug, vulcan/reviewed

#6751 Fix outdated link for Microsoft Visual Studio Build Tools 2015
  docs/development/build-win.md
Labels: vulcan/reviewed

#6750 [[ Bug 21474 ]] Reset mouse stack after drag and drop
  docs/notes/bugfix-21474.md
  engine/src/dispatch.cpp
Labels: bug, vulcan/reviewed

#6756 [[ Bug fix 9030 ]] Clarify how pageRect works
  docs/dictionary/command/print.lcdoc
  docs/notes/bugfix-9030.md
Labels: vulcan/reviewed

#6755 [[ Bug 20722 ]] Update launch URL command note for Android
  docs/dictionary/command/launch-url.lcdoc
  docs/notes/bugfix-20722.md
Labels: vulcan/reviewed

#6752 Update visual studio 2015 link
  docs/development/build-win.md
Labels: vulcan/reviewed

#6705 [[ Bug ]] Send keyboard messages after effective rect changes
  engine/src/java/com/runrev/android/Engine.java
  engine/src/java/com/runrev/android/LiveCodeActivity.java
Labels: bug, vulcan/reviewed

#6754 [[ Bug 21230 ]] Fixed bug causing incorrect alias creation on Windows@
  docs/notes/bugfix-21230.md
  engine/src/sysspec.cpp
  tests/lcs/core/files/folders.livecodescript
Labels: bug, vulcan/reviewed

#6749 [[ Bug 21647 ]] Dictionary error: description of exp1
  docs/dictionary/function/exp1.lcdoc
  docs/notes/bugfix-21647.md
Labels: bug, vulcan/reviewed

#6753 [[ Bug 19704 ]] Fixed HiDPI Win32 bug
  docs/notes/Bugfix-19704.md
  engine/src/exec-interface2.cpp
  engine/src/w32stack.cpp
Labels: bug, vulcan/reviewed

#6758 [17751] Correct the loc of option menus triggered by a popup stack
  docs/notes/bugfix-17751.md
  engine/src/desktop-menu.cpp
Labels: bug, vulcan/reviewed

#6762 [11794] Fix crash on iOS in a special case of 'hide this stack with visual ..'
  docs/notes/bugfix-11794.md
  engine/src/mbliphonestack.mm
Labels: bug, vulcan/reviewed

#6742 [15167] Escape special characters in android standalone label
  docs/notes/bugfix-15167.md
  ide-support/revsaveasandroidstandalone.livecodescript
Labels: bug, vulcan/reviewed

#6740 [[Docs]] Show-card command - Correct display
  docs/dictionary/command/show-cards.lcdoc
Labels: vulcan/reviewed

#6768 [21662] Fix crash when setting the scrollbar to false while scrolling
  docs/notes/bugfix-21662.md
  engine/src/control.cpp
Labels: bug, vulcan/reviewed

#6769 [[ Bug 21617 ]] Fix emscripten loading capsule from file
  docs/notes/bugfix-21617.md
  engine/src/mode_standalone.cpp
Labels: blocker, bug, vulcan/reviewed
