Repository livecode/livecode, pull requests merged in 2018-04, with the labels that each got.

#6464 [[ Bug 19754 ]] Enhance TreeView numeric sort to sort non-numbers
  extensions/widgets/treeview/notes/19754.md
  extensions/widgets/treeview/treeview.lcb
Labels: vulcan/reviewed

#6461 [[ Bug 19753 ]] Prevent TreeView chunk out of range error on Linux
  extensions/widgets/treeview/notes/19753.md
  extensions/widgets/treeview/treeview.lcb
Labels: bug, vulcan/reviewed

#6470 [Bug 21141] Fixed errors when setting textFont/textSize on Android native button
  docs/notes/bugfix-21141.md
  extensions/widgets/androidbutton/androidbutton.lcb
Labels: bug, vulcan/reviewed

#6473 Merge release 9.0.0 09.04.18
  docs/notes/bugfix-21161.md
  engine/src/globals.cpp
  engine/src/widget-ref.cpp
  engine/src/widget-ref.h
  extensions/widgets/browser/browser.lcb
  extensions/widgets/browser/notes/21107.md
  extensions/widgets/browser/notes/21121.md
  libbrowser/src/libbrowser_cef.cpp
  libbrowser/src/libbrowser_osx_webview.mm
Labels: vulcan/reviewed

#6466 Xcode 9.3 fixes
  engine/src/mac-core.mm
  engine/src/mac-internal.h
  engine/src/mac-surface.mm
Labels: cleanup, vulcan/reviewed

#6446 [Bugfix 15614] Replace URLEncode example
  docs/dictionary/function/URLEncode.lcdoc
  docs/notes/bugfix-15614.md
Labels: bug, documentation, vulcan/reviewed

#6449 [[ Bug 20488 ]] Ensure put throws when expecting preposition
  docs/dictionary/command/revBrowserSet.lcdoc
  docs/dictionary/property/scriptExecutionErrors.lcdoc
  docs/notes/bugfix-20488.md
  engine/src/cmds.cpp
  tests/lcs/docs/validate-dictionary.livecodescript
  tests/lcs/parser/put.parsertest
Labels: bug, vulcan/reviewed

#6437 [[ Bug 21080 ]] Check objc handler argument count matches
  docs/lcb/notes/21080.md
  libscript/src/script-instance.cpp
  tests/lcb/vm/interop-objc.lcb
Labels: bug, vulcan/reviewed

#6474 Merge develop 9.0 10.04.18
  docs/notes/bugfix-21141.md
  docs/notes/bugfix-21161.md
  engine/src/globals.cpp
  engine/src/widget-ref.cpp
  engine/src/widget-ref.h
  extensions/widgets/androidbutton/androidbutton.lcb
  extensions/widgets/browser/browser.lcb
  extensions/widgets/browser/notes/21107.md
  extensions/widgets/browser/notes/21121.md
  extensions/widgets/treeview/notes/19753.md
  extensions/widgets/treeview/notes/20142.md
  extensions/widgets/treeview/treeview.lcb
  libbrowser/src/libbrowser_cef.cpp
  libbrowser/src/libbrowser_osx_webview.mm
Labels: vulcan/reviewed

#6413 [[Dictionary]] touchMove minor update
  docs/dictionary/message/touchMove.lcdoc
Labels: vulcan/reviewed

#6415 [[ Bug 20678 ]] Take ownership of clipboard for private item
  docs/notes/bugfix-20678.md
  engine/src/w32-clipboard.cpp
  engine/src/w32-clipboard.h
Labels: bug, vulcan/reviewed

#6407 [[ Bug 20925 ]] Rebind dragboard when starting drag
  docs/notes/bugfix-20925.md
  engine/src/desktop.cpp
Labels: bug, vulcan/reviewed

#6325 Added support for Xcode 9.3 / iOS 11.3
  Installer/package.txt
  Makefile
  buildbot.py
  docs/notes/platforms.md
  ide-support/revdeploylibraryios.livecodescript
  prebuilt/fetch-libraries.sh
  prebuilt/scripts/build-icu.sh
  prebuilt/scripts/ios.inc
  tools/setup_xcode_sdks.py
Labels: vulcan/reviewed

#6468 [[ Bug 21109 ]] Limit clipboard clear setting fullClipboardData["text"]
  docs/dictionary/property/fullClipboardData.lcdoc
  docs/notes/bugfix-21109.md
  engine/src/clipboard.cpp
  tests/lcs/core/engine/clipboard.livecodescript
Labels: vulcan/reviewed

#6467 [[ mergExt ]] Update pointer
  builder/builder_utilities.livecodescript
Labels: vulcan/reviewed

#6477 Ensure you can use Xcode9.2 if 10.12.6 <= MacOS version < 10.13
  ide-support/revdeploylibraryios.livecodescript
Labels: bug, vulcan/reviewed

#6481 [[ Bug 20997 ]] Add release note
  docs/notes/bugfix-20997.md
Labels: vulcan/reviewed

#6482 [[ Bug 21062 ]] Add release note
  docs/notes/bugfix-21062.md
Labels: vulcan/reviewed

#6480 [[ tsNet ]] Update pointer
  builder/builder_utilities.livecodescript
Labels: enhancement, vulcan/reviewed

#6484 [[ Bug 21019 ]] Fix crash setting rect for orientation
  docs/dictionary/command/mobileSetFullScreenRectForOrientations.lcdoc
  engine/src/mblhandlers.cpp
Labels: blocker, bug, vulcan/reviewed

#6487 Merge develop 8.1 17.04.2018
  Installer/package.txt
  Makefile
  buildbot.py
  builder/builder_utilities.livecodescript
  docs/dictionary/command/mobileSetAllowedOrientations.lcdoc
  docs/dictionary/command/mobileSetFullScreenRectForOrientations.lcdoc
  docs/dictionary/function/mobileAllowedOrientations.lcdoc
  docs/dictionary/function/mobileOrientation.lcdoc
  docs/dictionary/message/orientationChanged.lcdoc
  docs/dictionary/message/touchMove.lcdoc
  docs/notes-base/platforms.md
  docs/notes/bugfix-20925.md
  docs/notes/bugfix-20997.md
  docs/notes/bugfix-21019.md
  docs/notes/bugfix-21062.md
  engine/src/desktop.cpp
  engine/src/exec-orientation.cpp
  engine/src/exec.h
  engine/src/mac-core.mm
  engine/src/mac-internal.h
  engine/src/mac-surface.mm
  engine/src/mblandroiddc.cpp
  engine/src/mblhandlers.cpp
  engine/src/stackview.cpp
  ide-support/revdeploylibraryios.livecodescript
  prebuilt/fetch-libraries.sh
  prebuilt/scripts/ios.inc
  tools/setup_xcode_sdks.py
Labels: vulcan/reviewed

#6488 Merge develop 9.0 17.04.2018
  Installer/package.txt
  Makefile
  buildbot.py
  builder/builder_utilities.livecodescript
  docs/dictionary/command/mobileSetAllowedOrientations.lcdoc
  docs/dictionary/command/mobileSetFullScreenRectForOrientations.lcdoc
  docs/dictionary/function/URLEncode.lcdoc
  docs/dictionary/function/mobileAllowedOrientations.lcdoc
  docs/dictionary/function/mobileOrientation.lcdoc
  docs/dictionary/message/orientationChanged.lcdoc
  docs/dictionary/message/touchMove.lcdoc
  docs/notes-base/platforms.md
  docs/notes/bugfix-15614.md
  docs/notes/bugfix-20678.md
  docs/notes/bugfix-20925.md
  docs/notes/bugfix-20997.md
  docs/notes/bugfix-21019.md
  docs/notes/bugfix-21062.md
  engine/src/desktop.cpp
  engine/src/exec-orientation.cpp
  engine/src/exec.h
  engine/src/mac-core.mm
  engine/src/mac-internal.h
  engine/src/mac-surface.mm
  engine/src/mblandroiddc.cpp
  engine/src/mblhandlers.cpp
  engine/src/stackview.cpp
  engine/src/w32-clipboard.cpp
  engine/src/w32-clipboard.h
  ide-support/revdeploylibraryios.livecodescript
  prebuilt/fetch-libraries.sh
  prebuilt/scripts/ios.inc
  tools/setup_xcode_sdks.py
Labels: clean merge, vulcan/reviewed

#6476 [Bug 21184] Ensure play command can play remote audiofiles on iOS
  docs/notes/bugfix-21184.md
  engine/src/mbliphonesound.mm
Labels: bug, enhancement, vulcan/reviewed

#6485 [[ Dictionary ]] dollar updates
  docs/dictionary/keyword/dollar.lcdoc
Labels: vulcan/reviewed

#6486 [[ Bug 21203 ]] Only post hiliteChanged when value actually changes
  extensions/widgets/switchbutton/notes/21203.md
  extensions/widgets/switchbutton/switchbutton.lcb
Labels: vulcan/reviewed

#6475 [[ CheatSheet ]] Add markdown output option
  docs/cheat-sheet/cheat-sheet.livecodescript
Labels: vulcan/reviewed

#6422 [[ Bug 21064 ]] Ensure assembly support modules' deps are in manifest
  docs/lcb/notes/21064.md
  tests/ide-support/standalonebuilder/assembly.livecodescript
  tests/lcs/extensions/libraries/multimoduleassemblydeps/assemblytest-support.lcb
  tests/lcs/extensions/libraries/multimoduleassemblydeps/assemblytest.lcb
  toolchain/lc-compile/src/generate.g
Labels: bug, vulcan/reviewed

#6458 [Cleanup] Reduce memory footprint of regex cache
  engine/src/exec-network.cpp
  engine/src/exec-strings.cpp
  engine/src/patternmatcher.cpp
  engine/src/patternmatcher.h
  engine/src/regex.cpp
  engine/src/regex.h
Labels: vulcan/reviewed

#6471 [[ Bug 20016 ]] Make sure emscripten behaviors are resolved
  docs/notes/bugfix-20016.md
  engine/src/mode_standalone.cpp
Labels: bug, vulcan/reviewed

#6490 [[ Android API ]] Use API 19
  config.py
  docs/development/build-android.md
  engine/src/java/com/runrev/android/nativecontrol/ExtVideoView.java
  ide-support/revdeploylibraryandroid.livecodescript
  prebuilt/scripts/android.inc
Labels: vulcan/reviewed

#6489 [[ Bug ]] Ignore stderr when calling xcodebuild
  ide-support/revsaveasiosstandalone.livecodescript
Labels: bug, vulcan/reviewed
