Repository livecode/livecode, pull requests merged in 2018-07, with the labels that each got.

#6601 [[ Bug ]] Fix pattern to filter android externals
  ide-support/revsaveasandroidstandalone.livecodescript
Labels: blocker, bug, vulcan/reviewed

#6456 [[ Bug 20839 ]] Improve appearance of Motif theme disabled button text / icons
  docs/notes/bugfix-20839-2.md
  engine/src/buttondraw.cpp
Labels: bug, vulcan/reviewed

#6602 [[ Player ]] Fix player not playing without setting playrate
  docs/notes/bugfix-21395.md
  engine/src/mac-av-player.mm
  engine/src/player-platform.cpp
Labels: LCS, bug, vulcan/reviewed

#6604 [[ Bug 19420 ]] Fix crash on resume in commercial android engine
  engine/src/globals.cpp
Labels: bug, vulcan/reviewed

#6606 Do not split up .framework folders between MacOS and Resources/_MacOS…
  docs/notes/bugfix-21398.md
  ide-support/revsaveasstandalone.livecodescript
Labels: bug, vulcan/reviewed

#6603 [[ PlayerPanning ]] Add stereo balance & panning properties to mac player
  docs/dictionary/property/audioPan.lcdoc
  docs/dictionary/property/leftBalance.lcdoc
  docs/dictionary/property/playLoudness.lcdoc
  docs/dictionary/property/rightBalance.lcdoc
  docs/notes/bugfix-20211.md
  docs/notes/feature-player-pan-mac.md
  engine/kernel.gyp
  engine/src/exec-interface-player.cpp
  engine/src/lextable.cpp
  engine/src/mac-av-player.mm
  engine/src/parsedef.h
  engine/src/platform.h
  engine/src/player-interface.h
  engine/src/player-legacy.cpp
  engine/src/player-legacy.h
  engine/src/player-platform.cpp
  engine/src/player-platform.h
  engine/src/player-srv-stubs.cpp
  engine/src/player.cpp
Labels: LCS, enhancement, vulcan/reviewed

#6609 [[ tsNet ]] Update pointer
  builder/builder_utilities.livecodescript
Labels: vulcan/reviewed

#6610 [[ Bug 21434 ]] Force bitmap view visible for visual effects
  docs/notes/bugfix-21434.md
  engine/src/java/com/runrev/android/Engine.java
Labels: blocker, bug, vulcan/reviewed

#6612 Merge develop 9.0 24.07.18
  builder/builder_utilities.livecodescript
  config.py
  config/android.gypi
  docs/development/build-android.md
  docs/dictionary/property/audioPan.lcdoc
  docs/dictionary/property/leftBalance.lcdoc
  docs/dictionary/property/playLoudness.lcdoc
  docs/dictionary/property/rightBalance.lcdoc
  docs/notes/bugfix-16366.md
  docs/notes/bugfix-16736.md
  docs/notes/bugfix-20211.md
  docs/notes/bugfix-20839-2.md
  docs/notes/bugfix-21171.md
  docs/notes/bugfix-21279.md
  docs/notes/bugfix-21304.md
  docs/notes/bugfix-21336.md
  docs/notes/bugfix-21356.md
  docs/notes/bugfix-21368.md
  docs/notes/bugfix-21386.md
  docs/notes/bugfix-21395.md
  docs/notes/bugfix-21398.md
  docs/notes/feature-player-pan-mac.md
  engine/kernel.gyp
  engine/rsrc/android-manifest.xml
  engine/src/buttondraw.cpp
  engine/src/em-dc.cpp
  engine/src/exec-interface-player.cpp
  engine/src/globals.cpp
  engine/src/java/com/runrev/android/Engine.java
  engine/src/java/com/runrev/android/NotificationModule.java
  engine/src/lextable.cpp
  engine/src/mac-av-player.mm
  engine/src/mblandroiddc.cpp
  engine/src/mblandroidmisc.cpp
  engine/src/mbldc.cpp
  engine/src/native-layer-ios.mm
  engine/src/parsedef.h
  engine/src/platform.h
  engine/src/player-interface.h
  engine/src/player-legacy.cpp
  engine/src/player-legacy.h
  engine/src/player-platform.cpp
  engine/src/player-platform.h
  engine/src/player-srv-stubs.cpp
  engine/src/player.cpp
  engine/src/redraw.cpp
  engine/src/stack.cpp
  engine/src/stack.h
  engine/src/stack2.cpp
  engine/src/stack3.cpp
  engine/src/stackview.cpp
  ide-support/revdeploylibraryandroid.livecodescript
  ide-support/revsaveasandroidstandalone.livecodescript
  ide-support/revsaveasstandalone.livecodescript
  prebuilt/fetch-libraries.sh
  prebuilt/libicu.gyp
  prebuilt/libopenssl.gyp
Labels: clean merge, vulcan/reviewed

#6584 [[ Android ]] Support additional android CPU architectures
  Makefile
  config-rpi.sh
  config.py
  config/android-settings.gypi
  engine/engine-common.gyp
  engine/engine.gyp
  engine/host-server.gyp
  engine/kernel-server.gyp
  engine/lcb-modules.gyp
  engine/src/mblandroidlcb.cpp
  engine/src/opensslsocket.cpp
  engine/src/sysunxdate.cpp
  engine/standalone-android.link
  libbrowser/libbrowser.gyp
  libbrowser/src/libbrowser_lnx_factories.cpp
  libcore/libcore.gyp
  libexternal/libexternal.gyp
  libfoundation/include/foundation.h
  libgraphics/libgraphics.gyp
  prebuilt/fetch-libraries.sh
  prebuilt/libcef.gyp
  prebuilt/libcurl.gyp
  prebuilt/libicu.gyp
  prebuilt/libopenssl.gyp
  prebuilt/scripts/android.inc
  prebuilt/scripts/build-curl.sh
  prebuilt/scripts/build-icu.sh
  prebuilt/scripts/build-openssl.sh
  prebuilt/scripts/platform.inc
  revbrowser/revbrowser.gyp
  tests/Makefile
  toolchain/lc-compile-ffi-java/lc-compile-ffi-java.gyp
  toolchain/lc-compile/lc-compile.gyp
  util/run-tests.pl
Labels: vulcan/reviewed

#6615 [[ Bug ]] Move TISCopyCurrentKeyboardInputSource to main thread
  engine/src/mac-abort.mm
Labels: bug, vulcan/reviewed
