Repository livecode/livecode, pull requests merged in 2019-05, with the labels that each got.

#7005 Merge release 9.0.4 01.05.2019
  docs/notes/bugfix-21984.md
  engine/src/mblandroiddc.cpp
Labels: vulcan/reviewed

#6621 [[ Xcode Setup ]] Add support for setup of Xcode-beta.app
  tools/setup_xcode_sdks.py
Labels: vulcan/reviewed

#7012 [[ Deploy Docs ]] Move deploy docs to IDE repo
  docs/guides/HTML5 Deployment.md
  docs/guides/Mac Deployment.md
Labels: vulcan/reviewed

#6821 [[ Win 64 ]] Add support for 64 bit standalones on Windows
  Installer/package.txt
  buildbot.mk
  builder/builder_tool.livecodescript
  builder/builder_utilities.livecodescript
  builder/server_builder.livecodescript
  builder/tools_builder.livecodescript
  builder/windows_manifest.xml
  configure.bat
  docs/notes/feature-win64-deployment.md
  engine/src/deploy.h
  engine/src/deploy_sign.cpp
  engine/src/deploy_windows.cpp
  ide-support/revsaveasstandalone.livecodescript
  ide-support/revsblibrary.livecodescript
  lcidlc/lcidlc.gyp
Labels: vulcan/reviewed

#6942 [[ Bug 12419 ]] Ensure Android ScrollViews don't cancel touch events
  docs/notes/bugfix-12419.md
  engine/src/java/com/runrev/android/nativecontrol/ScrollerControl.java
Labels: bug, vulcan/reviewed

#6641 [[Bugfix 14721]] Implement 'go visible <stack>' as an antonym to 'go invisible'
  docs/dictionary/command/go.lcdoc
  docs/notes/Bugfix-14721.md
  engine/src/cmds.h
  engine/src/cmdss.cpp
  engine/src/exec-interface.cpp
  engine/src/exec.h
  tests/lcs/core/interface/go.livecodescript
  tests/lcs/parser/go.parsertest
Labels: vulcan/reviewed

#6813 [[ Bug 14316 ]] Allow infinite result in div, times and pow operations
  docs/dictionary/command/add.lcdoc
  docs/dictionary/command/divide.lcdoc
  docs/dictionary/command/multiply.lcdoc
  docs/dictionary/command/subtract.lcdoc
  docs/dictionary/function/acos.lcdoc
  docs/dictionary/function/annuity.lcdoc
  docs/dictionary/function/asin.lcdoc
  docs/dictionary/function/atan.lcdoc
  docs/dictionary/function/atan2.lcdoc
  docs/dictionary/function/average.lcdoc
  docs/dictionary/function/averageDeviation.lcdoc
  docs/dictionary/function/compound.lcdoc
  docs/dictionary/function/exp.lcdoc
  docs/dictionary/function/exp1.lcdoc
  docs/dictionary/function/exp10.lcdoc
  docs/dictionary/function/exp2.lcdoc
  docs/dictionary/function/geometricMean.lcdoc
  docs/dictionary/function/harmonicMean.lcdoc
  docs/dictionary/function/ln.lcdoc
  docs/dictionary/function/ln1.lcdoc
  docs/dictionary/function/log10.lcdoc
  docs/dictionary/function/log2.lcdoc
  docs/dictionary/function/median.lcdoc
  docs/dictionary/function/populationStandardDeviation.lcdoc
  docs/dictionary/function/populationVariance.lcdoc
  docs/dictionary/function/sqrt.lcdoc
  docs/dictionary/function/standardDeviation.lcdoc
  docs/dictionary/function/sum.lcdoc
  docs/dictionary/function/variance.lcdoc
  docs/dictionary/operator/asterisk.lcdoc
  docs/dictionary/operator/caret.lcdoc
  docs/dictionary/operator/div.lcdoc
  docs/dictionary/operator/mod.lcdoc
  docs/dictionary/operator/plus.lcdoc
  docs/dictionary/operator/slash.lcdoc
  docs/dictionary/operator/wrap.lcdoc
  docs/glossary/m/math-operation.lcdoc
  docs/notes/bugfix-14316.md
  docs/notes/feature-math_errors.md
  engine/src/exec-math.cpp
  engine/src/exec.h
  engine/src/executionerrors.h
  engine/src/osspec.h
  engine/src/sysspec.cpp
  engine/src/util.cpp
  engine/src/util.h
  tests/_testlib.livecodescript
  tests/lcs/core/math/arithmetic-commands.livecodescript
  tests/lcs/core/math/errors.livecodescript
  tests/lcs/core/math/infinity.livecodescript
  tests/lcs/core/math/math.livecodescript
  tests/lcs/core/math/stats.livecodescript
Labels: vulcan/reviewed

#6270 [[ WidgetUtils ]] Use icon library for placeholder icons where possible
  extensions/modules/widget-utils/widget-utils.lcb
  extensions/widgets/androidfield/tests/properties.livecodescript
  extensions/widgets/browser/tests/basic.livecodescript
  extensions/widgets/graph/tests/properties.livecodescript
  extensions/widgets/header/tests/properties.livecodescript
  extensions/widgets/html5button/html5button.lcb
  extensions/widgets/mactextfield/tests/properties.livecodescript
  extensions/widgets/navbar/tests/properties.livecodescript
  extensions/widgets/paletteactions/tests/basic.livecodescript
  extensions/widgets/svgpath/tests/properties.livecodescript
Labels: vulcan/reviewed

#7016 Revert "[[ WidgetUtils ]] Use icon library for placeholder icons where possible"
  extensions/modules/widget-utils/widget-utils.lcb
  extensions/widgets/androidfield/tests/properties.livecodescript
  extensions/widgets/browser/tests/basic.livecodescript
  extensions/widgets/graph/tests/properties.livecodescript
  extensions/widgets/header/tests/properties.livecodescript
  extensions/widgets/html5button/html5button.lcb
  extensions/widgets/mactextfield/tests/properties.livecodescript
  extensions/widgets/navbar/tests/properties.livecodescript
  extensions/widgets/paletteactions/tests/basic.livecodescript
  extensions/widgets/svgpath/tests/properties.livecodescript
Labels: vulcan/reviewed

#7014 [[ Release Notes ]] Fix issue with release notes extension category
  builder/release_notes_builder.livecodescript
Labels: vulcan/reviewed

#7015 [[ Version ]] Update for 9.5.0
  version
Labels: vulcan/reviewed

#6802 [[ Bug ]] Fix extension copy resources
  ide-support/revsblibrary.livecodescript
Labels: bug, vulcan/reviewed

#6664 [[ Bug ]] Include library in objc binding string definition
  docs/guides/LiveCode Builder Language Reference.md
Labels: bug, documentation, vulcan/reviewed

#6893 [[ Bug ]] Fix crash and behavior of popup widget
  engine/src/exec-interface.cpp
  engine/src/widget-popup.cpp
Labels: vulcan/reviewed

#7009 [[ Bug 16293 ]] Ensure inf is converted to string correctly
  engine/src/util.cpp
  tests/lcs/core/math/infinity.livecodescript
Labels: bug, vulcan/reviewed

#6569 [[ Bug 21343 ]] Add extension security permission
  docs/dictionary/property/secureMode.lcdoc
  docs/dictionary/property/securityCategories.lcdoc
  docs/dictionary/property/securityPermissions.lcdoc
  docs/notes/bugfix-21343.md
  engine/src/exec-engine.cpp
  engine/src/exec-extension.cpp
  engine/src/securemode.cpp
  engine/src/securemode.h
  tests/lcs/core/security/_extension.lcb
  tests/lcs/core/security/securitypermissions.livecodescript
Labels: enhancement, vulcan/reviewed

#6782 [[ Log ]] log command and logMessage global property
  docs/dictionary/command/log.lcdoc
  docs/dictionary/property/logmessage.lcdoc
  docs/notes/feature-log.md
  engine/src/cmds.h
  engine/src/cmdse.cpp
  engine/src/debug.cpp
  engine/src/debug.h
  engine/src/exec-debugging.cpp
  engine/src/exec.h
  engine/src/globals.cpp
  engine/src/handler.cpp
  engine/src/lextable.cpp
  engine/src/newobj.cpp
  engine/src/parsedef.h
  engine/src/property.cpp
  tests/_testlib.livecodescript
  tests/lcs/core/debugging/_log.lc
  tests/lcs/core/debugging/_log.livecodescript
  tests/lcs/core/debugging/log.livecodescript
Labels: enhancement, vulcan/reviewed

#7018 [[ WidgetUtils ]] Add per-platform placeholder icons to widget utils library
  extensions/modules/widget-utils/widget-utils.lcb
  extensions/widgets/html5button/html5button.lcb
Labels: vulcan/reviewed

#6810 [[ libbrowser ]] Progress, isSecure and allowUserInteraction
  docs/notes/feature-browser_progress_secure_and_interaction.md
  engine/src/browser.lcb
  engine/src/java/com/runrev/android/libraries/LibBrowser.java
  extensions/widgets/browser/browser.lcb
  libbrowser/include/libbrowser.h
  libbrowser/src/libbrowser.cpp
  libbrowser/src/libbrowser_android.cpp
  libbrowser/src/libbrowser_cef.cpp
  libbrowser/src/libbrowser_cef.h
  libbrowser/src/libbrowser_cef_lnx.cpp
  libbrowser/src/libbrowser_cef_win.cpp
  libbrowser/src/libbrowser_internal.h
  libbrowser/src/libbrowser_osx_webview.h
  libbrowser/src/libbrowser_osx_webview.mm
  libbrowser/src/libbrowser_uiwebview.h
  libbrowser/src/libbrowser_uiwebview.mm
Labels: vulcan/reviewed

#6663 [[ Bug ]] Fix alloc & init handler definitions
  extensions/widgets/macbutton/macbutton.lcb
  extensions/widgets/mactextfield/mactextfield.lcb
Labels: bug, vulcan/reviewed

#7021 [[ Bug 22047 ]] Allow nothing as variadic argument to foreign handler
  docs/lcb/notes/22047.md
  libscript/src/script-execute.cpp
  tests/lcb/vm/foreign-invoke.lcb
Labels: LCB, bug, vulcan/reviewed

#7022 [9.0.4] Updated version
  version
Labels: vulcan/reviewed

#6812 [[ Constants ]] Refactor constants and add infinity constant
  docs/dictionary/constant/infinity.lcdoc
  docs/notes-base/breaking_changes.md
  docs/notes/feature-infinity.md
  docs/notes/feature-real-boolean-constants.md
  engine/engine-sources.gypi
  engine/src/constant.cpp
  engine/src/constant.h
  engine/src/exec-engine.cpp
  engine/src/keywords.cpp
  engine/src/lextable.cpp
  engine/src/scriptpt.cpp
  engine/src/scriptpt.h
  engine/test/test_lextable.cpp
  extensions/widgets/paletteactions/paletteactions.lcb
  tests/lcs/core/constants/constants.livecodescript
  tests/lcs/core/logic/isstrictly.livecodescript
  tests/lcs/core/math/infinity.livecodescript
  tests/lcs/parser/constants.parsertest
Labels: vulcan/reviewed

#7024 [[ Bug ]] Fix failing LCB varargs test on Linux
  tests/lcb/vm/foreign-invoke.lcb
Labels: bug, vulcan/reviewed

#6626 [[ Bug 18309 ]] Implement filter where expression
  docs/dictionary/command/filter.lcdoc
  docs/notes/bugfix-18309.md
  engine/src/cmdsf.cpp
  engine/src/exec-array.cpp
  engine/src/exec-strings.cpp
  engine/src/exec.h
  engine/src/parsedef.h
  engine/src/patternmatcher.cpp
  engine/src/patternmatcher.h
  tests/lcs/core/array/filter.livecodescript
  tests/lcs/core/strings/filter.livecodescript
Labels: enhancement, vulcan/reviewed

#6648 [[ Bug 21464-7 ]] Keyboard properties
  docs/dictionary/command/mobileSetKeyboardDisplay.lcdoc
  docs/dictionary/command/mobileSetKeyboardReturnKey.lcdoc
  docs/dictionary/command/mobileSetKeyboardType.lcdoc
  docs/dictionary/function/mobileGetKeyboardDisplay.lcdoc
  docs/dictionary/message/keyboardActivated.lcdoc
  docs/dictionary/message/keyboardDeactivated.lcdoc
  docs/dictionary/property/keyboardType.lcdoc
  docs/dictionary/property/returnKeyType.lcdoc
  docs/notes/bugfix-21464.md
  docs/notes/bugfix-21465.md
  docs/notes/bugfix-21466.md
  docs/notes/bugfix-21467.md
  engine/src/exec-interface-field.cpp
  engine/src/exec-interface.h
  engine/src/exec-misc.cpp
  engine/src/exec.h
  engine/src/field.cpp
  engine/src/field.h
  engine/src/java/com/runrev/android/Engine.java
  engine/src/lextable.cpp
  engine/src/mblandroiddc.cpp
  engine/src/mblandroidmisc.cpp
  engine/src/mblhandlers.cpp
  engine/src/mbliphoneapp.h
  engine/src/mbliphoneapp.mm
  engine/src/mbliphoneextra.mm
  engine/src/mbliphonegfx.mm
  engine/src/mbliphoneview.h
  engine/src/mblsyntax.h
  tests/_testlib.livecodescript
  tests/lcs/core/field/softkeyboardproperties.livecodescript
Labels: enhancement, vulcan/reviewed

#7006 [[ AccelRender ]] Add container layer modes
  docs/dictionary/property/layerMode.lcdoc
  docs/notes/feature-container_layermode
  engine/src/card.cpp
  engine/src/card.h
  engine/src/exec-interface-control.cpp
  engine/src/mccontrol.h
  engine/src/redraw.cpp
  engine/src/tilecache.cpp
Labels: enhancement, vulcan/reviewed

#7023 [[ Tests ]] Make verbose mode less verbose
  tests/_testrunnerbehavior.livecodescript
Labels: vulcan/reviewed

#7026 [[ Bug ]] Fix crash on creation of browser widget
  libbrowser/src/libbrowser.cpp
Labels: bug, vulcan/reviewed

#7007 [[ Engine ]] Add 'layerClipRect' property to controls
  docs/dictionary/property/layerClipRect.lcdoc
  docs/notes/feature-layercliprect.md
  engine/src/control.cpp
  engine/src/exec-interface-control.cpp
  engine/src/lextable.cpp
  engine/src/mccontrol.h
  engine/src/parsedef.h
  engine/src/redraw.cpp
Labels: enhancement, vulcan/reviewed

#7030 Merge develop 9.0 12.05.2019
  docs/guides/LiveCode Builder Language Reference.md
  docs/lcb/notes/22047.md
  docs/notes/bugfix-12419.md
  docs/notes/bugfix-22042.md
  engine/src/java/com/runrev/android/nativecontrol/ScrollerControl.java
  extensions/widgets/macbutton/macbutton.lcb
  extensions/widgets/mactextfield/mactextfield.lcb
  ide-support/revsblibrary.livecodescript
  libscript/src/script-execute.cpp
  tests/_testrunnerbehavior.livecodescript
  tests/lcb/vm/foreign-invoke.lcb
Labels: vulcan/reviewed

#7028 [[ Bugfix MultileAarRes ]] Support multiple AAR resource folders
  ide-support/revsaveasandroidstandalone.livecodescript
Labels: vulcan/reviewed

#7031 [[ Canvas ]] Add ability to get density property of canvas images
  docs/lcb/notes/feature-canvas_image_metadata.md
  engine/src/canvas.lcb
  engine/src/exec-interface-image.cpp
  engine/src/image_rep.cpp
  engine/src/module-canvas.cpp
  engine/src/module-canvas.h
Labels: LCB, enhancement, vulcan/reviewed

#7034 [[ Windows ]] Set default target correctly for commercial
  make.cmd
Labels: vulcan/reviewed

#7035 [[ Bug ]] Android arch issues
  ide-support/revdeploylibraryandroid.livecodescript
  ide-support/revsaveasandroidstandalone.livecodescript
Labels: bug, vulcan/reviewed

#6653 [[ Bug 20027 ]] Ensure UQL is cleard when setting container value
  docs/notes/bugfix-20027.md
  engine/src/variable.cpp
  tests/lcs/core/execution/uql.livecodescript
Labels: bug, vulcan/reviewed

#7033 [[ canvas ]] Add `begin effect only layer with <effect> on <canvas>` syntax
  docs/lcb/notes/feature-effect_only_layer.md
  engine/src/canvas.lcb
  engine/src/graphicscontext.cpp
  engine/src/module-canvas.cpp
  engine/src/module-canvas.h
  engine/src/player-platform.cpp
  libgraphics/include/graphics.h
  libgraphics/src/context.cpp
Labels: LCB, enhancement, vulcan/reviewed

#6656 [[ Resolve File ]] Implement resolve file relative to object
  docs/lcb/notes/19137.md
  docs/lcb/notes/feature-resolvefile.md
  engine/src/canvas.lcb
  engine/src/engine.lcb
  engine/src/module-canvas.cpp
  engine/src/module-engine.cpp
  engine/src/module-engine.h
  tests/lcs/core/engine-lcb/_canvas.lcb
  tests/lcs/core/engine-lcb/_engine.lcb
  tests/lcs/core/engine-lcb/_test_image.png
  tests/lcs/core/engine-lcb/_widget_canvas.lcb
  tests/lcs/core/engine-lcb/_widget_engine.lcb
  tests/lcs/core/engine-lcb/canvas.livecodescript
  tests/lcs/core/engine-lcb/engine.livecodescript
Labels: enhancement, vulcan/reviewed

#7038 [[ ReleaseNotes ]] Fix issue with release notes extension category
  builder/release_notes_builder.livecodescript
Labels: vulcan/reviewed

#7037 [[ Config ]] Added unzip gyp rule
  config/unzip.gypi
Labels: vulcan/reviewed

#7036 [[ Config ]] Added google play path to android gyp config
  config/android.gypi
Labels: vulcan/reviewed

#7042 [[ Bug ]] Strip quotes when pathifying arguments
  tools/pathify.sh
Labels: vulcan/reviewed

#7043 [[ Bug 21941 ]] Ensure calls into Java don't accumulate JNI local-refs
  docs/notes/bugfix-21941.md
  libfoundation/src/foundation-java-private.cpp
Labels: bug, vulcan/reviewed

#6660 [[ Mac Status Menu ]] Implement mac status menu library
  Installer/package.txt
  extensions/extensions.gyp
  extensions/libraries/macstatusmenu/macstatusmenu.lcb
  extensions/libraries/macstatusmenu/notes/feature-macstatusmenu.md
Labels: enhancement, vulcan/reviewed

#7044 [[ Bug 22063 ]] Ensure nothing is a valid optional foreign handler value
  docs/lcb/notes/22063.md
  libscript/src/script-execute.cpp
  tests/lcb/vm/native-callback.lcb
Labels: LCB, bug, vulcan/reviewed

#7040 [[ Bug 22060 ]] Stop point values with matching hashes from overwriting each other.
  docs/lcb/notes/22060.md
  engine/src/module-canvas.cpp
Labels: LCB, bug, vulcan/reviewed

#7047 [[ Bug ]] Fix handler function pointers on newer Android versions
  libfoundation/src/foundation-handler.cpp
Labels: bug, vulcan/reviewed

#7049 [[ Bug ]] Fix evaluation of mobile handler parameters
  engine/src/mblhandlers.cpp
Labels: bug, vulcan/reviewed

#7046 Merge develop 9.0 15.05.2019
  docs/lcb/notes/22060.md
  docs/lcb/notes/22063.md
  docs/notes/bugfix-20027.md
  docs/notes/bugfix-21941.md
  engine/src/mblhandlers.cpp
  engine/src/module-canvas.cpp
  engine/src/variable.cpp
  libfoundation/src/foundation-java-private.cpp
  libscript/src/script-execute.cpp
  tests/lcb/vm/native-callback.lcb
  tests/lcs/core/execution/uql.livecodescript
Labels: clean merge, vulcan/reviewed

#7045 [[ Bug ]] Ensure browser widget callbacks are reset on finalize
  engine/src/browser.lcb
  extensions/widgets/browser/browser.lcb
Labels: bug, vulcan/reviewed

#7053 [[ Cleanup ]] Move incorrectly placed note
  docs/lcb/notes/feature-widget_touch.md
Labels: cleanup

#7054 [[ Bug ]] Fix crash rendering card with no controls
  engine/src/redraw.cpp
Labels: blocker, bug, vulcan/reviewed

#7029 [[ PlayAAR ]] LCB files can now specify play AARs they depend on.
  ide-support/revdeploylibraryandroid.livecodescript
  ide-support/revsaveasandroidstandalone.livecodescript
  ide-support/revsblibrary.livecodescript
Labels: vulcan/reviewed

#7027 [[ AndroidPermissionsLCB ]] Added permission checking handlers to and…
  engine/src/mblandroiddc.cpp
  engine/src/mblandroidutil.h
  extensions/modules/android-utils/android-utils.lcb
  extensions/modules/android-utils/notes/feature-android_permissions.md
Labels: vulcan/reviewed

#7052 [[ Bug ]] Fix module lcext note to describe correct docs update
  docs/notes/feature-modulelcext.md
Labels: bug

#7055 [[ Bug ]] Make sure the updater reports the correct platform
  builder/installer/installeruiupdatecheckcardbehavior.livecodescript
Labels: vulcan/reviewed

#7058 [[ Bug 22074 ]] Ensure S/B doesn't warn about missing builtin modules
  extensions/script-libraries/extension-utils/extension-utils.livecodescript
  ide-support/revsblibrary.livecodescript
Labels: vulcan/reviewed

#7056 [[ Bug 22070 ]] Fix answer with type on macOS
  docs/notes/bugfix-22070.md
  engine/src/desktop-ans.cpp
Labels: bug, vulcan/reviewed

#7063 [Dictionary] movingControls to pageRange
  docs/dictionary/command/open-file.lcdoc
  docs/dictionary/command/open-process.lcdoc
  docs/dictionary/control_st/on.lcdoc
  docs/dictionary/function/movingControls.lcdoc
  docs/dictionary/function/optionKey.lcdoc
  docs/dictionary/keyword/msg.lcdoc
  docs/dictionary/keyword/opaque.lcdoc
  docs/dictionary/message/msgChanged.lcdoc
  docs/dictionary/message/newGroup.lcdoc
  docs/dictionary/property/name.lcdoc
  docs/dictionary/property/pageRanges.lcdoc
Labels: vulcan/reviewed

#7068 [9.5 DP-2] Updated version
  version
Labels: vulcan/reviewed

#7067 [[ Bug 22100 ]] Ensure x86_64 is a synonym of x86-64
  docs/notes/bugfix-22100.md
  ide-support/revsblibrary.livecodescript
Labels: vulcan/reviewed

#7066 [[ Bug 17323 ]] refresh windows after backdrop is created
  engine/src/lnxdcs.cpp
Labels: bug, vulcan/reviewed

#7071 [9.0.5] Updated version
  version
Labels: vulcan/reviewed

#7072 [12315] Ensure files open for driver have stdio buffering turned off
  docs/notes/bugfix-12315.md
  engine/src/dsklnx.cpp
  engine/src/dskmac.cpp
Labels: bug, vulcan/reviewed

#7065 [[ Bug 22084 ]] Fix extension release note edition section
  builder/release_notes_builder.livecodescript
  docs/notes/bugfix-22084.md
Labels: bug, vulcan/reviewed

#7060 [[ Bug 22085 ]] Fix use after release of dashes struct lengths field
  docs/notes/bugfix-22085.md
  libgraphics/src/context.cpp
Labels: vulcan/reviewed

#7069 [22079] Fix crash when putting before/after an invalid container
  docs/notes/bugfix-22079.md
  engine/src/chunk.cpp
  tests/lcs/core/engine/put.livecodescript
Labels: bug, vulcan/reviewed

#7078 [22129] Serial I/O: Expand the baudrates on Linux and Mac
  docs/notes/bugfix-22129.md
  engine/src/dsklnx.cpp
  engine/src/dskmac.cpp
Labels: enhancement, vulcan/reviewed

#7080 [9.0.6 rc-1] Updated version
  version
Labels: vulcan/reviewed
