Repository livecode/livecode, pull requests merged in 2019-11, with the labels that each got.

#7217 fixed callback typo
  engine/src/module-canvas.cpp
Labels: vulcan/reviewed

#7216 weak link glib not needed here
  engine/src/lnxdcs.cpp
Labels: vulcan/reviewed

#7218 [[ Player ]] Update iOS mobile player control to use AVKit framework
  docs/dictionary/command/mobileControlDo.lcdoc
  docs/dictionary/command/mobileControlSet.lcdoc
  docs/dictionary/function/mobileControlGet.lcdoc
  docs/notes/feature-mobile-player-ios-avkit.md
  engine/kernel.gyp
  engine/src/mbliphonecontrol.h
  engine/src/mbliphoneinput.mm
  engine/src/mbliphoneplayer.mm
  engine/src/mbliphonevideo.mm
  engine/standalone.ios
Labels: enhancement, vulcan/reviewed

#7183 Fix error when deploying to iOS 13.x simulator
  engine/rsrc/mobile-template.plist
Labels: blocker, bug, vulcan/reviewed

#7223 [[ PlayerControl ]] Fix iOS9.2 build errors after update to AVKit player
  engine/src/mbliphoneplayer.mm
  engine/src/mbliphonevideo.mm
Labels: blocker, bug, vulcan/reviewed

#7222 [[ libbrowser ]] Update iOS browser implementation to use WKWebView
  docs/dictionary/command/mobileControlDo.lcdoc
  docs/dictionary/command/mobileControlSet.lcdoc
  docs/dictionary/message/browserLoadRequest.lcdoc
  docs/dictionary/message/browserLoadRequested.lcdoc
  docs/dictionary/object/iosBrowser.lcdoc
  docs/notes/feature-mobile-browser-ios-wkwebview.md
  engine/src/browser.lcb
  engine/src/mbliphonebrowser.mm
  engine/src/module-browser.cpp
  engine/standalone.ios
  extensions/widgets/browser/browser.lcb
  extensions/widgets/browser/notes/feature-browser-widget-ios-wkwebview.md
  libbrowser/include/libbrowser.h
  libbrowser/libbrowser.gyp
  libbrowser/src/libbrowser.cpp
  libbrowser/src/libbrowser_android.cpp
  libbrowser/src/libbrowser_cef.cpp
  libbrowser/src/libbrowser_cef.h
  libbrowser/src/libbrowser_cef_win.cpp
  libbrowser/src/libbrowser_internal.h
  libbrowser/src/libbrowser_ios_factories.cpp
  libbrowser/src/libbrowser_nsvalue.h
  libbrowser/src/libbrowser_nsvalue.mm
  libbrowser/src/libbrowser_osx_webview.h
  libbrowser/src/libbrowser_osx_webview.mm
  libbrowser/src/libbrowser_uiwebview.mm
  libbrowser/src/libbrowser_wkwebview.h
  libbrowser/src/libbrowser_wkwebview.mm
  libfoundation/include/foundation-auto.h
Labels: enhancement, vulcan/reviewed

#7224 Remove support for iOS 8.2 simulator
  Installer/package.txt
  Makefile
  config.py
  docs/notes-base/platforms.md
  ide-support/revdeploylibraryios.livecodescript
  prebuilt/fetch-libraries.sh
  prebuilt/scripts/ios.inc
  tools/setup_xcode_sdks.py
Labels: vulcan/reviewed

#7225 [[ Bug 22463 ]] Fix compilation of SVG ellipses
  docs/notes/bugfix-22463.md
  extensions/script-libraries/drawing/drawing.livecodescript
Labels: bug, vulcan/reviewed

#7227 Drop support for iOS 9.2
  Installer/package.txt
  Makefile
  config.py
  docs/notes-base/platforms.md
  ide-support/revdeploylibraryios.livecodescript
  prebuilt/fetch-libraries.sh
  prebuilt/scripts/ios.inc
  tools/setup_xcode_sdks.py
Labels: vulcan/reviewed

#7228 Merge develop 9.5 21.11.2019
  builder/builder_utilities.livecodescript
  docs/dictionary/command/start-session.lcdoc
  docs/dictionary/function/controlAtLoc.lcdoc
  docs/dictionary/function/controlAtScreenLoc.lcdoc
  docs/dictionary/property/fullClipboardData.lcdoc
  docs/dictionary/property/showController.lcdoc
  docs/dictionary/property/startAngle.lcdoc
  docs/dictionary/property/strokeGradient.lcdoc
  docs/dictionary/property/styledText.lcdoc
  docs/dictionary/property/tabGroupBehavior.lcdoc
  docs/glossary/s/SOAP.lcdoc
  docs/glossary/s/stack-version.lcdoc
  docs/notes/Bugfix-20472.md
  docs/notes/bugfix-15645.md
Labels: vulcan/reviewed

#7148 [[ Bug 22346 ]] Add tests for sqlite error with sprintf format specifier
  docs/notes/bugfix-22346.md
  tests/lcs/core/database/sqlite_error.livecodescript
Labels: bug, vulcan/reviewed

#7201 [[ RevPDFPrinter ]] Add Android support to revpdfprinter library
  docs/dictionary/command/open-printing-to-pdf.lcdoc
  docs/notes/feature-revpdfprinter-android.md
  engine/kernel.gyp
  engine/src/customprinter.cpp
  engine/src/mblandroidtextlayout.cpp
  ide-support/revsaveasandroidstandalone.livecodescript
  ide-support/revsblibrary.livecodescript
  livecode.gyp
  prebuilt/scripts/lib_versions.inc
  prebuilt/thirdparty.gyp
  revpdfprinter/revpdfprinter.gyp
  revpdfprinter/src/revpdfprinter_android.cpp
Labels: enhancement, vulcan/reviewed

#7229 [[ CEF ]] Update to 74.1.19
  prebuilt/versions/cef
  prebuilt/versions/cef_buildrevision
  prebuilt/versions/cefchromium
Labels: vulcan/reviewed

#7230 Include Android revpdfprinter to installer
  Installer/package.txt
Labels: blocker, vulcan/reviewed

#7197 [[ Bug 22382 ]] Account for soft button bar on Android
  docs/notes/bugfix-22382.md
  engine/src/java/com/runrev/android/Engine.java
Labels: bug, vulcan/reviewed

#7194 [[ Bug 22414 ]] Fix crash coalescing window reshape events
  docs/notes/bugfix-22414.md
  engine/src/eventqueue.cpp
Labels: bug, vulcan/reviewed

#7154 [[TreeView Widget]] Mobile Support Enhancements
  extensions/widgets/treeview/notes/21719.md
  extensions/widgets/treeview/notes/22386.md
  extensions/widgets/treeview/notes/22387.md
  extensions/widgets/treeview/notes/feature-mobile_support.md
  extensions/widgets/treeview/treeview.lcb
Labels: vulcan/reviewed
