Repository livecode/livecode, pull requests merged in 2019-07, with the labels that each got.

#7121 Update readme © dates
  README.md
Labels: vulcan/reviewed

#7124 [Dictionary] revAppVersion to revXMLEvaluatePath
  docs/dictionary/command/revExecuteSQL.lcdoc
  docs/dictionary/command/revInitializeVideoGrabber.lcdoc
  docs/dictionary/command/revMail.lcdoc
  docs/dictionary/command/revPrintReport.lcdoc
  docs/dictionary/command/revShowPrintDialog.lcdoc
  docs/dictionary/function/revAppVersion.lcdoc
  docs/dictionary/function/revBrowserGet.lcdoc
  docs/dictionary/function/revBrowserInstances.lcdoc
  docs/dictionary/function/revXMLCreateTreeWithNamespaces.lcdoc
  docs/dictionary/function/revXMLDataFromXPathQuery.lcdoc
  docs/dictionary/function/revXMLEvaluateXPath.lcdoc
Labels: vulcan/reviewed

#7123 [Dictionary] relayerGroupsControls to return
  docs/dictionary/command/reply.lcdoc
  docs/dictionary/command/request-appleEvent.lcdoc
  docs/dictionary/command/request.lcdoc
  docs/dictionary/control_st/return.lcdoc
  docs/dictionary/function/result.lcdoc
  docs/dictionary/property/relayerGroupedControls.lcdoc
  docs/dictionary/property/resizable.lcdoc
  docs/dictionary/property/resizeQuality.lcdoc
  docs/dictionary/property/retainImage.lcdoc
  docs/dictionary/property/retainPostScript.lcdoc
  docs/glossary/r/ResEdit.lcdoc
Labels: vulcan/reviewed

#7116 [Bugfix-21803] Add file overwrite warning to rename entry
  docs/dictionary/command/rename.lcdoc
  docs/notes/bugfix-21803.md
Labels: vulcan/reviewed

#7126 [[ Bug 22167 ]] Fix iOS standalone engine link issue
  extensions/libraries/timezone/notes/22167.md
  ide-support/revsaveasiosstandalone.livecodescript
  ide-support/revsblibrary.livecodescript
Labels: blocker, bug, vulcan/reviewed

#7128 [9.5 RC-1] Updated version
  version
Labels: vulcan/reviewed

#7129 Merge develop 9.0 23.07.2019
  docs/dictionary/command/print-link.lcdoc
  docs/dictionary/command/put.lcdoc
  docs/dictionary/command/rename.lcdoc
  docs/dictionary/command/reply.lcdoc
  docs/dictionary/command/request-appleEvent.lcdoc
  docs/dictionary/command/request.lcdoc
  docs/dictionary/command/revExecuteSQL.lcdoc
  docs/dictionary/command/revInitializeVideoGrabber.lcdoc
  docs/dictionary/command/revMail.lcdoc
  docs/dictionary/command/revPrintReport.lcdoc
  docs/dictionary/command/revShowPrintDialog.lcdoc
  docs/dictionary/control_st/return.lcdoc
  docs/dictionary/function/recordCompressionTypes.lcdoc
  docs/dictionary/function/result.lcdoc
  docs/dictionary/function/revAppVersion.lcdoc
  docs/dictionary/function/revBrowserGet.lcdoc
  docs/dictionary/function/revBrowserInstances.lcdoc
  docs/dictionary/function/revXMLCreateTreeWithNamespaces.lcdoc
  docs/dictionary/function/revXMLDataFromXPathQuery.lcdoc
  docs/dictionary/function/revXMLEvaluateXPath.lcdoc
  docs/dictionary/message/QTDebugStr.lcdoc
  docs/dictionary/message/queryRecordChanged.lcdoc
  docs/dictionary/property/dragData.lcdoc
  docs/dictionary/property/hiliteColor.lcdoc
  docs/dictionary/property/printScale.lcdoc
  docs/dictionary/property/properties.lcdoc
  docs/dictionary/property/rawDragData.lcdoc
  docs/dictionary/property/recordFormat.lcdoc
  docs/dictionary/property/recordInput.lcdoc
  docs/dictionary/property/recursionLimit.lcdoc
  docs/dictionary/property/relayerGroupedControls.lcdoc
  docs/dictionary/property/resizable.lcdoc
  docs/dictionary/property/resizeQuality.lcdoc
  docs/dictionary/property/retainImage.lcdoc
  docs/dictionary/property/retainPostScript.lcdoc
  docs/glossary/r/ResEdit.lcdoc
  docs/notes/bugfix-21803.md
  docs/notes/bugfix-22192.md
  docs/notes/bugfix-22198.md
Labels: clean merge, vulcan/reviewed

#7092 [Dictionary] pan to preOpenControl
  docs/dictionary/command/pop.lcdoc
  docs/dictionary/command/popup-widget.lcdoc
  docs/dictionary/command/popup.lcdoc
  docs/dictionary/command/post.lcdoc
  docs/dictionary/function/param.lcdoc
  docs/dictionary/function/params.lcdoc
  docs/dictionary/message/playerProgressChanged.lcdoc
  docs/dictionary/message/preOpenControl.lcdoc
  docs/dictionary/property/pan.lcdoc
  docs/dictionary/property/penPattern.lcdoc
  docs/dictionary/property/pointerFocus.lcdoc
  docs/glossary/p/Pointer-tool.lcdoc
Labels: vulcan/reviewed

#7122 [Bugfix-22207] Fix garbled text in selectedObject
  docs/dictionary/function/selectedObject.lcdoc
  docs/notes/bugfix-22207.md
Labels: vulcan/reviewed

#7064 [Dictionary] mobilePickDate to movieTouched
  docs/dictionary/command/mobilePickDate.lcdoc
  docs/dictionary/command/mobileSetFullScreenRectForOrientations.lcdoc
  docs/dictionary/command/mobileSetLocationHistoryLimit.lcdoc
  docs/dictionary/function/mobileSensorReading.lcdoc
  docs/dictionary/function/mouseChunk.lcdoc
  docs/dictionary/function/mouseControl.lcdoc
  docs/dictionary/message/mouseDoubleDown.lcdoc
  docs/dictionary/message/mouseDoubleUp.lcdoc
  docs/dictionary/message/mouseUp.lcdoc
  docs/dictionary/message/mouseUpInBackdrop.lcdoc
  docs/dictionary/message/movieTouched.lcdoc
  docs/dictionary/property/HTMLText.lcdoc
  docs/dictionary/property/label.lcdoc
Labels: vulcan/reviewed

#7133 [9.5 rc2] Updated version
  version
Labels: vulcan/reviewed

#7132 [22261] Fix S/B error on Windows if Android Barcode widget is included
  docs/notes/bugfix-22261.md
  ide-support/revsaveasandroidstandalone.livecodescript
Labels: bug, vulcan/reviewed

#7135 [9.5.0] Updated version
  version
Labels: vulcan/reviewed
