Repository livecode/livecode, pull requests merged in 2019-03, with the labels that each got.

#6892 [21864] Ensure launch url can open a document on Android 6+
  docs/notes/bugfix-21864.md
  engine/src/java/com/runrev/android/Engine.java
Labels: bug, vulcan/reviewed

#6894 [21870] Ensure no folder "Linux" is created if only "Linux x64" is checked
  docs/notes/bugfix-21870.md
  ide-support/revsaveasstandalone.livecodescript
Labels: bug, vulcan/reviewed

#6884 [Dictionary] backgroundColor to charSet
  docs/dictionary/function/base64Encode.lcdoc
  docs/dictionary/function/binaryDecode.lcdoc
  docs/dictionary/keyword/binfile.lcdoc
  docs/dictionary/operator/less-than-or-equals.lcdoc
  docs/dictionary/property/backgroundColor.lcdoc
  docs/dictionary/property/backgroundPattern.lcdoc
  docs/dictionary/property/beepPitch.lcdoc
  docs/dictionary/property/bottomPattern.lcdoc
  docs/dictionary/property/caseSensitive.lcdoc
  docs/dictionary/property/charSet.lcdoc
  docs/glossary/c/CGI.lcdoc
  docs/glossary/c/character.lcdoc
Labels: vulcan/reviewed

#6891 Ensure HealthKit related plist entries are included only when necessary
  docs/notes/bugfix-21862.md
  engine/rsrc/mobile-device-template.plist
  engine/rsrc/mobile-template.plist
  ide-support/revsaveasiosstandalone.livecodescript
Labels: bug, vulcan/reviewed

#6317 [[ Bugfix 20951 ]] Fixed bug causing garbage at end of repeat to be ignored
  docs/notes/bugfix-20951.md
  engine/src/keywords.cpp
  extensions/script-libraries/drawing/drawing.livecodescript
  tests/lcs/parser/repeat.parsertest
Labels: LCS, bug, vulcan/reviewed

#6902 [21892] Include TimeZone code folder in iOS 12.1 Runtime
  Installer/package.txt
  docs/notes/bugfix-21892.md
Labels: bug, vulcan/reviewed

#6903 Ensure visual effect "scroll" does honor rect
  docs/notes/bugfix-21738.md
  docs/notes/bugfix-21869.md
  engine/src/stacke.cpp
Labels: bug, vulcan/reviewed

#6898 [Dictionary] child node to Database library
  docs/dictionary/command/click.lcdoc
  docs/dictionary/function/cipherNames.lcdoc
  docs/dictionary/function/clickCharChunk.lcdoc
  docs/dictionary/function/controlKey.lcdoc
  docs/dictionary/function/cos.lcdoc
  docs/dictionary/function/date.lcdoc
  docs/dictionary/property/colorMap.lcdoc
  docs/dictionary/property/coloroverlay.lcdoc
  docs/dictionary/property/constantMask.lcdoc
  docs/dictionary/property/constraints.lcdoc
  docs/dictionary/property/customKeys.lcdoc
  docs/dictionary/property/customProperties.lcdoc
  docs/glossary/c/Common-library.lcdoc
  docs/glossary/c/child-node.lcdoc
  docs/glossary/c/cursor.lcdoc
  docs/glossary/d/Database-library.lcdoc
Labels: vulcan/reviewed

#6907 Don't build for android armv6
  config.py
Labels: vulcan/reviewed

#6906 [Dictionary] decorations to exists
  docs/dictionary/command/delete.lcdoc
  docs/dictionary/command/disable-menu.lcdoc
  docs/dictionary/command/do-as-alternatelanguage.lcdoc
  docs/dictionary/command/enable-menu.lcdoc
  docs/dictionary/function/exists.lcdoc
  docs/dictionary/keyword/default.lcdoc
  docs/dictionary/keyword/else-if.lcdoc
  docs/dictionary/keyword/end-if.lcdoc
  docs/dictionary/message/deleteKey.lcdoc
  docs/dictionary/property/decorations.lcdoc
  docs/dictionary/property/disabled.lcdoc
  docs/dictionary/property/dragData.lcdoc
Labels: vulcan/reviewed

#6908 Merge release 9.0.3 18.03.2019
  Installer/package.txt
  docs/notes/bugfix-21738.md
  docs/notes/bugfix-21869.md
  docs/notes/bugfix-21892.md
  engine/src/stacke.cpp
Labels: vulcan/reviewed

#6909 Updated version [9.0.3]
  version
Labels: vulcan/reviewed

#6910 [[ Bug 21828 ]] Reduce time taken to compute minimum required file version for stack
  docs/notes/bugfix-21828.md
  engine/src/object.cpp
Labels: bug, vulcan/reviewed

#6913 [[ Bug 10881 ]] Fix Android openGL compositor surface height issue
  docs/notes/bugfix-10881.md
  engine/kernel.gyp
  engine/src/mblandroiddc.cpp
  engine/src/mbldc.h
  engine/src/mbliphonedc.mm
  engine/src/tilecachegl.cpp
Labels: bug, vulcan/reviewed

#6904 [[ Bug 21882 ]] Fix video view closing when player control is grouped / ungrouped
  docs/notes/bugfix-21882.md
  engine/src/player-platform.cpp
Labels: bug, vulcan/reviewed

#6794 [[ ByteOffset ]] Fixed bug causing incorrect results
  docs/notes/bugfix-byteoffset.md
  libfoundation/src/foundation-data.cpp
  tests/lcs/core/strings/byteoffset.livecodescript
Labels: bug, vulcan/reviewed

#6905 [21826] Ensure mobilePickPhoto works in all Android devices
  docs/notes/bugfix-21826.md
  engine/src/java/com/runrev/android/FileProvider.java
Labels: bug, vulcan/reviewed

#6911 [21900] Fix mobileComposeMail crashing iOS app when attachment has no name
  docs/notes/bugfix-21900.md
  engine/src/mbliphonemail.mm
Labels: bug, vulcan/reviewed

#6916 [[ Bug 21917 ]] Fix leak of NSEvent in core macOS event processing
  docs/notes/bugfix-21917.md
  engine/src/mac-core.mm
Labels: bug, vulcan/reviewed

#6917 [[ Bug 21918 ]] Memory leak when manipulating four-char-codes on macOS
  docs/notes/bugfix-21918.md
  engine/src/dskmac.cpp
Labels: bug, vulcan/reviewed

#6918 [[ Bug 21919 ]] Fix memory leak when deleting system font refs on macOS
  docs/notes/bugfix-21919.md
  engine/src/osxflst.cpp
Labels: bug, vulcan/reviewed

#6811 [[ Bug 21726 ]] Fix crash when using inf in math ops
  docs/notes/bugfix-21726.md
  engine/src/exec-math.cpp
  engine/src/operator.h
  tests/_testlib.livecodescript
  tests/lcs/core/math/infinity.livecodescript
Labels: bug, vulcan/reviewed

#6920 [[ Bug 21921 ]] Ensure MCGRegion destructor is called
  docs/notes/bugfix-21921.md
  libgraphics/src/region.cpp
Labels: bug, vulcan/reviewed

#6924 [[ Bug 21926 ]] Fix memory leak when using message box put command
  docs/notes/bugfix-21926.md
  engine/src/debug.cpp
Labels: bug, vulcan/reviewed

#6925 [[ Bug 21887 ]] Use auto classes to manage MCTextChunkIterator instances
  docs/notes/bugfix-21887.md
  engine/src/exec-keywords.cpp
  engine/src/exec-strings-chunk.cpp
  engine/src/exec-strings.cpp
  libscript/src/module-char.cpp
Labels: bug, vulcan/reviewed

#6921 [[ Bug 21923 ]] Fix memory leak when computing formattedWidth of buttons
  docs/notes/bugfix-21923.md
  engine/src/exec-interface-button.cpp
Labels: bug, vulcan/reviewed

#6919 [[ Bug 21920 ]] Fix leak of evaluated source value in filter command
  docs/notes/bugfix-21920.md
  engine/src/cmdsf.cpp
Labels: bug, vulcan/reviewed

#6895 [21871] Ensure no word "Standalone" is appended to the standalone name
  docs/notes/bugfix-21871.md
  ide-support/revsaveasstandalone.livecodescript
Labels: vulcan/reviewed

#6912 Prevent hang when opening the script of an edited group with cmd+alt+click
  docs/notes/bugfix-21819.md
  engine/src/stack2.cpp
Labels: bug, vulcan/reviewed

#6890 [[ Bug 21860 ]] Fix encoding of svg paths containing relative commands
  docs/notes/bugfix-21860.md
  extensions/script-libraries/drawing/drawing.livecodescript
Labels: bug, vulcan/reviewed

#6929 [[ Bug 21930 ]] Fix memory leak in use of GetVariableEx(UTF8) calls
  docs/notes/bugfix-21930.md
  engine/src/externalv0.cpp
Labels: bug, vulcan/reviewed

#6923 [[ Bug 21925 ]] Fix memory leak when using macOS Debug method
  docs/notes/bugfix-21925.md
  engine/src/dskmac.cpp
Labels: bug, vulcan/reviewed

#6922 [[ Bug 21924 ]] Fix memory leak when choosing item from macOS popup menu
  docs/notes/bugfix-21924.md
  engine/src/desktop-menu.cpp
Labels: bug, vulcan/reviewed

#6930 [[ Bug 21931 ]] Fix leak when executing send or call command
  docs/notes/bugfix-21931.md
  engine/src/exec-engine.cpp
Labels: bug, vulcan/reviewed

#6927 [[ Bug 21928 ]] Fix memory leak when using menu buttons
  docs/notes/bugfix-21928.md
  engine/src/button.cpp
  engine/src/stack.cpp
Labels: bug, vulcan/reviewed

#6900 [[ Bug 21933 ]] Add com.livecode.assert to list of builtin module names
  docs/notes/bugfix-21933.md
  extensions/script-libraries/extension-utils/extension-utils.livecodescript
Labels: bug, vulcan/reviewed

#6928 [[ Bug 21932 ]] Fix memory leak when executing sqlite queries
  docs/notes/bugfix-21932.md
Labels: bug, vulcan/reviewed

#6896 [21880] Prevent crash when restoring IAP but Google Billing Service is disconnected
  docs/notes/bugfix-21880.md
  engine/src/java/com/runrev/android/billing/google/IabHelper.java
Labels: bug, vulcan/reviewed

#6926 [[ Bug 21787 ]] Fix memory leak when implicitly deleting substacks
  docs/notes/bugfix-21787.md
  engine/src/dispatch.cpp
  engine/src/stack.cpp
Labels: bug, vulcan/reviewed

#6936 [21944] Added bugfix note
  docs/notes/bugfix-21944.md
Labels: vulcan/reviewed

#6935 Revert "[[ Bug 21928 ]] Fix memory leak when using menu buttons"
  docs/notes/bugfix-21928.md
  engine/src/button.cpp
  engine/src/stack.cpp
Labels: vulcan/reviewed
