Repository livecode/livecode, pull requests merged in 2019-12, with the labels that each got.

#7198 [22378] Ensure tolower() is used in unicode case fold
  docs/notes/bugfix-22378.md
  libfoundation/src/foundation-unicode.cpp
  tests/lcs/core/strings/sort.livecodescript
Labels: bug, vulcan/reviewed

#7226 [22457] Prevent crash when calling binarayDecode with wrong data input
  docs/notes/bugfix-22457.md
  engine/src/exec-filters.cpp
Labels: bug, vulcan/reviewed

#7233 [[ Bug 18655 ]] Make ScreenOrientationEventListener public
  engine/src/java/com/runrev/android/ScreenOrientationEventListener.java
Labels: vulcan/reviewed

#7236 [[ Bug 22498 ]] Fix compiling of rotate(<pAngle>) in SVG elements
  extensions/script-libraries/drawing/drawing.livecodescript
  extensions/script-libraries/drawing/notes/22498.md
Labels: LCS, bug, vulcan/reviewed

#7235 [[ Bug 22483 ]] Fix web view not resizing on iOS after reconfiguration
  docs/notes/bugfix-22483.md
  libbrowser/src/libbrowser_wkwebview.mm
Labels: LCS, bug, vulcan/reviewed

#7140 [[ Bug 22279 ]] Fix browser widget showing blank page after set htmltext
  docs/notes/bugfix-22279.md
  libbrowser/src/libbrowser_cef.cpp
Labels: bug, vulcan/reviewed

#7107 [22190] Ensure setting spaceAbove does not affect spaceBelow
  docs/notes/bugfix-22190.md
  engine/src/exec-interface-field-chunk.cpp
  tests/lcs/core/field/spaceAbove.livecodescript
Labels: bug, vulcan/reviewed

#7231 [[ Engine ]] Tweak passing of script text for parsing purposes
  engine/src/hndlrlst.cpp
  engine/src/hndlrlst.h
  engine/src/mcio.cpp
  engine/src/object.cpp
  engine/src/scriptpt.cpp
  engine/src/scriptpt.h
  engine/src/stack.cpp
  engine/src/stack.h
  engine/src/stacksecurity.cpp
  engine/src/stacksecurity.h
  libfoundation/include/foundation.h
  libfoundation/src/foundation-string.cpp
Labels: vulcan/reviewed

#7196 [[ Bug 22412 ]] Save tabAlign when tabStops is not set
  docs/notes/bugfix-22412.md
  engine/src/field.cpp
  tests/_testlib.livecodescript
  tests/lcs/core/field/line-properties.livecodescript
  tests/lcs/core/field/softkeyboardproperties.livecodescript
Labels: bug, vulcan/reviewed

#7237 [[ Bug 22499 ]] Don't recalculate scaled width & height if widget dimensions are unchanged
  extensions/widgets/svgpath/notes/feature-fewer-recalculations.md
  extensions/widgets/svgpath/svgpath.lcb
Labels: LCB, enhancement, vulcan/reviewed

#7130 [22241] Fix error when getting the android field's scrollingEnabled
  extensions/widgets/androidfield/androidfield.lcb
  extensions/widgets/androidfield/notes/22241.md
Labels: bug, vulcan/reviewed

#7239 [[ Bug 22497 ]] List object ref for protected stacks in execContexts
  docs/notes/bugfix-22497.md
  engine/src/exec-debugging.cpp
Labels: bug, vulcan/reviewed

#7238 [[ Bug 22213 ]] Implement detailed-utf8 files & folders
  docs/dictionary/function/files.lcdoc
  docs/dictionary/function/folders.lcdoc
  docs/notes/bugfix-22213.md
  engine/src/exec-files.cpp
  engine/src/exec.h
  engine/src/funcs.cpp
  engine/src/osspec.h
  engine/src/sysspec.cpp
  tests/lcs/core/files/folders.livecodescript
Labels: bug, vulcan/reviewed

#7179 [22388] Add support for merging activity attributes in manifest
  docs/notes/bugfix-22388.md
  ide-support/revsaveasandroidstandalone.livecodescript
Labels: vulcan/reviewed
