Repository livecode/livecode, pull requests merged in 2019-04, with the labels that each got.

#6914 [[ Bug 21915 ]] Fix memory leak in 'the processor'
  docs/notes/bugfix-21915.md
  engine/src/dskw32.cpp
  engine/src/exec-engine.cpp
  engine/src/osspec.h
  engine/src/srvwindows.cpp
  engine/src/sysspec.cpp
Labels: bug, vulcan/reviewed

#6939 Merge release 9.0.4 29.03.2019
  docs/notes/bugfix-21928.md
  docs/notes/bugfix-21944.md
  engine/src/button.cpp
  engine/src/stack.cpp
Labels: vulcan/reviewed

#6941 [9.0.5 rc1] Updated version
  version
Labels: vulcan/reviewed

#6933 [[ Bug 21964 ]] Fix MCWidget::hittest for invisible/disabled widgets
  docs/notes/bugfix-21945.md
  engine/src/widget.cpp
  tests/lcs/core/interface/controlatloc.livecodescript
Labels: bug, vulcan/reviewed

#6880 [[ Bug ]] Fix over-release crash in ListToNSArray
  libfoundation/src/foundation-cf.cpp
Labels: vulcan/reviewed

#6944 [[ Bug 21956 ]] Fix memory leak in repeat for each string chunk
  docs/notes/bugfix-21956.md
  engine/src/exec-keywords.cpp
Labels: bug, vulcan/reviewed

#6858 [[ lcidlc ]] Fix posting of LCBytes parameter using LCObjectPost
  lcidlc/src/Support.mm
Labels: vulcan/reviewed

#6943 [[ Bug 21955 ]] Fix diamond menu item mark on macOS
  docs/notes/bugfix-21955.md
  engine/src/mac-menu.mm
Labels: bug, vulcan/reviewed

#6948 [[ Bug 21958 ]] Fix buffer overrun when initializing MCrandomseed
  docs/notes/bugfix-21958.md
  engine/src/mcssl.cpp
Labels: bug, vulcan/reviewed

#6949 [[ Bug 21928 ]] Fix memory leak when using menu buttons
  docs/notes/bugfix-21928.md
  engine/src/button.cpp
  engine/src/stack.cpp
Labels: bug, vulcan/reviewed

#6950 [[ Bug 21959 ]] Fix memory leak when using clipboard functions
  docs/notes/bugfix-21959.md
  engine/src/clipboard.cpp
  engine/src/exec-pasteboard.cpp
  engine/src/lnx-clipboard.cpp
  engine/src/mac-clipboard.mm
  engine/src/raw-clipboard.cpp
  engine/src/w32-clipboard.cpp
Labels: bug, vulcan/reviewed

#6952 [[ Bug 21960 ]] Ensure private handler lookups are cached
  docs/notes/bugfix-21960.md
  engine/src/exec-keywords.cpp
  engine/src/exec.h
  engine/src/express.cpp
  engine/src/statemnt.cpp
Labels: bug, vulcan/reviewed

#6940 Merge develop 9.0 01.04.2019
  docs/notes/bugfix-21928.md
  docs/notes/bugfix-21944.md
  engine/src/button.cpp
  engine/src/stack.cpp
Labels: vulcan/reviewed

#6958 [[ Bug 21984 ]] Fix android accelrendering startup issue
  docs/notes/bugfix-21984.md
  engine/src/mblandroiddc.cpp
Labels: bug, vulcan/reviewed

#6959 [[ Prebuilt ]] Exclude armv6 binaries when fetching Android prebuilt libraries
  prebuilt/fetch-libraries.sh
  prebuilt/fetch.gyp
Labels: blocker, bug, vulcan/reviewed

#6534 [[ bugfix-20121 ]] Update the iconpicker to allow filtering
  extensions/widgets/iconpicker/iconpicker.lcb
Labels: vulcan/reviewed

#6483 [[ Bug 21156 ]] videoClip not deprecated in dictionary
  docs/dictionary/object/videoClip.lcdoc
  docs/notes/bugfix-21156.md
Labels: vulcan/reviewed

#6771 [[ Bug 17315 ]] Update the `delete variable` entry
  docs/dictionary/command/delete-variable.lcdoc
  docs/notes/bugfix-17315.md
Labels: bug, vulcan/reviewed

#6764 [[ Bug 21659 ]] Update TreeView to ignore mouseUp when row has changed
  extensions/widgets/treeview/notes/21361.md
  extensions/widgets/treeview/notes/21659.md
  extensions/widgets/treeview/notes/feature-auto_expand.md
  extensions/widgets/treeview/treeview.lcb
Labels: vulcan/reviewed

#6770 [[ TreeView ]] Get/Set Fold State
  extensions/widgets/treeview/notes/feature-fold_state.md
  extensions/widgets/treeview/treeview.lcb
Labels: vulcan/reviewed

#6957 [Dictionary] kill to lock menus
  docs/dictionary/command/kill.lcdoc
  docs/dictionary/command/launch-document.lcdoc
  docs/dictionary/command/launch.lcdoc
  docs/dictionary/command/libURLSetCustomHTTPHeaders.lcdoc
  docs/dictionary/command/libURLftpUpload.lcdoc
  docs/dictionary/command/libURLftpUploadFile.lcdoc
  docs/dictionary/command/load-extension.lcdoc
  docs/dictionary/command/load.lcdoc
  docs/dictionary/command/lock-menus.lcdoc
  docs/dictionary/function/libUrlFormData.lcdoc
  docs/dictionary/property/layer.lcdoc
  docs/dictionary/property/layerMode.lcdoc
  docs/dictionary/property/listBehavior.lcdoc
  docs/glossary/l/library.lcdoc
Labels: vulcan/reviewed

#6964 [[ Bug 21988 ]] Fix memory leaks in clipboard functions
  docs/notes/bugfix-21988.md
  engine/src/clipboard.cpp
Labels: bug, vulcan/reviewed

#6963 [[ Bug 21987 ]] Fix pasteboard leak on macOS
  docs/notes/bugfix-21987.md
  engine/src/mac-clipboard.h
  engine/src/mac-clipboard.mm
Labels: bug, vulcan/reviewed

#6967 [[ Bug 21991 ]] Ensure external library modules are unloaded
  docs/notes/bugfix-21991.md
  engine/src/external.cpp
Labels: bug, vulcan/reviewed

#6965 [[ Bug 21989 ]] Fix benign leak of apple events on startup on macOS
  docs/notes/bugfix-21989.md
  engine/src/mac-core.mm
  engine/src/mac-internal.h
Labels: bug, vulcan/reviewed

#6962 [[ Bug 21986 ]] Fix benign leak of backdrop window on macOS
  docs/notes/bugfix-21986.md
  engine/src/desktop-dc.cpp
Labels: bug, vulcan/reviewed

#6966 [[ Bug 21990 ]] Fix memory leak when destroying windows on macOS
  docs/notes/bugfix-21990.md
  engine/src/platform-window.cpp
Labels: bug, vulcan/reviewed

#6971 [[ Bug 21995 ]] Fix memory leaks when using sockets
  docs/notes/bugfix-21995.md
  engine/src/opensslsocket.cpp
  engine/src/socket_resolve.cpp
Labels: bug, vulcan/reviewed

#6975 [[ Bug 21999 ]] Fix memory leak when converting strings to numbers
  docs/notes/bugfix-21999.md
  engine/src/exec.cpp
Labels: bug, vulcan/reviewed

#6979 [[ Bug 22003 ]] Fix memory leaks when fetching revScriptDescription
  docs/notes/bugfix-22003.md
  engine/src/exec-interface-object.cpp
Labels: bug, vulcan/reviewed

#6982 [[ Bug 22006 ]] Fix memory leaks when using player on macOS
  docs/notes/bugfix-22006.md
  engine/src/mac-av-player.mm
Labels: bug, vulcan/reviewed

#6988 [[ Bug 22012 ]] Fix memory leak when using LCB's log command
  docs/notes/bugfix-22012.md
  engine/src/eventqueue.cpp
Labels: bug, vulcan/reviewed

#6989 [[ Bug 22013 ]] Fix memory leak when using LCB's send/post/execute
  docs/notes/bugfix-22013.md
  engine/src/module-engine.cpp
Labels: bug, vulcan/reviewed

#6991 [[ Bug 22016 ]] Fix memory leak when setting widget properties
  docs/notes/bugfix-22016.md
  engine/src/widget.cpp
Labels: bug, vulcan/reviewed

#6983 [[ Bug 22007 ]] Fix memory leaks when using menus on macOS
  docs/notes/bugfix-22007.md
  engine/src/mac-menu.mm
Labels: bug, vulcan/reviewed

#6977 [[ Bug 22001 ]] Fix memory leak when using import eps
  docs/notes/bugfix-22001.md
  engine/src/exec-legacy.cpp
Labels: bug, vulcan/reviewed

#6974 [[ Bug 21998 ]] Use name values for variable initializers
  docs/notes/bugfix-21998.md
  engine/src/keywords.cpp
Labels: enhancement, vulcan/reviewed

#6972 [[ Bug 21996 ]] Fix memory leak when using filter elements of
  docs/notes/bugfix-21996.md
  engine/src/patternmatcher.cpp
Labels: bug, vulcan/reviewed

#6970 [[ Bug 21994 ]] Fix memory leak in arrayDecode (7.0 format)
  docs/notes/bugfix-21994.md
  engine/src/exec-array.cpp
Labels: bug, vulcan/reviewed

#6981 [[ Bug 22005 ]] Fix memory leaks when using browser widget
  docs/notes/bugfix-22005.md
  libbrowser/src/libbrowser.cpp
  libbrowser/src/libbrowser_cef.cpp
  libbrowser/src/libbrowser_internal.h
  libbrowser/src/libbrowser_osx_webview.mm
  libbrowser/src/libbrowser_uiwebview.mm
Labels: bug, vulcan/reviewed

#6968 [[ Bug 21992 ]] Fix memory leaks when sorting using MCSortnodes
  docs/notes/bugfix-21992.md
  engine/src/exec-strings.cpp
  engine/src/fields.cpp
  engine/src/sellst.cpp
  engine/src/stack3.cpp
  libfoundation/include/foundation-auto.h
Labels: bug, vulcan/reviewed

#6990 [[ Bug 22015 ]] Fix memory leak when bridging foreign values
  docs/notes/bugfix-22015.md
  engine/src/exec-extension.cpp
Labels: bug, vulcan/reviewed

#6994 [TreeView Widget] Set hilited item to empty fix
  extensions/widgets/treeview/treeview.lcb
Labels: vulcan/reviewed

#6978 [[ Bug 22002 ]] Fix memory leak when setting numberFormat
  docs/notes/bugfix-22002.md
  engine/src/util.cpp
Labels: bug, vulcan/reviewed

#6986 [[ Bug 22010 ]] Fix memory leak when binding LCB foreign handlers
  docs/notes/bugfix-22010.md
  libscript/include/libscript/script.h
  libscript/src/script-instance.cpp
  libscript/src/script-module.cpp
  libscript/src/script-private.h
Labels: bug, vulcan/reviewed

#6985 [[ Bug 22009 ]] Fix memory leak when releasing LCB objects
  docs/notes/bugfix-22009.md
  libfoundation/src/foundation-pickle.cpp
  libscript/src/script-object.cpp
Labels: bug, vulcan/reviewed

#6987 [[ Bug 22011 ]] Fix memory leak when using LCB's char iterator
  docs/notes/bugfix-22011.md
  libscript/src/module-char.cpp
  tests/lcb/stdlib/char.lcb
Labels: bug, vulcan/reviewed

#6993 [[ Bug 22019 ]] Fix several memory leaks in the field object
  docs/notes/bugfix-22019.md
  engine/src/exec-interface-field-chunk.cpp
  engine/src/field.cpp
  engine/src/fieldhtml.cpp
  engine/src/fieldstyledtext.cpp
  tests/lcs/core/field/line-properties.livecodescript
  tests/lcs/core/field/styledText.livecodescript
Labels: bug, vulcan/reviewed

#6980 [[ Bug 22004 ]] Fix memory leak when configuring syntax highlighting
  docs/notes/bugfix-22004.md
  engine/src/ide.cpp
Labels: bug, vulcan/reviewed

#6976 [[ Bug 22000 ]] Fix memory leak when parsing save with format
  docs/notes/bugfix-22000.md
  engine/src/cmdss.cpp
Labels: bug, vulcan/reviewed

#6973 [[ Bug 21997 ]] Fix memory leak in MCStringSplitByDelimiter
  docs/notes/bugfix-21997.md
  libfoundation/src/foundation-string.cpp
Labels: bug, vulcan/reviewed

#6954 [[ Bug 16947 ]] Fix memory leak when making recursive calls with refs
  docs/notes/bugfix-16947.md
  engine/src/cmds.h
  engine/src/cmdse.cpp
  engine/src/exec-engine.cpp
  engine/src/exec-extension.cpp
  engine/src/exec-keywords.cpp
  engine/src/exec.cpp
  engine/src/exec.h
  engine/src/express.cpp
  engine/src/express.h
  engine/src/handler.cpp
  engine/src/ide.cpp
  engine/src/keywords.cpp
  engine/src/keywords.h
  engine/src/object.cpp
  engine/src/param.cpp
  engine/src/param.h
  engine/src/statemnt.cpp
  engine/src/statemnt.h
  tests/lcs/core/control/recursion.livecodescript
Labels: bug, vulcan/reviewed

#6984 [[ Bug 22008 ]] Fix memory leak when parsing menu strings
  docs/notes/bugfix-22008.md
  engine/src/menuparse.cpp
Labels: bug, vulcan/reviewed

#6969 [[ Bug 21993 ]] Tweak __MCName and __MCString layouts
  docs/notes/bugfix-21993.md
  libfoundation/src/foundation-private.h
  libfoundation/test/test_memory.cpp
Labels: bug, vulcan/reviewed

#6995 [[ Bug 22020 ]] Fix memory leak when dbsqlite connection fails
  docs/notes/bugfix-22020.md
Labels: bug

#6992 [[ Bug 22017 ]] Fix memory leak when updating listBehavior fields
  docs/notes/bugfix-22017.md
  engine/src/field.h
  engine/src/fieldf.cpp
  engine/src/fields.cpp
  tests/lcs/core/field/listBehavior.livecodescript
Labels: bug, vulcan/reviewed

#6956 [Dictionary] hotspotClicked to keyword
  docs/dictionary/command/import.lcdoc
  docs/dictionary/command/iphoneSetAudioCategory.lcdoc
  docs/dictionary/command/iphoneSetRedrawInterval.lcdoc
  docs/dictionary/command/iphoneSetRemoteControlDisplay.lcdoc
  docs/dictionary/control_st/if.lcdoc
  docs/dictionary/function/iphoneDoNotBackupFile.lcdoc
  docs/dictionary/keyword/http.lcdoc
  docs/dictionary/keyword/https.lcdoc
  docs/dictionary/message/hotspotClicked.lcdoc
  docs/dictionary/message/keyDown.lcdoc
  docs/dictionary/property/ink.lcdoc
  docs/glossary/k/keyword.lcdoc
Labels: vulcan/reviewed

#6961 long to mobileGetLocationHistoryLimit
  docs/dictionary/command/mobileBusyIndicatorStop.lcdoc
  docs/dictionary/command/mobileCancelLocalNotification.lcdoc
  docs/dictionary/function/md5Digest.lcdoc
  docs/dictionary/function/mobileCanSendMail.lcdoc
  docs/dictionary/function/mobileCurrentHeading.lcdoc
  docs/dictionary/function/mobileCurrentLocation.lcdoc
  docs/dictionary/function/mobileGetLocationHistoryLimit.lcdoc
  docs/dictionary/keyword/long.lcdoc
  docs/dictionary/message/menuKey.lcdoc
  docs/dictionary/message/menuPick.lcdoc
  docs/dictionary/property/lookAndFeel.lcdoc
  docs/dictionary/property/magnify.lcdoc
  docs/dictionary/property/margins.lcdoc
  docs/dictionary/property/markerDrawn.lcdoc
  docs/dictionary/property/mnemonic.lcdoc
Labels: vulcan/reviewed

#6945 [Dictionary] export snapshot to go
  docs/dictionary/command/export-snapshot.lcdoc
  docs/dictionary/command/go.lcdoc
  docs/dictionary/function/folders.lcdoc
  docs/dictionary/function/fontNames.lcdoc
  docs/dictionary/function/getResources.lcdoc
  docs/dictionary/keyword/fifth.lcdoc
  docs/dictionary/keyword/from.lcdoc
  docs/dictionary/property/focusColor.lcdoc
  docs/dictionary/property/foregroundPattern.lcdoc
  docs/dictionary/property/fullDragData.lcdoc
  docs/dictionary/property/fullscreen.lcdoc
Labels: vulcan/reviewed

#6937 [Bugfix 20022] Change external link to Apple Event documentation.
  docs/dictionary/command/request-appleEvent.lcdoc
  docs/dictionary/message/appleEvent.lcdoc
  docs/notes/bugfix-20022.md
Labels: vulcan/reviewed

#6947 [Dictionary] grab to hilitePattern
  docs/dictionary/command/grab.lcdoc
  docs/dictionary/command/hide.lcdoc
  docs/dictionary/constant/hand.lcdoc
  docs/dictionary/keyword/gRevProfileReadOnly.lcdoc
  docs/dictionary/object/group.lcdoc
  docs/dictionary/property/HCAddressing.lcdoc
  docs/dictionary/property/hidden.lcdoc
  docs/dictionary/property/hilite.lcdoc
  docs/dictionary/property/hiliteBorder.lcdoc
  docs/dictionary/property/hiliteColor.lcdoc
  docs/dictionary/property/hiliteFill.lcdoc
  docs/dictionary/property/hilitePattern.lcdoc
  docs/dictionary/property/hilitedButtonName.lcdoc
  docs/dictionary/property/hilitedLine.lcdoc
Labels: vulcan/reviewed

#6915 [[ Bug 21916 ]] Fix memory leak when using printing on macOS
  docs/notes/bugfix-21916.md
  engine/src/osxprinter.cpp
Labels: bug, vulcan/reviewed

#7000 [9.0.4 rc3] Updated version
  version
Labels: vulcan/reviewed

#6953 [[ Prebuilt ]] Build Linux prebuilt libraries with position-independant code
  config/linux-settings.gypi
  prebuilt/scripts/build-curl.bat
  prebuilt/scripts/platform.inc
  prebuilt/versions/curl_buildrevision
  prebuilt/versions/icu_buildrevision
  prebuilt/versions/openssl_buildrevision
Labels: enhancement, vulcan/reviewed

#6960 [[ Foundation ]] Index name tests
  libfoundation/libfoundation.gyp
  libfoundation/test/test_hash.cpp
  libfoundation/test/test_name.cpp
Labels: vulcan/reviewed

#7001 [[ Bug 22024 ]] Fix LCB's 'is among the elements of' operator
  docs/notes/bugfix-22024.md
  libfoundation/src/foundation-array.cpp
  tests/lcb/stdlib/array.lcb
Labels: LCB, bug, vulcan/reviewed

#7002 [[ Prebuilt ]] Update platform tools version to 14.1
  prebuilt/build-all-libs.bat
  prebuilt/build-libs.bat
  prebuilt/fetch-libraries.sh
Labels: enhancement, vulcan/reviewed
