Repository livecode/livecode, pull requests merged in 2019-09, with the labels that each got.

#7158 [9.5.1 RC 1] Updated version
  version
Labels: vulcan/reviewed

#7160 [Bugfix-21978] Add tsNet/libUrl conflict warning to urlProgress
  docs/dictionary/message/urlProgress.lcdoc
  docs/notes/bugfix-21978.md
Labels: vulcan/reviewed

#7153 [Bugfix-19660] Add note about when card numbers are displayed in title bar
  docs/dictionary/property/label.lcdoc
  docs/notes/bugfix-19660.md
Labels: vulcan/reviewed

#7152 [Bugfix-19631] Note in docs that mobile player controller requires correct filename to display
  docs/dictionary/command/mobileControlCreate.lcdoc
  docs/dictionary/command/mobileControlSet.lcdoc
  docs/notes/bugfix-19631.md
Labels: vulcan/reviewed

#7150 [Bugfix-22341] Add note about non-ASCII chars to URLDecode entry
  docs/dictionary/function/URLDecode.lcdoc
  docs/notes/bugfix-22341.md
Labels: vulcan/reviewed

#7149 [Bugfix-22340] Add note about non-ASCII chars to URLEncode entry
  docs/dictionary/function/URLEncode.lcdoc
  docs/notes/bugfix-22340.md
Labels: vulcan/reviewed

#7163 [Bugfix-20314] Added r,g,b color definitions in HTMLText entry
  docs/dictionary/property/HTMLText.lcdoc
  docs/notes/bugfix-20314.md
Labels: vulcan/reviewed

#7162 [Bugfix-20303] Add variable example to URL entry
  docs/dictionary/keyword/URL.lcdoc
  docs/notes/bugfix-20303.md
Labels: vulcan/reviewed

#7155 [[ Bug 22256 ]] Use correct user info key to obtain keyboard size
  docs/notes/bugfix-22256.md
  engine/src/mbliphoneapp.mm
Labels: bug, vulcan/reviewed

#7144 [[ Bug 22322 ]] Fix graphical artefacts after removing focus from a group on mobile
  docs/notes/bugfix-22322.md
  engine/src/group.cpp
  engine/src/group.h
Labels: bug, vulcan/reviewed

#7143 [Dictionary] scriptExecutionError to show
  docs/dictionary/command/request.lcdoc
  docs/dictionary/command/send.lcdoc
  docs/dictionary/command/show.lcdoc
  docs/dictionary/keyword/second.lcdoc
  docs/dictionary/keyword/segment.lcdoc
  docs/dictionary/keyword/segments.lcdoc
  docs/dictionary/message/scriptExecutionError.lcdoc
  docs/dictionary/message/searchKey.lcdoc
  docs/dictionary/property/sessionLifetime.lcdoc
  docs/dictionary/property/shadowPattern.lcdoc
Labels: vulcan/reviewed

#7141 [22308] Ensure Search for Inclusions works if script is unlocked
  docs/notes/bugfix-22308.md
  ide-support/revsblibrary.livecodescript
Labels: vulcan/reviewed

#7165 Added support for building with Xcode 11 / iOS 13.0 SDK
  Installer/package.txt
  Makefile
  config.py
  docs/notes-base/platforms.md
  ide-support/revdeploylibraryios.livecodescript
  prebuilt/fetch-libraries.sh
  prebuilt/scripts/ios.inc
  tools/setup_xcode_sdks.py
Labels: vulcan/reviewed

#7174 [Bugfix-21111] Add docs note about accelerometer differences
  docs/dictionary/message/accelerationChanged.lcdoc
  docs/notes/bugfix-21111.md
Labels: vulcan/reviewed

#7172 [Bugfix-22380] Correct documented cursorMovement mechanisms
  docs/dictionary/property/cursorMovement.lcdoc
  docs/notes/bugfix-22380.md
Labels: vulcan/reviewed

#7171 [Bugfix-19495] Describe potential use of out-of-range values in dateItems
  docs/dictionary/keyword/dateItems.lcdoc
  docs/notes/bugfix-19495.md
Labels: vulcan/reviewed

#7176 Merge develop 9.5 23.09.2019
  Installer/package.txt
  Makefile
  config.py
  docs/dictionary/keyword/dateItems.lcdoc
  docs/dictionary/message/accelerationChanged.lcdoc
  docs/dictionary/property/cursorMovement.lcdoc
  docs/notes-base/platforms.md
  docs/notes/bugfix-19495.md
  docs/notes/bugfix-21111.md
  docs/notes/bugfix-22380.md
  ide-support/revdeploylibraryios.livecodescript
  prebuilt/fetch-libraries.sh
  prebuilt/scripts/ios.inc
  tools/setup_xcode_sdks.py
Labels: clean merge, vulcan/reviewed

#7177 Merge develop 9.5 23.09.2019
  builder/builder_utilities.livecodescript
Labels: vulcan/reviewed

#7178 Added support for building with Xcode 11.1 / iOS 13.1 SDK
  Installer/package.txt
  Makefile
  config.py
  docs/notes-base/platforms.md
  ide-support/revdeploylibraryios.livecodescript
  prebuilt/fetch-libraries.sh
  prebuilt/scripts/ios.inc
  tools/setup_xcode_sdks.py
Labels: vulcan/reviewed

#7180 Merge develop 9.5 26.09.2019
  Installer/package.txt
  Makefile
  config.py
  docs/notes-base/platforms.md
  ide-support/revdeploylibraryios.livecodescript
  prebuilt/fetch-libraries.sh
  prebuilt/scripts/ios.inc
  tools/setup_xcode_sdks.py
Labels: clean merge, vulcan/reviewed

#7170 [Bugfix-19377] Edit version comparison example to work beyond LC 9
  docs/dictionary/function/version.lcdoc
  docs/notes/bugfix-19377.md
Labels: vulcan/reviewed

#7151 [Bugfix-21822] drawingSvgCompileFile() can't read from Android resources folder
  extensions/script-libraries/drawing/drawing.livecodescript
  extensions/script-libraries/drawing/notes/21822.md
Labels: vulcan/reviewed
