Repository livecode/livecode, pull requests merged in 2019-10, with the labels that each got.

#7182 Merge develop 9.5 27.09.2019
  Installer/package.txt
  docs/dictionary/function/version.lcdoc
  docs/dictionary/message/playStopped.lcdoc
  docs/notes/bugfix-19377.md
  docs/notes/bugfix-19892.md
  extensions/script-libraries/drawing/drawing.livecodescript
  extensions/script-libraries/drawing/notes/21822.md
Labels: vulcan/reviewed

#7185 [[ Bug 22130 ]] Disable deleted object pool creation whilst debugging
  docs/notes/bugfix-22130.md
  engine/src/debug.cpp
  engine/src/object.cpp
  engine/src/object.h
Labels: bug, vulcan/reviewed

#7186 Merge release 9.0.5 7.10.2019
  docs/notes/bugfix-22130.md
  engine/src/debug.cpp
  engine/src/object.cpp
  engine/src/object.h
Labels: clean merge, vulcan/reviewed

#7187 Merge develop 9.0 07.10.2019
  docs/notes/bugfix-22130.md
  engine/src/debug.cpp
  engine/src/object.cpp
  engine/src/object.h
Labels: vulcan/reviewed

#7189 Merge develop 9.5 09.10.2019
  docs/notes/bugfix-22130.md
  engine/src/debug.cpp
  engine/src/object.cpp
  engine/src/object.h
Labels: clean merge, vulcan/reviewed

#7145 [Dictionary] showController to tabGroupBehaviour
  docs/dictionary/command/start-session.lcdoc
  docs/dictionary/property/showController.lcdoc
  docs/dictionary/property/startAngle.lcdoc
  docs/dictionary/property/strokeGradient.lcdoc
  docs/dictionary/property/styledText.lcdoc
  docs/dictionary/property/tabGroupBehavior.lcdoc
  docs/glossary/s/SOAP.lcdoc
  docs/glossary/s/stack-version.lcdoc
Labels: vulcan/reviewed

#7199 [Bugfix-20472] Add missing info to fullClipboardData docs
  docs/dictionary/property/fullClipboardData.lcdoc
  docs/notes/Bugfix-20472.md
Labels: vulcan/reviewed

#7200 [Bugfix-15645] Generally correct controlAtScreenLoc
  docs/dictionary/function/controlAtLoc.lcdoc
  docs/dictionary/function/controlAtScreenLoc.lcdoc
  docs/notes/bugfix-15645.md
Labels: vulcan/reviewed

#7204 [[ tsNet ]] Update pointer
  builder/builder_utilities.livecodescript
Labels: vulcan/reviewed
