Repository livecode/livecode, pull requests merged in 2019-06, with the labels that each got.

#7070 [[ Cleanup ]] Ensure extensionOrderByDependency does not return builtins
  extensions/script-libraries/extension-utils/extension-utils.livecodescript
  ide-support/revsblibrary.livecodescript
Labels: cleanup, vulcan/reviewed

#7081 [[ Bug 22117 ]] Check for failure to find folder
  docs/notes/bugfix-22117.md
  engine/src/dskw32.cpp
  tests/lcs/core/files/folders.livecodescript
Labels: bug, vulcan/reviewed

#7082 [[ Build ]] Don't rebuild thirdparty libs
  engine/kernel-development.gyp
  engine/kernel-installer.gyp
  engine/kernel-server.gyp
  engine/kernel.gyp
  libfoundation/libfoundation.gyp
  libgraphics/libgraphics.gyp
  libscript/libscript.gyp
  prebuilt/thirdparty.gyp
  revdb/revdb.gyp
  revpdfprinter/revpdfprinter.gyp
  revxml/revxml.gyp
  revzip/revzip.gyp
  toolchain/lc-compile-ffi-java/lc-compile-ffi-java.gyp
  toolchain/lc-compile/lc-compile.gyp
  toolchain/lc-compile/lc-run.gyp
  toolchain/lc-compile/src/lc-compile-lib.gyp
  toolchain/libcompile/libcompile.gyp
Labels: vulcan/reviewed

#7075 [[ Bug ]] Fix use of execute script with explicitVars
  extensions/widgets/treeview/treeview.lcb
Labels: bug, vulcan/reviewed

#7061 [22088] Ensure default device theme is used on Android datePicker
  docs/notes/bugfix-22088.md
  engine/src/java/com/runrev/android/DialogModule.java
Labels: vulcan/reviewed

#7032 [[ Prebuilt ]] Ensure linux thirdparty libs are prebuilt with position-independent code
  config/linux-settings.gypi
  prebuilt/scripts/lib_versions.bat
  prebuilt/versions/thirdparty_buildrevision
Labels: bug, vulcan/reviewed

#7048 [[ Widget ]] Add `this widget` and `trigger all in <widget>` syntax
  docs/lcb/notes/feature-widget_reference.md
  engine/src/widget-syntax.cpp
  engine/src/widget.lcb
Labels: LCB, enhancement, vulcan/reviewed

#7083 [[ Bug 22142 ]] Add x86_64 to as possible value of the machine on win
  docs/dictionary/function/machine.lcdoc
  docs/notes/bugfix-22142.md
Labels: bug, vulcan/reviewed

#7084 [[ Build ]] Fix fetch step arch parameter
  fetch.py
Labels: vulcan/reviewed

#7086 [22136] Show appropriate message when standalone building is canceled
  docs/notes/bugfix-22136.md
  ide-support/revsaveasstandalone.livecodescript
Labels: bug, vulcan/reviewed

#7088 [21673] Ensure the Mac autoupdater is 64-bit
  builder/tools_builder.livecodescript
  docs/notes/bugfix-21673.md
Labels: bug, vulcan/reviewed

#7079 [[ Bug 22121 ]] Implement delete undo for widgets
  docs/notes/bugfix-22121.md
  engine/src/control.cpp
  engine/src/sellst.cpp
  engine/src/widget.cpp
  engine/src/widget.h
  tests/lcs/core/engine/widget.livecodescript
Labels: bug, vulcan/reviewed

#7019 [[ CEF ]] Update CEF to 74.1.16+ge20b240+chromium-74.0.3729.131
  libbrowser/libbrowser.gyp
  libbrowser/src/libbrowser_cef.cpp
  libbrowser/src/libbrowser_cefprocess.cpp
  prebuilt/libcef.gyp
  prebuilt/scripts/build-cef.bat
  prebuilt/scripts/build-cef.sh
  prebuilt/scripts/lib_versions.bat
  prebuilt/scripts/lib_versions.inc
  prebuilt/versions/cef
  prebuilt/versions/cef_buildrevision
  prebuilt/versions/cefchromium
  prebuilts-buildbot.py
  revbrowser/src/cefbrowser.cpp
  revbrowser/src/cefprocess.cpp
Labels: vulcan/reviewed

#7091 [[ CEF ]] Remove d3dcompiler_43.dll
  Installer/package.txt
Labels: bug, vulcan/reviewed

#7093 Ensure we use "x86-64" for 64bit autoupdater
  builder/tools_builder.livecodescript
Labels: blocker, bug, vulcan/reviewed

#7103 [[ Bug ]] Fix macOS 64 bit installer
  engine/src/mode_installer.cpp
Labels: bug, vulcan/reviewed

#7104 [[Bug 22182]] Add support for `Apple Development:` certificates
  docs/notes/bugfix-22182.md
  ide-support/revsaveasiosstandalone.livecodescript
Labels: enhancement, vulcan/reviewed

#7099 [[ CEF ]] Fixes for linux with current CEF version
  Installer/package.txt
  engine/src/globals.cpp
  ide-support/revsaveasstandalone.livecodescript
  libbrowser/libbrowser.gyp
  libbrowser/src/libbrowser_cef.cpp
  prebuilt/libcef.gyp
Labels: bug, vulcan/reviewed

#7111 [[ Android API 28 ]] Update to use android API 28
  config.py
  config/android.gypi
  docs/development/build-android.md
  prebuilt/fetch-libraries.sh
  prebuilt/scripts/android.inc
Labels: vulcan/reviewed

#7113 [Bugfix 22198] Fix missing text in hiliteColor
  docs/dictionary/property/hiliteColor.lcdoc
  docs/notes/bugfix-22198.md
Labels: vulcan/reviewed

#7112 [[ Android ]] Ensure end-user apps build against sdk api 28
  docs/notes/bugfix-22194.md
  engine/rsrc/android-manifest.xml
  ide-support/revdeploylibraryandroid.livecodescript
  ide-support/revsaveasandroidstandalone.livecodescript
Labels: vulcan/reviewed

#7117 [Docs] Intersect function. Remove glossary reference from Syntax example
  docs/dictionary/function/intersect.lcdoc
Labels: vulcan/reviewed

#7110 [[ Bug 22097 ]] Docs: effective rect of stack docs should mention need for the stack to have been opened
  docs/dictionary/property/rectangle.lcdoc
  docs/notes/bugfix-22097.md
Labels: vulcan/reviewed

#7109 [[ Bug 22192 ]] Mention using textEncode/textDecode with the dragData["private"]
  docs/dictionary/property/dragData.lcdoc
  docs/notes/bugfix-22192.md
Labels: vulcan/reviewed

#7115 [Dictionary] print link to recordInput
  docs/dictionary/command/print-link.lcdoc
  docs/dictionary/command/put.lcdoc
  docs/dictionary/function/recordCompressionTypes.lcdoc
  docs/dictionary/message/QTDebugStr.lcdoc
  docs/dictionary/message/queryRecordChanged.lcdoc
  docs/dictionary/property/printScale.lcdoc
  docs/dictionary/property/properties.lcdoc
  docs/dictionary/property/rawDragData.lcdoc
  docs/dictionary/property/recordFormat.lcdoc
  docs/dictionary/property/recordInput.lcdoc
  docs/dictionary/property/recursionLimit.lcdoc
Labels: vulcan/reviewed
