Repository livecode/livecode, pull requests merged in 2019-01, with the labels that each got.

#6797 [[ Bug 21705 ]] Fixed offset bugs
  engine/src/exec-strings.cpp
  tests/lcs/core/strings/offset.livecodescript
Labels: bug, vulcan/reviewed

#6837 [Bugfix 21770] Fix reference errors in URL entry
  docs/dictionary/keyword/URL.lcdoc
  docs/notes/bugfix-21770.md
Labels: vulcan/reviewed

#6839 [Bugfix-15176] Remove inaccuracies from revDeleteFolder entry
  docs/dictionary/command/revDeleteFolder.lcdoc
  docs/notes/bugfix-15176.md
Labels: vulcan/reviewed

#6834 Fix "Print All Cards from TL to BR" printing an empty page
  docs/notes/bugfix-18919.md
  engine/src/exec-printing.cpp
Labels: bug, vulcan/reviewed

#6842 Ensure Mac standalones have correct folder structure when built on Windows
  docs/notes/bugfix-21772.md
  ide-support/revsaveasstandalone.livecodescript
Labels: bug, vulcan/reviewed

#6841 [Dictionary] showFocusBorder to startFrame
  docs/dictionary/command/sort.lcdoc
  docs/dictionary/command/start-editing.lcdoc
  docs/dictionary/command/start-session.lcdoc
  docs/dictionary/function/sin.lcdoc
  docs/dictionary/keyword/sixth.lcdoc
  docs/dictionary/property/showFocusBorder.lcdoc
  docs/dictionary/property/size.lcdoc
  docs/dictionary/property/socketTimeoutInterval.lcdoc
  docs/dictionary/property/spray.lcdoc
  docs/dictionary/property/sslCertificates.lcdoc
  docs/dictionary/property/stackFileVersion.lcdoc
  docs/dictionary/property/startFrame.lcdoc
  docs/glossary/s/SQL.lcdoc
  docs/glossary/s/stack-version.lcdoc
  docs/glossary/s/standard-output.lcdoc
Labels: vulcan/reviewed

#6835 [21765] Fix problem when 'adb devices' finds no serial number
  docs/notes/bugfix-21765.md
  ide-support/revdeploylibraryandroid.livecodescript
Labels: bug, vulcan/reviewed

#6846 [[ Bug 21778 ]] Add sorting / collation support for more locales
  docs/notes/bugfix-21778.md
  prebuilt/rsrc/icudata-minimal-list.txt
Labels: LCS, bug, vulcan/reviewed

#6840 [Bugfix 12410] Mention trailing slash removal for defaultFolder
  docs/dictionary/property/defaultFolder.lcdoc
  docs/notes/bugfix-12410.md
Labels: vulcan/reviewed

#6832 [18606] Ensure setting the imagesource to a remote image works
  docs/notes/bugfix-18606.md
  engine/src/dispatch.cpp
Labels: bug, vulcan/reviewed

#6791 [21690] Fix crash when clicking on magnify palette with Browse tool
  docs/notes/bugfix-21690.md
  engine/src/idraw.cpp
Labels: bug, vulcan/reviewed

#6836 [21767] Support for splash images for iPhone XR and XSMAX
  engine/src/mbliphoneapp.mm
  ide-support/revsaveasiosstandalone.livecodescript
Labels: bug, enhancement, vulcan/reviewed

#6847 Add missing reference.
  docs/dictionary/keyword/URL.lcdoc
Labels: vulcan/reviewed

#6682 [Bugfix 18359] Add note about non-numeric x-values for hilitedCoordinates
  docs/notes/bugfix-18359.md
  extensions/widgets/graph/graph.lcb
Labels: vulcan/reviewed

#6849 [[Dictionary]] Unlock error dialogs typo
  docs/dictionary/command/unlock-error-dialogs.lcdoc
Labels: vulcan/reviewed

#6845 [[ Perf ]] Array access optimizations
  benchmarks/_benchmarkrunner.livecodescript
  benchmarks/lcs/control/array.livecodescript
  benchmarks/lcs/control/example_tsv_records.txt
  benchmarks/lcs/control/the_adventures_of_sherlock_holmes.txt
  engine/src/exec.cpp
  engine/src/externalv0.cpp
  engine/src/handler.cpp
  engine/src/parseerrors.h
  engine/src/variable.cpp
  engine/src/variable.h
  libfoundation/include/foundation-auto.h
  libfoundation/include/foundation.h
  libfoundation/libfoundation.gyp
  libfoundation/src/foundation-array.cpp
  libfoundation/src/foundation-name.cpp
  libfoundation/src/foundation-number.cpp
  libfoundation/src/foundation-private.h
  libfoundation/src/foundation-string.cpp
  libfoundation/src/foundation-value.cpp
  libfoundation/test/test_memory.cpp
Labels: enhancement, vulcan/reviewed

#6831 [21168] Ensure path to MacOS app icon is always resolved
  docs/notes/bugfix-21168.md
  ide-support/revsaveasstandalone.livecodescript
Labels: vulcan/reviewed

#6838 [Dictionary] set to show
  docs/dictionary/command/set.lcdoc
  docs/dictionary/command/show.lcdoc
  docs/dictionary/function/setRegistry.lcdoc
  docs/dictionary/function/setResource.lcdoc
  docs/dictionary/function/sha1Digest.lcdoc
  docs/dictionary/function/shortFilePath.lcdoc
  docs/dictionary/keyword/seventh.lcdoc
  docs/dictionary/property/columnDelimiter.lcdoc
  docs/dictionary/property/shadow.lcdoc
  docs/dictionary/property/shadowColor.lcdoc
Labels: vulcan/reviewed

#6850 Add windows installation notes
  docs/development/build-win.md
  docs/development/images/add-perl-to-the-path-environment-variable.png
  docs/development/images/add-python-27-to-path.png
  docs/development/images/add-windows-81-sdk-and-visual-c-mfc-for-x86-and-x64.png
  docs/development/images/build-livecode-all.png
  docs/development/images/configure-for-c-development.png
  docs/development/images/install-cygwin-with-additional-packages.png
  docs/development/images/set-the-livecode-all-debugging-command.png
  docs/development/images/set-up-for-visual-c-.png
Labels: vulcan/reviewed

#6853 Added support for building with Xcode 10.1 / iOS 12.1 SDK
  Installer/package.txt
  Makefile
  config.py
  docs/notes-base/platforms.md
  ide-support/revdeploylibraryios.livecodescript
  prebuilt/fetch-libraries.sh
  prebuilt/scripts/ios.inc
  tools/setup_xcode_sdks.py
Labels: enhancement, vulcan/reviewed

#6861 [Bugfix 21741] Add notes about evaluating scientific notation
  docs/dictionary/operator/equals.lcdoc
  docs/glossary/s/scientific-notation.lcdoc
Labels: vulcan/reviewed

#6859 [Dictionary] switch to thumbSize
  docs/dictionary/control_st/switch.lcdoc
  docs/dictionary/control_st/throw.lcdoc
  docs/dictionary/function/tan.lcdoc
  docs/dictionary/keyword/system.lcdoc
  docs/dictionary/keyword/templateButton.lcdoc
  docs/dictionary/keyword/templateVideoClip.lcdoc
  docs/dictionary/keyword/tenth.lcdoc
  docs/dictionary/keyword/the.lcdoc
  docs/dictionary/keyword/third.lcdoc
  docs/dictionary/keyword/this.lcdoc
  docs/dictionary/property/systemColorSelector.lcdoc
  docs/dictionary/property/systemFileSelector.lcdoc
  docs/dictionary/property/text.lcdoc
  docs/dictionary/property/textStyle.lcdoc
  docs/dictionary/property/themeClass.lcdoc
  docs/dictionary/property/thumbSize.lcdoc
  docs/glossary/t/tabbed-button.lcdoc
Labels: vulcan/reviewed

#6863 [21807] Ensure you can set the android recorder props more than once
  docs/notes/bugfix-21807.md
  extensions/libraries/androidaudiorecorder/androidaudiorecorder.lcb
Labels: bug, vulcan/reviewed

#6864 Improve memory usage when app is launched from Finder
  engine/rsrc/LiveCode-Info.plist
  engine/rsrc/Standalone-Info.plist
Labels: enhancement, vulcan/reviewed
