Repository livecode/livecode, pull requests merged in 2020-04, with the labels that each got.

#7305 [[ Bug 22487 ]] Audit engine for iOS dark mode issues
  docs/notes/bugfix-22487.md
  engine/src/mbliphonedialog.mm
  engine/src/mbliphonepick.mm
  engine/src/mbliphonepickdate.mm
Labels: bug, vulcan/reviewed

#7309 [22054] Ensure mobilePickPhoto() proceeds after taking a photo
  docs/notes/bugfix-22054.md
  engine/src/java/com/runrev/android/Engine.java
Labels: bug, vulcan/reviewed

#7311 [22634] Fix scaling of mobilePick menus when device is on landscape
  docs/notes/bugfix-22634.md
  engine/src/mbliphonepick.mm
  engine/src/mbliphonepickdate.mm
Labels: bug, vulcan/reviewed

#7303 [[ 22635 ]] Remove unsupported Android minimum deployment versions
  docs/notes/bugfix-22635.md
  ide-support/revdeploylibraryandroid.livecodescript
  ide-support/revsaveasandroidstandalone.livecodescript
Labels: bug, vulcan/reviewed

#7310 [[ Bug 22623 ]] Fixes for iOS simulator in notarized builds
  ide-support/revsaveasiosstandalone.livecodescript
Labels: blocker, bug, vulcan/reviewed

#7306 [[ Bug 22645 ]] Add NSBluetoothAlwaysUsageDescription to iOS plist
  docs/notes/bugfix-22645.md
  engine/rsrc/mobile-device-template.plist
  engine/rsrc/mobile-template.plist
  engine/rsrc/standalone-mobile-Info.plist
Labels: bug, vulcan/reviewed

#7142 [[ Debug ]] Docs and tweaks for android debugging
  docs/development/build-android.md
  engine/engine.gyp
  tools/extract-debug-symbols.sh
  util/set_android_debuggable.sh
Labels: documentation, vulcan/reviewed

#7271 [Bugfix-22596] Include Android in playLoudness docs
  docs/dictionary/property/playLoudness.lcdoc
  docs/notes/bugfix-22596.md
Labels: vulcan/reviewed

#6404 [[ Navigation Bar ]] Add option to highlight none of the icons
  extensions/widgets/navbar/navbar.lcb
  extensions/widgets/navbar/notes/feature-nohighlight.md
Labels: vulcan/reviewed

#7232 [[ Bug 21566 ]] Fix crash when opening and closing modal windows
  docs/notes/bugfix-21566.md
  engine/src/mac-core.mm
Labels: bug, vulcan/reviewed

#7280 [[ Bug 22543 ]] Ensure multiple queued requests are handled correctly
  extensions/widgets/browser/notes/22543.md
  libbrowser/src/libbrowser_wkwebview.h
  libbrowser/src/libbrowser_wkwebview.mm
Labels: LCB, bug, vulcan/reviewed

#7314 [[ Bug 22664 ]] Add support for front camera in Android mobilePickPhoto
  docs/dictionary/command/mobilePickPhoto.lcdoc
  docs/notes/bugfix-22664.md
  engine/src/java/com/runrev/android/Engine.java
  engine/src/mblandroidcamera.cpp
Labels: enhancement, vulcan/reviewed

#7298 [[ Bug 22607 ]] Implement system appearance support
  docs/dictionary/message/systemAppearanceChanged.lcdoc
  docs/dictionary/property/systemAppearance.lcdoc
  docs/notes/bugfix-22607.md
  engine/src/desktop-dc.cpp
  engine/src/desktop-dc.h
  engine/src/desktop.cpp
  engine/src/exec-interface2.cpp
  engine/src/exec.h
  engine/src/java/com/runrev/android/Engine.java
  engine/src/lextable.cpp
  engine/src/mac-core.mm
  engine/src/mblandroiddc.cpp
  engine/src/mbldc.h
  engine/src/mbliphoneapp.mm
  engine/src/mbliphonedc.mm
  engine/src/mblnotification.cpp
  engine/src/mblnotification.h
  engine/src/mcstring.cpp
  engine/src/mcstring.h
  engine/src/parsedef.h
  engine/src/platform-internal.h
  engine/src/platform.cpp
  engine/src/platform.h
  engine/src/property.cpp
  engine/src/uidc.cpp
  engine/src/uidc.h
  ide-support/revsaveasandroidstandalone.livecodescript
Labels: enhancement, vulcan/reviewed

#7316 [Platform support] Update notes
  docs/notes-base/platforms.md
Labels: vulcan/reviewed

#7315 [[ Bug 22607 ]] Fix compilation errors pre-iOS 12
  engine/src/mbliphonedc.mm
Labels: blocker, bug, vulcan/reviewed

#7317 [[ Bug 22607 ]] Fix missing header
  engine/src/mbliphonedc.mm
Labels: blocker, bug, vulcan/reviewed

#7318 [[ Bug 22668 ]] Fix bug preventing JS execution in Android browser
  engine/src/mblandroiddc.cpp
  engine/src/mblandroidjava.cpp
  engine/src/mblandroidjava.h
  extensions/widgets/browser/notes/22668.md
Labels: blocker, bug, vulcan/reviewed

#7321 [[ Bug 22673 ]] Show first frame in Android player
  docs/notes/bugfix-22673.md
  engine/src/java/com/runrev/android/nativecontrol/ExtVideoView.java
Labels: bug, vulcan/reviewed

#7320 [[ Bug 22671 ]] Fix mobile player controller visibility
  docs/notes/bugfix-22671.md
  engine/src/java/com/runrev/android/nativecontrol/VideoControl.java
Labels: bug, vulcan/reviewed

#7324 [[ Bug 22663 ]] Support max width/height in Android mobilePickPhoto
  docs/dictionary/command/mobilePickPhoto.lcdoc
  docs/notes/bugfix-22663.md
  engine/src/java/com/runrev/android/Engine.java
  engine/src/mblandroidcamera.cpp
Labels: bug, vulcan/reviewed

#7326 [Bugfix-22686] Correct parameter in playerPropertyAvailable example
  docs/dictionary/message/playerPropertyAvailable.lcdoc
  docs/notes/bugfix-22686.md
Labels: vulcan/reviewed

#7191 [Bugfix-19848] Mention lockLoc allows arrow key movement
  docs/dictionary/property/lockLocation.lcdoc
  docs/notes/bugfix-19848.md
Labels: vulcan/reviewed

#7273 [Bugfix-11554] Remove inaccuracies from mobilePickDate docs
  docs/dictionary/command/mobilePickDate.lcdoc
  docs/notes/bugfix-11554.md
Labels: vulcan/reviewed

#7327 [9.6 RC-1] Updated version
  version
Labels: vulcan/reviewed

#7313 [[ mergExt ]] Update pointer
  builder/builder_utilities.livecodescript
Labels: enhancement, vulcan/reviewed

#7300 Support building with Xcode 11.4 / iOS 13.4 SDK
  Installer/package.txt
  Makefile
  config.py
  docs/notes-base/platforms.md
  ide-support/revdeploylibraryios.livecodescript
  prebuilt/fetch-libraries.sh
  prebuilt/scripts/ios.inc
  tools/setup_xcode_sdks.py
Labels: enhancement, vulcan/reviewed

#7207 [[Bugfix 22433]] Docs: Update selectionChanged
  docs/dictionary/message/selectionChanged.lcdoc
  docs/notes/bugfix-22433.md
Labels: vulcan/reviewed

#7328 [[ Bug 22689 ]] Fix execution error when calling JavaScript in iOS browser widget
  engine/src/browser.lcb
  extensions/widgets/browser/notes/22689.md
  libbrowser/src/libbrowser_wkwebview.mm
Labels: LCB, bug, vulcan/reviewed

#7120 [22209] Updated copyright notice
  docs/notes/bugfix-22209.md
  engine/rsrc/Installer-Info.plist
  engine/rsrc/LiveCode-Info.plist
  engine/rsrc/Standalone-Info.plist
Labels: bug, vulcan/reviewed

#7329 [[ Bug 22688 ]] Fix bug preventing mobile browser control from loading after setting the "url" property to empty
  extensions/widgets/browser/notes/22688.md
  libbrowser/src/libbrowser_wkwebview.mm
Labels: bug, vulcan/reviewed

#7252 [[Bug 22363 ]] Ensure Windows player shows correct frame for currentTime when paused
  docs/notes/bugfix-22363.md
  engine/src/w32-ds-player.cpp
Labels: LCS, bug, vulcan/reviewed

#7331 [[ Bug 22693 ]] Fix url callbacks sent when setting html in CEF browser
  extensions/widgets/browser/notes/22693.md
  libbrowser/src/libbrowser_cef.cpp
Labels: bug, vulcan/reviewed

#7334 [[ Bug 22700 ]] Fix crash on enter in android native field widget
  extensions/widgets/androidfield/androidfield.lcb
  extensions/widgets/androidfield/notes/22700.md
Labels: bug, vulcan/reviewed

#7333 [Bugfix-22433] Correct selectionChanged for missing text
  docs/dictionary/message/selectionChanged.lcdoc
Labels: vulcan/reviewed

#7296 [Bug 22624] Tree View Widget sends click when scrolling
  extensions/widgets/treeview/notes/22624.md
  extensions/widgets/treeview/treeview.lcb
Labels: vulcan/reviewed

#7335 [Bugfix-22209] Update copyright notice for 2020
  engine/rsrc/Installer-Info.plist
  engine/rsrc/LiveCode-Info.plist
  engine/rsrc/Standalone-Info.plist
Labels: vulcan/reviewed

#7308 [[ Bug 22605 ]] Load startup screen storyboard
  Installer/package.txt
  docs/notes/bugfix-22605.md
  engine/engine.gyp
  engine/rsrc/Default-568h@2x.png
  engine/rsrc/mobile-device-template.plist
  engine/rsrc/mobile-splashscreen-template.plist
  engine/rsrc/mobile-template.plist
  engine/rsrc/template.storyboard
  engine/src/mbliphoneapp.h
  engine/src/mbliphoneapp.mm
  ide-support/revsaveasiosstandalone.livecodescript
Labels: blocker, enhancement, vulcan/reviewed

#7336 [[ Bug 22605 ]] Improve storyboard launch file support for dark mode
  engine/rsrc/template.storyboard
  ide-support/revsaveasiosstandalone.livecodescript
Labels: bug, enhancement, vulcan/reviewed

#7338 [[ Bug 22710 ]] Reset itemDelimiter to resolve divide by 0 error
  ide-support/revsaveasiosstandalone.livecodescript
Labels: bug, vulcan/reviewed

#7340 [[ Bug 22379 ]] Ignore foreign handler calling convention on 64-bit Windows
  docs/lcb/notes/22379.md
  libscript/src/script-instance.cpp
Labels: LCB, bug, vulcan/reviewed

#7341 [[ Bug 22605 ]] Fix iOS dark launch image clobbering light image
  ide-support/revsaveasiosstandalone.livecodescript
Labels: bug, vulcan/reviewed

#7342 [[ Bugfix 21305 ]] Improve performance of stackfile saving on Windows
  docs/notes/bugfix-21305.md
  engine/src/w32dc.cpp
  engine/src/w32dc.h
  engine/src/w32dcs.cpp
  engine/src/windows-theme.cpp
Labels: bug, vulcan/reviewed

#7339 [[ LifecycleListeners ]] Allow lcb widgets to register and listen for Android lifecycle events
  engine/src/java/com/runrev/android/Engine.java
  extensions/modules/android-utils/android-utils.lcb
  extensions/modules/android-utils/notes/feature-android_lifecycle_events.md
  ide-support/revdocsparser.livecodescript
Labels: LCB, enhancement, vulcan/reviewed
