Repository livecode/livecode, pull requests merged in 2020-10, with the labels that each got.

#7441 [[ Tests ]] Increase socket timeout in liburl status codes test
  tests/lcs/liburl/status_codes.livecodescript
Labels: LCS, tests, vulcan/reviewed

#7444 [[ Bug 22929 ]] Fix high CPU usage when showing modal stack
  docs/notes/bugfix-22929.md
  engine/src/mac-core.mm
Labels: bug, vulcan/reviewed

#7448 [[ Bug 19016 ]] Fix printing with vGrid enabled on Windows
  docs/notes/bugfix-19016.md
  engine/src/customprinter.cpp
  engine/src/w32printer.cpp
Labels: bug, vulcan/reviewed

#7445 [[ Bug 22927 ]] Fix tracking of mouse events during modal session
  docs/notes/bugfix-22927.md
  engine/src/mac-core.mm
  engine/src/mac-internal.h
  engine/src/mac-window.mm
Labels: bug, vulcan/reviewed

#7446 [[ Bug 22935 ]] Fix engine instability after opening & closing modal stack
  docs/notes/bugfix-22935.md
  engine/src/mac-core.mm
  engine/src/mac-internal.h
  libfoundation/include/foundation-auto.h
Labels: bug, vulcan/reviewed

#7449 [[ Bug 22940 ]] Remove support for 32bit on MacOS IDE and standalones
  Installer/package.txt
  config.py
  config/mac.gypi
  docs/notes/bugfix-22940.md
  ide-support/revsaveasstandalone.livecodescript
  ide-support/revsblibrary.livecodescript
Labels: vulcan/reviewed

#7442 [[ Issue 22933 ]] Remove unneccessary creation and clearance of SKBitmap
  docs/notes/bugfix-22933.md
  libgraphics/src/context.cpp
Labels: bug, vulcan/reviewed

#7454 [[ Bug 22942 ]] Ensure the shellcommand defaults to COMSPEC on Windows
  docs/dictionary/property/shellCommand.lcdoc
  docs/notes/bugfix-22942.md
  engine/src/dskw32.cpp
  engine/src/exec-files.cpp
Labels: bug, vulcan/reviewed

#7439 [[ Bug 22914 ]] Call doProcess in updateKeyboardVisible
  docs/notes/bugfix-22914.md
  engine/src/java/com/runrev/android/Engine.java
Labels: bug, vulcan/reviewed

#7456 [[ Bug 22947 ]] Change the behavior of the long deprecated function 'iphoneSystemIdentifier'
  docs/dictionary/function/iphoneSystemIdentifier.lcdoc
  docs/notes/bugfix-22947.md
  engine/src/mbliphoneextra.mm
Labels: vulcan/reviewed

#7450 [[ Bug 22946 ]] Update the engine to compile with Xcode 12
  config/ios.gypi
  engine/src/mbliphoneapp.mm
  engine/src/mbliphonedc.mm
  toolchain/lc-compile-ffi-java/src/main.c
Labels: enhancement, vulcan/reviewed

#7461 Typo fixes
  docs/dictionary/command/answer-file.lcdoc
  docs/dictionary/command/create-card.lcdoc
  docs/dictionary/command/decrypt.lcdoc
  docs/dictionary/command/edit.lcdoc
  docs/dictionary/command/encrypt.lcdoc
  docs/dictionary/command/grab.lcdoc
Labels: vulcan/reviewed

#7463 [[ Bug 22951 ]] Add note about scaleFactor not persisting in standalones
  docs/dictionary/property/scaleFactor.lcdoc
  docs/notes/bugfix-22951.md
Labels: bug, vulcan/reviewed

#7462 [[ Build ]] Do not sign simulator .dylib externals
  tools/build-extension-ios.sh
Labels: blocker, vulcan/reviewed

#7464 [[ Bug 22889 ]] Update mergExt for iOS SDK 14.1
  builder/builder_utilities.livecodescript
Labels: vulcan/reviewed

#7465 [[ tsNet ]] Update pointer
  builder/builder_utilities.livecodescript
Labels: vulcan/reviewed

#7460 [[ Bug 22952 ]] Fix event handling of nested modal stacks
  docs/notes/bugfix-22952.md
  engine/src/mac-core.mm
Labels: bug, vulcan/reviewed

#7459 [[ Bug 22888 ]] Add support for building apps against iOS 14.1 SDK
  Installer/package.txt
  Makefile
  config.py
  docs/notes-base/platforms.md
  docs/notes/bugfix-22888.md
  ide-support/revdeploylibraryios.livecodescript
  prebuilt/fetch-libraries.sh
  prebuilt/scripts/ios.inc
  tools/setup_xcode_sdks.py
Labels: vulcan/reviewed
