Repository livecode/livecode, pull requests merged in 2020-09, with the labels that each got.

#7427 [Bugfix-22892] Add detail to "is an integer"
  docs/dictionary/operator/is-a.lcdoc
  docs/notes/bugfix-22892.md
Labels: bug, vulcan/reviewed

#7430 [Bugfix-14941] Correct XML Function References in User Guide
  docs/guides/Processing Text and Data.md
  docs/notes/bugfix-14941.md
Labels: bug, vulcan/reviewed

#7429 [[ Bug 22901 ]] Ensure commercial debug symbols for Win are copied
  tools/windows_debug_syms.pl
Labels: bug

#7428 [[ Bug 22894 ]] Android Manifest: Allow merging <activity> children
  docs/notes/bugfix-22894.md
  ide-support/revsaveasandroidstandalone.livecodescript
Labels: enhancement, vulcan/reviewed

#7435 [Bugfix-22891] Clarify behavior of rename command when file exists
  docs/dictionary/command/rename.lcdoc
  docs/notes/bugfix-22891.md
Labels: LCS, documentation, vulcan/reviewed

#7436 [[ Prebuilts ]] Disable U_HAVE_STRTOD_L when building ICU for Android
  prebuilt/scripts/build-icu.sh
Labels: bug

#7440 [[ Bug 22918 ]] Fix crash when deleting object target of messages
  docs/notes/bugfix-22918.md
  engine/src/object.cpp
Labels: bug, vulcan/reviewed
