Repository livecode/livecode, pull requests merged in 2020-07, with the labels that each got.

#7394 [[ Foundation ]] Prevent emission of logging parameters in release mode
  libfoundation/include/foundation.h
Labels: bug, vulcan/reviewed

#7368 [[ Bug 22763 ]] Fix resizing mobilePickPhoto for API Level < 24
  docs/notes/bugfix-22763.md
  engine/src/java/com/runrev/android/Engine.java
Labels: bug, vulcan/reviewed

#7389 [[ Bug 22802 ]] Fix crash in HTML5 standalones when fetching the system date or system time
  docs/notes/bugfix-22802.md
  engine/src/sysunxdate.cpp
Labels: bug, vulcan/reviewed

#7388 [[ Bug 22801 ]] Fix crash in HTML5 standalones when getting / setting the effective rect of a stack
  docs/notes/bugfix-22801.md
  engine/src/em-stack.cpp
Labels: bug, vulcan/reviewed

#7375 [[ Bug 21353 ]] Ensure long lines are shown in full in mobilePick on iOS
  docs/notes/bugfix-21353.md
  engine/src/mbliphonepick.mm
Labels: vulcan/reviewed

#7345 [[ Bug 22705 ]] Resolve crash focusing on unopen stack
  docs/notes/bugfix-22705.md
  engine/src/desktop-dc.cpp
Labels: bug, vulcan/reviewed

#7347 [[ Bug 22711 ]] Fix crash when calling copy on non-field text chunk
  docs/notes/bugfix-22711.md
  engine/src/cmdsc.cpp
Labels: bug, vulcan/reviewed

#7348 [[ Documentation ]] Add references between scriptOnly property and script only stack glossary
  docs/dictionary/property/scriptOnly.lcdoc
  docs/glossary/s/script-only-stack.lcdoc
Labels: vulcan/reviewed

#7397 [Bugfix-22778] Add QT deprecation note to play entry
  docs/dictionary/command/play.lcdoc
Labels: vulcan/reviewed

#7400 [[ emscripten ]] Use a single hidden input field for all LC windows
  engine/src/em-event.js
Labels: bug, vulcan/reviewed

#7398 [[ Bug 22763 ]] Ensure the captured image is not rotated when saved
  engine/src/java/com/runrev/android/Engine.java
Labels: bug, vulcan/reviewed

#7403 [[ emscripten ]] Keep hidden input field in fixed position in browser window
  engine/src/em-event.js
Labels: bug, vulcan/reviewed

#7405 [[ Bug 22544 ]] Enable text editing options in CEF context menu
  docs/notes/bugfix-22544.md
  libbrowser/src/libbrowser_cef.cpp
Labels: bug, vulcan/reviewed

#7408 [[ Bug 22854 ]] Fix crash deleting touch target on mobile
  docs/notes/bugfix-22854.md
  engine/src/eventqueue.cpp
Labels: bug, vulcan/reviewed

#7410 [[ Android API 29 ]] Update to use android API 29
  config.py
  docs/development/build-android.md
  ide-support/revdeploylibraryandroid.livecodescript
  prebuilt/scripts/android.inc
Labels: blocker, vulcan/reviewed

#7402 [[ Bug 22839 ]] Clear focused control ref from card when relayering
  docs/notes/bugfix-22839.md
  engine/src/card.cpp
Labels: bug, vulcan/reviewed

#7409 [[ Bug 22855 ]] Fix hang in EvaluateJavaScript on iOS
  docs/notes/bugfix-22855.md
  libbrowser/src/libbrowser_wkwebview.mm
Labels: bug, vulcan/reviewed

#7412 Remove AdModule.java file from the commercial engine dependencies
  engine/engine-sources.gypi
Labels: bug, vulcan/reviewed
