Repository livecode/livecode, pull requests merged in 2020-05, with the labels that each got.

#7343 [[ Bug 21387 ]] Provide means to create function ptr with abi
  libfoundation/include/foundation.h
  libfoundation/src/foundation-handler.cpp
  libfoundation/src/foundation-private.h
Labels: enhancement, vulcan/reviewed

#7346 [[ Bug 22702 ]] Perform ad-hoc codesign of macOS standalones
  docs/notes/bugfix-22702.md
  ide-support/revsaveasstandalone.livecodescript
Labels: bug, vulcan/reviewed

#7349 [[ Bug 22718 ]] Don't fail opening socket if can't set SO_REUSEPORT option
  docs/notes/bugfix-22718.md
  engine/src/opensslsocket.cpp
Labels: bug

#7350 Make sure you have permissions to clear extended attributes
  ide-support/revsaveasstandalone.livecodescript
Labels: blocker, vulcan/reviewed

#7354 [9.6.1 RC-1] Updated version
  version
Labels: vulcan/reviewed

#7332 [Bugfix-16662] Describe speed in mobileSensorReading
  docs/dictionary/function/mobileSensorReading.lcdoc
  docs/notes/bugfix-16662.md
Labels: enhancement, vulcan/reviewed

#7322 [[ OpenSSL ]] Update prebuilt OpenSSL library to version 1.1.1g
  prebuilt/scripts/android.inc
  prebuilt/scripts/build-openssl.sh
  prebuilt/scripts/platform.inc
  prebuilt/versions/openssl
Labels: enhancement, vulcan/reviewed

#7355 [Bugfix-21183] Document specialFolderPath("resources") behaviour for unsaved stacks
  docs/dictionary/function/specialFolderPath.lcdoc
  docs/notes/bugfix-21183.md
Labels: vulcan/reviewed

#7356 [9.6.0 RC-2] Updated version
  version
Labels: vulcan/reviewed

#7357 [22733] Remove redundant warning from the standalone builder
  docs/notes/bugfix-22733.md
  ide-support/revsaveasiosstandalone.livecodescript
Labels: bug, vulcan/reviewed

#7353 [[ Bug 22729 ]] Fix iOS framework signing
  docs/notes/bugfix-22729.md
  ide-support/revsaveasiosstandalone.livecodescript
Labels: bug, vulcan/reviewed

#7351 [Bugfix-22723] Change pasteKey example syntax
  docs/dictionary/message/pasteKey.lcdoc
  docs/notes/bugfix-22723.md
Labels: vulcan/reviewed

#7361 [22737] Ensure the externals lcextd folder is not copied into the apk
  docs/notes/bugfix-22737.md
  ide-support/revsaveasandroidstandalone.livecodescript
Labels: blocker, bug, vulcan/reviewed

#7190 [22401] Ensure iOS time picker always returns the displayed time
  docs/notes/bugfix-22401.md
  engine/src/mbliphonepickdate.mm
Labels: bug, vulcan/reviewed

#7108 [[ Bug 22187 ]] Ensure rewind and fast forward buttons do not affect playrate
  docs/notes/bugfix-22187.md
  engine/src/player-platform.cpp
  engine/src/player-platform.h
Labels: bug, vulcan/reviewed

#7365 [9.6.0] Updated version
  version
Labels: vulcan/reviewed

#7360 [20120] Ensure location data is always returned on Android
  docs/notes/bugfix-20120.md
  engine/src/java/com/runrev/android/SensorModule.java
Labels: bug, vulcan/reviewed
