Repository livecode/livecode, pull requests merged in 2020-06, with the labels that each got.

#7359 [11170] Turn off auto-suggestion in Android native password fields
  engine/src/java/com/runrev/android/nativecontrol/InputControl.java
Labels: bug, vulcan/reviewed

#7372 [[ Bug 22746 ]] Add release note
  docs/notes/bugfix-22746.md
Labels: vulcan/reviewed

#7369 [[ tsNet ]] Update pointer
  builder/builder_utilities.livecodescript
Labels: vulcan/reviewed

#7371 [[ Bug 22638 ]] Add release note
  docs/notes/bugfix-22638.md
Labels: vulcan/reviewed

#7370 [[ Bug 22755 ]] Add release note
  docs/notes/bugfix-22755.md
Labels: vulcan/reviewed

#7367 [[ Bug 22760 ]] Fix 'external' handler invocation
  docs/lcb/notes/22760.md
  engine/src/mbliphonedc.mm
  libfoundation/src/foundation-handler.cpp
  libfoundation/src/foundation-java-private.cpp
Labels: bug, vulcan/reviewed

#7373 [[ Bug 22777 ]] Implement hitTest in iOS native container view
  docs/notes/bugfix-22777.md
  engine/src/native-layer-ios.mm
Labels: bug, vulcan/reviewed

#7366 [[ Bug 22698 ]] Fix crash when relayering field with key focus
  docs/notes/bugfix-22698.md
  engine/src/card.cpp
  engine/src/exec-interface2.cpp
  engine/src/group.cpp
Labels: bug, vulcan/reviewed

#7290 [Bugfix-8822] Say open file can't create folder
  docs/dictionary/command/open-file.lcdoc
  docs/notes/bugfix-8822.md
Labels: vulcan/reviewed

#7376 [9.7.0 DP-1] Updated version
  version
Labels: vulcan/reviewed

#7374 [21857] Make autoupdater faster when downloading a new LC version
  builder/installer/installeruiupdatedownloadcardbehavior.livecodescript
  docs/notes/bugfix-21857.md
Labels: vulcan/reviewed

#7379 Add support for building with Xcode 11.5 / iOS 13.5 SDK
  Installer/package.txt
  Makefile
  config.py
  docs/notes-base/platforms.md
  ide-support/revdeploylibraryios.livecodescript
  prebuilt/fetch-libraries.sh
  prebuilt/scripts/ios.inc
  tools/setup_xcode_sdks.py
Labels: vulcan/reviewed

#7380 [[ Bug 22756 ]] Update mergExt for iOS 13.5
  builder/builder_utilities.livecodescript
Labels: enhancement, vulcan/reviewed

#7384 Merge develop 9.6 23.06.2020
  Installer/package.txt
  Makefile
  builder/builder_utilities.livecodescript
  builder/installer/installeruiupdatedownloadcardbehavior.livecodescript
  config.py
  docs/notes-base/platforms.md
  docs/notes/bugfix-21857.md
  ide-support/revdeploylibraryios.livecodescript
  prebuilt/fetch-libraries.sh
  prebuilt/scripts/ios.inc
  tools/setup_xcode_sdks.py
Labels: vulcan/reviewed

#7385 [[ Bug 22787 ]] Fix event handling during modal sessions
  docs/notes/bugfix-22787.md
  engine/src/mac-core.mm
Labels: bug, vulcan/reviewed

#7352 [[ Bug 21001 ]] Fix forwarding of key events in HTML5 engine
  docs/notes/bugfix-21001.md
  engine/src/em-event.js
  engine/src/eventqueue.cpp
  engine/src/eventqueue.h
  engine/src/mbldc.cpp
Labels: bug, vulcan/reviewed

#7381 [Bug 22557] OAuth2 - Prevent double URL encoding of authentication code
  extensions/script-libraries/oauth2/notes/22557.md
  extensions/script-libraries/oauth2/oauth2.livecodescript
Labels: need-rebase, vulcan/reviewed

#7392 [Bugfix-22795] Correct documented opacity range in mobileBusyIndicatorStart
  docs/dictionary/command/mobileBusyIndicatorStart.lcdoc
  docs/notes/bugfix-22795.md
Labels: vulcan/reviewed

#7391 [Bugfix-22796] Add info about activity/busy indicators' input blocking
  docs/dictionary/command/iphoneActivityIndicatorStart.lcdoc
  docs/dictionary/command/mobileBusyIndicatorStart.lcdoc
  docs/notes/bugfix-22796.md
Labels: vulcan/reviewed

#7363 [[ Bug 22095 ]] Fix input of alt+key combination characters in HTML5 standalones
  docs/notes/bugfix-22095.md
  engine/src/em-event.js
Labels: blocker, bug, vulcan/reviewed

#7393 [Bugfix-22778] Add deprecation note to play videoClip
  docs/dictionary/command/play.lcdoc
  docs/notes/bugfix-22778.md
Labels: vulcan/reviewed
