Repository livecode/livecode, pull requests merged in 2020-03, with the labels that each got.

#7266 [[ Bug 22552 ]] Fix crash when touching screen during preOpenStack
  docs/notes/bugfix-22552.md
  engine/src/mbldc.cpp
Labels: bug, vulcan/reviewed

#7265 [22591] Fix drag-n-drop onto Mail app if filename has spaces
  docs/notes/bugfix-22591.md
  engine/src/mac-clipboard.mm
Labels: bug, vulcan/reviewed

#7267 [[ Bug 22593 ]] Add release note
  docs/notes/bugfix-22593.md
Labels: vulcan/reviewed

#7272 [bugfix-7948] Add docs note that revDeleteFolder can't delete defaultFolder
  docs/dictionary/command/revDeleteFolder.lcdoc
  docs/notes/bugfix-7948.md
Labels: vulcan/reviewed

#7275 [19997] Ensure the printPaperRectangle returns the correct value
  docs/notes/bugfix-19997.md
  engine/src/exec-printing.cpp
Labels: bug, vulcan/reviewed

#7276 [[ Bug 22602 ]] Ensure setting the keyboardType has an effect on iOS
  docs/notes/bugfix-22602.md
  engine/src/mbliphoneapp.mm
Labels: bug, vulcan/reviewed

#7277 Correct formatting in revDeleteFolder
  docs/dictionary/command/revDeleteFolder.lcdoc
Labels: vulcan/reviewed

#7095 [[ Config ]] Allow base android toolchain location to be specified
  config.py
  docs/development/build-android.md
Labels: vulcan/reviewed

#7285 [[ Bug 22615 ]] Fix build error when barcode scanner is included
  docs/notes/bugfix-22615.md
  ide-support/revsaveasandroidstandalone.livecodescript
Labels: bug, vulcan/reviewed

#7281 [[ Bug 22612]] Allow detection of "Apple Distribution" certificates
  docs/notes/bugfix-22612.md
  ide-support/revsaveasiosstandalone.livecodescript
Labels: enhancement, vulcan/reviewed

#7284 [Bugfix-16240] Explain how replace isn't recursive
  docs/dictionary/command/replace.lcdoc
  docs/notes/bugfix-16240.md
Labels: vulcan/reviewed

#7289 [[ Bug 22619 ]] Fix crash where listener param is null
  docs/lcb/notes/22619.md
  libfoundation/src/foundation-java-private.cpp
Labels: bug, vulcan/reviewed

#7282 [[ Bug 22614 ]] Resync mouse focus when control opacity changes
  docs/notes/bugfix-22614.md
  engine/src/exec-interface-graphic.cpp
  engine/src/exec-interface-group.cpp
  engine/src/exec-interface-object.cpp
  engine/src/exec-interface.cpp
  engine/src/group.h
  engine/src/object.cpp
  engine/src/object.h
Labels: bug, vulcan/reviewed

#7274 [[ Bug 22149 ]] Removed UIExitsOnSuspend key from plist
  engine/rsrc/mobile-device-template.plist
  ide-support/revsaveasiosstandalone.livecodescript
Labels: bug, vulcan/reviewed

#7288 [[ Build ]] Rename assert type enum entries
  engine/src/cmds.cpp
  engine/src/cmds.h
  engine/src/exec-debugging.cpp
  engine/src/parsedef.h
Labels: bug, vulcan/reviewed

#7286 [[ Bug 22616 ]] Fix incorrect placement of native layers within moved group
  docs/notes/bugfix-22616.md
  engine/src/group.cpp
Labels: bug, vulcan/reviewed

#7279 [[ Bug 22508 ]] Don't clear the clipboard when setting dragdata on Windows
  docs/notes/bugfix-22508.md
  engine/src/w32-clipboard.cpp
  engine/src/w32-clipboard.h
Labels: bug, vulcan/reviewed

#7292 [[ Bug ]] Fix error when installing app to simulator
  engine/rsrc/mobile-template.plist
Labels: blocker, vulcan/reviewed

#7243 [[ Bug 22511 ]] Fix multi-codepoint character parsing in JSONImport()
  docs/notes/bugfix-22511.md
  extensions/libraries/json/json.lcb
Labels: bug, vulcan/reviewed

#7291 [[ libscript ]] Add Objective-C block support
  docs/lcb/notes/feature-objc_blocks.md
  ide-support/revdocsparser.livecodescript
  libscript/src/objc.lcb
  libscript/stdscript-sources.gypi
  toolchain/lc-compile/src/emit.cpp
Labels: enhancement, vulcan/reviewed

#7295 [[ Bug 22603 ]] Correctly translate popup location to global location
  docs/lcb/notes/22603.md
  engine/src/widget-popup.cpp
Labels: bug, vulcan/reviewed

#7299 [[ Bug 22623 ]] Add support for lcextd mobile external folder
  ide-support/revsaveasandroidstandalone.livecodescript
  ide-support/revsaveasiosstandalone.livecodescript
  ide-support/revsblibrary.livecodescript
Labels: enhancement, vulcan/reviewed

#7304 [[ config ]] Update version of source code expected by javac
  config/java.gypi
Labels: vulcan/reviewed

#7301 [[ Bug 22606 ]] Support opting out of iOS dark mode
  docs/notes/bugfix-22606.md
  engine/rsrc/mobile-device-template.plist
  engine/rsrc/mobile-template.plist
  ide-support/revsaveasiosstandalone.livecodescript
Labels: enhancement, vulcan/reviewed
