Repository livecode/livecode, pull requests merged in 2020-01, with the labels that each got.

#7248 [9.6.0 dp-3] Updated version
  version
Labels: vulcan/reviewed

#7250 [[ mergExt ]] Update pointer
  builder/builder_utilities.livecodescript
Labels: vulcan/reviewed

#7246 Added support for building with Xcode11.3 / iOS13.2 SDK
  Installer/package.txt
  Makefile
  config.py
  docs/notes-base/platforms.md
  ide-support/revdeploylibraryios.livecodescript
  prebuilt/fetch-libraries.sh
  prebuilt/scripts/ios.inc
  tools/setup_xcode_sdks.py
Labels: vulcan/reviewed

#7247 [Dictionary] unicodeLabel to visible
  docs/dictionary/command/unload.lcdoc
  docs/dictionary/command/unlock-menus.lcdoc
  docs/dictionary/command/unlock-recent.lcdoc
  docs/dictionary/function/version.lcdoc
  docs/dictionary/property/unicodeLabel.lcdoc
  docs/dictionary/property/unicodePlainText.lcdoc
  docs/dictionary/property/unicodeTitle.lcdoc
  docs/dictionary/property/unicodeTooltip.lcdoc
  docs/dictionary/property/visible.lcdoc
Labels: vulcan/reviewed

#7253 [[ Bug 22533 ]] Add support for layerClipRect to widgets
  docs/notes/bugfix-22533.md
  engine/src/widget.cpp
Labels: bug, vulcan/reviewed

#7254 [[ Bug 22536 ]] Don't fail MCStringFindAndReplace if replacement not possible
  docs/notes/bugfix-22536.md
  libfoundation/src/foundation-string.cpp
  tests/lcs/core/strings/replace.livecodescript
Labels: bug, vulcan/reviewed

#7249 [Dictionary] vScroll to [end]
  docs/dictionary/function/within.lcdoc
  docs/dictionary/operator/wrap.lcdoc
  docs/dictionary/property/vScroll.lcdoc
  docs/dictionary/property/xScale.lcdoc
  docs/glossary/x/XML-tree.lcdoc
Labels: vulcan/reviewed

#7245 [Dictionary] templateAudioClip to unicodeFormattedText
  docs/dictionary/keyword/templateAudioClip.lcdoc
  docs/dictionary/message/touchEnd.lcdoc
  docs/dictionary/property/text.lcdoc
  docs/dictionary/property/textHeight.lcdoc
  docs/dictionary/property/thumbPosition.lcdoc
  docs/dictionary/property/topRight.lcdoc
  docs/dictionary/property/unboundedVScroll.lcdoc
  docs/dictionary/property/unicodeFormattedText.lcdoc
  docs/glossary/u/Unicode.lcdoc
Labels: vulcan/reviewed

#7256 [Bugfix-12504] Have caseSensitive & operators refer to each other
  docs/dictionary/operator/contains.lcdoc
  docs/dictionary/operator/is-among.lcdoc
  docs/dictionary/operator/is-in.lcdoc
  docs/dictionary/operator/is-not-among.lcdoc
  docs/dictionary/operator/is-not-in.lcdoc
  docs/dictionary/operator/less-than-or-greater-than.lcdoc
  docs/dictionary/operator/less-than.lcdoc
  docs/dictionary/property/caseSensitive.lcdoc
  docs/notes/bugfix-12504.md
Labels: vulcan/reviewed

#7255 [iPad Pro 11] Added support for splash screen and icon
  docs/notes/bugfix-22295.md
  engine/src/mbliphoneapp.mm
  ide-support/revsaveasiosstandalone.livecodescript
Labels: vulcan/reviewed

#7240 [Bug 22509] Tree View Widget crash
  extensions/widgets/treeview/notes/22509.md
  extensions/widgets/treeview/treeview.lcb
Labels: vulcan/reviewed

#7251 [[ Bug 22530 ]] Update Android text rendering
  docs/notes/bugfix-22530.md
  engine/src/mblandroidtextlayout.cpp
  libgraphics/include/graphics.h
  libgraphics/libgraphics.gyp
  libgraphics/src/harfbuzztext.cpp
Labels: LCS, bug, vulcan/reviewed

#7257 [iPad Pro 11] Ensure plist has new splash screen references and prevent memory corruption
  engine/src/mbliphoneapp.mm
  ide-support/revsaveasiosstandalone.livecodescript
Labels: vulcan/reviewed

#7258 Don't throw if no mapping between sim_version and sdk_version is found
  ide-support/revdeploylibraryios.livecodescript
Labels: vulcan/reviewed
