Repository livecode/livecode, pull requests merged in 2020-12, with the labels that each got.

#7485 [[ Bug 23003 ]] Fix engine pause after closing modal dialog on MacOS X
  docs/notes/bugfix-23003.md
  engine/src/mac-core.mm
Labels: bug, vulcan/reviewed

#7484 [Bugfix-22997] Add Big Sur to supported platforms
  docs/notes-base/platforms.md
  docs/notes/bugfix-22997.md
Labels: vulcan/reviewed

#7493 [[ Bug 23019 ]] Request Mac window redraw in bounds of dirty region
  docs/notes/bugfix-23019.md
  engine/src/mac-window.mm
Labels: blocker, bug, vulcan/reviewed

#7495 Merge release 9.6.2 30.12.2020
  docs/notes-base/platforms.md
  docs/notes/bugfix-22997.md
  docs/notes/bugfix-23003.md
  docs/notes/bugfix-23019.md
  engine/src/mac-core.mm
  engine/src/mac-window.mm
Labels: vulcan/reviewed
