Repository livecode/livecode, pull requests merged in 2020-11, with the labels that each got.

#7468 [Bugfix-22951] Correct scaleFactor bugfix.
  docs/dictionary/property/scaleFactor.lcdoc
Labels: vulcan/reviewed

#7472 [Bugfix-29959] - Fix missing text in time docs
  docs/dictionary/function/time.lcdoc
  docs/notes/bugfix-22959.md
Labels: vulcan/reviewed

#7466 [[ Bug 22586 ]] Fix buffer overrun in native split
  docs/notes/bugfix-22586.md
  libfoundation/src/foundation-string.cpp
  tests/lcs/core/array/split.livecodescript
Labels: bug, vulcan/reviewed

#7469 [[ Bug 22960 ]] Use the simctl tool for deploying to iOS simulator
  ide-support/revdeploylibraryios.livecodescript
Labels: blocker, bug, vulcan/reviewed

#7473 [[ Bug 22787 ]] Fix crash when reopening modal stack in "resumeStack" handler
  engine/src/mac-core.mm
  engine/src/mac-internal.h
  engine/src/mac-window.mm
Labels: blocker, bug, vulcan/reviewed

#7474 [[ Bug 22896 ]] Fix click location for sheet dialogs on MacOS Big Sur
  docs/notes/bugfix-22896.md
  engine/src/mac-window.mm
Labels: bug, vulcan/reviewed

#7477 [[ Bug 22974 ]] Set exported attribute of content provider to false
  docs/notes/bugfix-22974.md
  ide-support/revsaveasandroidstandalone.livecodescript
Labels: bug, vulcan/reviewed

#7471 [[ Bug 21471 ]] Fix revIsSpeaking function on Windows
  docs/notes/bugfix-21471.md
  revspeech/src/w32sapi5speech.cpp
  revspeech/src/w32sapi5speech.h
Labels: bug, vulcan/reviewed

#7470 [[ Bug 22940 ]] Remove "MacOSX x86-32" option from the "Test Target" list.
  ide-support/revsblibrary.livecodescript
Labels: bug, vulcan/reviewed

#7475 [[ Bug 22880 ]] Fix window shape not applied to stacks on MacOS Big Sur
  docs/notes/bugfix-22880.md
  engine/src/mac-window.mm
Labels: bug, vulcan/reviewed

#7476 [[ Bug 22937 ]] Fix crash where FileProvider projection null
  engine/src/java/com/runrev/android/FileProvider.java
Labels: bug, vulcan/reviewed

#7480 [[ Bug 22879 ]] Use correct text color for active tab button on Big Sur
  docs/notes/bugfix-22879.md
  engine/src/button.cpp
  engine/src/buttondraw.cpp
  engine/src/dskmac.cpp
  engine/src/dskw32.cpp
  engine/src/globals.cpp
  engine/src/mac-core.mm
  engine/src/mac-dialog.mm
  engine/src/mac-theme.mm
  engine/src/mblhandlers.cpp
  engine/src/mbliphone.mm
  engine/src/mbliphoneapp.mm
  engine/src/mbliphonecalendar.mm
  engine/src/mbliphonecontact.mm
  engine/src/mbliphonedc.mm
  engine/src/mbliphonedialog.mm
  engine/src/mbliphoneextra.mm
  engine/src/mbliphonefs.mm
  engine/src/mbliphonemediapick.mm
  engine/src/mbliphonepick.mm
  engine/src/mbliphonepickdate.mm
  engine/src/mbliphonescroller.mm
  engine/src/mbliphonesensor.mm
  engine/src/mbliphonesound.mm
  engine/src/platform-player.cpp
  engine/src/platform-recorder.cpp
  engine/src/srvwindows.cpp
  engine/src/sysdefs.h
  engine/src/w32ans.cpp
  engine/src/w32cursor.cpp
  engine/src/w32date.cpp
  engine/src/w32dc.cpp
  engine/src/w32dcs.cpp
  engine/src/w32image.cpp
  engine/src/w32printer.cpp
  engine/src/w32stack.cpp
  engine/src/w32theme.cpp
  engine/src/windows-theme.cpp
Labels: bug, vulcan/reviewed

#7479 [[ Bug 22980 ]] Initialize uninitialized MCPlatformMenuItemHighlight variable
  docs/notes/bugfix-22980.md
  engine/src/desktop-menu.cpp
Labels: bug, vulcan/reviewed

#7481 [[ Bug 22987 ]] Fix wrong operator used to combine version number components
  engine/src/sysdefs.h
Labels: blocker, bug, vulcan/reviewed

#7482 [[ Bug 22996 ]] Fix JNI error calling methods that trigger callbacks
  docs/lcb/notes/22996.md
  libfoundation/src/foundation-java-private.cpp
Labels: LCB, bug, vulcan/reviewed
