Repository livecode/livecode, pull requests merged in 2020-08, with the labels that each got.

#7413 Merge release 9.6.0 03.08.2020
  docs/notes/bugfix-22737.md
  ide-support/revsaveasandroidstandalone.livecodescript
Labels: vulcan/reviewed

#7414 Merge release 9.6.1 13.08.2020
  docs/notes/bugfix-22737.md
  engine/engine-sources.gypi
  ide-support/revsaveasandroidstandalone.livecodescript
  version
Labels: clean merge, vulcan/reviewed

#7418 [[ 9.6.1 ]] Updated version
  version
Labels: vulcan/reviewed

#7416 [[ Bug 22143 ]] Fix interactive tutorial on Windows
  docs/notes/bugfix-22143.md
  engine/src/exec-interface-stack.cpp
Labels: bug, vulcan/reviewed

#7420 [9.6.2 RC-1] Updated version
  version
Labels: vulcan/reviewed

#7421 [[ Bug 22877 ]] Ensure mouse focus restored after relayer
  docs/notes/bugfix-22877.md
  engine/src/exec-interface2.cpp
Labels: bug, vulcan/reviewed
