Repository livecode/livecode, pull requests merged in 2021-01, with the labels that each got.

#7496 Merge develop 9.6 30.12.2020
  docs/notes-base/platforms.md
  docs/notes/bugfix-21471.md
  docs/notes/bugfix-22879.md
  docs/notes/bugfix-22880.md
  docs/notes/bugfix-22896.md
  docs/notes/bugfix-22974.md
  docs/notes/bugfix-22980.md
  docs/notes/bugfix-22997.md
  docs/notes/bugfix-23003.md
  docs/notes/bugfix-23019.md
  engine/src/button.cpp
  engine/src/buttondraw.cpp
  engine/src/desktop-menu.cpp
  engine/src/dskmac.cpp
  engine/src/dskw32.cpp
  engine/src/globals.cpp
  engine/src/mac-core.mm
  engine/src/mac-dialog.mm
  engine/src/mac-internal.h
  engine/src/mac-theme.mm
  engine/src/mac-window.mm
  engine/src/mblhandlers.cpp
  engine/src/mbliphone.mm
  engine/src/mbliphoneapp.mm
  engine/src/mbliphonecalendar.mm
  engine/src/mbliphonecontact.mm
  engine/src/mbliphonedc.mm
  engine/src/mbliphonedialog.mm
  engine/src/mbliphoneextra.mm
  engine/src/mbliphonefs.mm
  engine/src/mbliphonemediapick.mm
  engine/src/mbliphonepick.mm
  engine/src/mbliphonepickdate.mm
  engine/src/mbliphonescroller.mm
  engine/src/mbliphonesensor.mm
  engine/src/mbliphonesound.mm
  engine/src/platform-player.cpp
  engine/src/platform-recorder.cpp
  engine/src/srvwindows.cpp
  engine/src/sysdefs.h
  engine/src/w32ans.cpp
  engine/src/w32cursor.cpp
  engine/src/w32date.cpp
  engine/src/w32dc.cpp
  engine/src/w32dcs.cpp
  engine/src/w32image.cpp
  engine/src/w32printer.cpp
  engine/src/w32stack.cpp
  engine/src/w32theme.cpp
  engine/src/windows-theme.cpp
  ide-support/revsaveasandroidstandalone.livecodescript
  ide-support/revsblibrary.livecodescript
  revspeech/src/w32sapi5speech.cpp
  revspeech/src/w32sapi5speech.h
Labels: vulcan/reviewed

#7488 [[ Bug 22990 ]] Fix emscripten crash when loading custom TTF font files
  docs/notes/bugfix-22990.md
Labels: bug, vulcan/reviewed

#7500 [[ Bug 23050 ]] Update SQLite to v3.34.0
  docs/dictionary/function/revOpenDatabase.lcdoc
  docs/notes/bugfix-23050.md
Labels: enhancement, vulcan/reviewed

#7501 [[ Bug 23053 ]] Fix frozen color picker launched from modal stack on macOS
  docs/notes/bugfix-23053.md
  engine/src/mac-core.mm
Labels: bug, vulcan/reviewed

#7497 Do not build 32bit MacOS prebuilts
  prebuilt/scripts/platform.inc
Labels: vulcan/reviewed

#7503 [[ Bug 23030 ]] Enable WebRTC on CEF browser
  docs/notes/bugfix-23030.md
  libbrowser/src/libbrowser_cef.cpp
Labels: enhancement, vulcan/reviewed

#7505 [[ Bug 23064 ]] Add support for building apps against iOS 14.3 SDK
  Installer/package.txt
  Makefile
  config.py
  docs/notes-base/platforms.md
  docs/notes/bugfix-23064.md
  ide-support/revdeploylibraryios.livecodescript
  prebuilt/fetch-libraries.sh
  prebuilt/scripts/ios.inc
  tools/setup_xcode_sdks.py
Labels: enhancement, vulcan/reviewed

#7506 [[Bug 23068]] Correct docs on how LC runs on Windows
  docs/notes-base/platforms.md
  docs/notes/bugfix-23068.md
Labels: vulcan/reviewed

#7508 [Bug 23067] Add reload note to browser URL docs
  docs/notes/bugfix-23067.md
  extensions/widgets/browser/browser.lcb
Labels: vulcan/reviewed

#7512 [[ Bug 23064 ]] Add support for building apps against iOS 14.4 SDK
  Installer/package.txt
  Makefile
  config.py
  docs/notes-base/platforms.md
  docs/notes/bugfix-23064.md
  ide-support/revdeploylibraryios.livecodescript
  prebuilt/fetch-libraries.sh
  prebuilt/scripts/ios.inc
  tools/setup_xcode_sdks.py
Labels: enhancement, vulcan/reviewed

#7509 [Bugfix 23074] Add holderVariable note to revDatabaseColumnNamed
  docs/dictionary/function/revDatabaseColumnNamed.lcdoc
  docs/notes/bugfix-23074.md
Labels: enhancement, vulcan/reviewed
