Repository livecode/livecode, pull requests merged in 2021-06, with the labels that each got.

#7572 [[ Bug 22400 ]] Allow http connections on Android browser
  engine/rsrc/android-manifest.xml
  ide-support/revsaveasandroidstandalone.livecodescript
Labels: bug, vulcan/reviewed

#7570 [[ Bug 23183 ]] Fix error in 'deploySanitizeSystemVersion()'
  ide-support/revdeploylibraryios.livecodescript
Labels: blocker, bug, vulcan/reviewed

#7573 [[ Bug 23130 ]] Ensure the pick wheel is shown on iOS 14 on iPhone
  engine/src/mbliphonepickdate.mm
Labels: bug

#7486 [[ Bug 22999 ]] Fix background location updates on iOS
  docs/dictionary/command/iphoneAllowBackgroundLocationUpdates.lcdoc
  docs/notes/bugfix-22999.md
  docs/notes/feature-allow_background_location_updates.md
  engine/rsrc/mobile-template.plist
  engine/src/exec-sensor.cpp
  engine/src/exec.h
  engine/src/mblandroidsensor.cpp
  engine/src/mblhandlers.cpp
  engine/src/mbliphonesensor.mm
  engine/src/mblsensor.h
Labels: bug, vulcan/reviewed

#7576 [Bug-23232] Correct code example in replace entry.
  docs/dictionary/command/replace.lcdoc
  docs/notes/bugfix-23232.md
Labels: bug, vulcan/reviewed

#7577 [[ Bug 23223 ]] Add name of SVG Icon to Properties Inspector
  extensions/widgets/svgpath/notes/bugfix-23223.md
  extensions/widgets/svgpath/svgpath.lcb
Labels: vulcan/reviewed

#7457 [[ Bug 21769 ]] Add new function iphoneDeviceModel()
  docs/dictionary/function/iphoneDeviceModel.lcdoc
  docs/notes/bugfix-21769.md
  engine/src/exec-misc.cpp
  engine/src/exec.h
  engine/src/mblandroidmisc.cpp
  engine/src/mblhandlers.cpp
  engine/src/mbliphoneapp.mm
  engine/src/mbliphoneextra.mm
  engine/src/mbliphonepick.mm
  engine/src/mbliphonepickdate.mm
  engine/src/mblsyntax.h
Labels: enhancement, vulcan/reviewed

#7579 [[ Bug 23193 ]] Ensure AppTrackingTransparency framework is included on iOS 14+
  lcidlc/lclink.sh
  tools/build-extension-ios.sh
Labels: blocker, bug, vulcan/reviewed

#7581 [[ Bug 22400 ]] Move ${ALLOW_HTTP_CONNECTIONS} into <application> tag
  engine/rsrc/android-manifest.xml
Labels: bug, vulcan/reviewed

#7584 [[ mergExt ]] Update pointer
  builder/builder_utilities.livecodescript
Labels: vulcan/reviewed

#7590 [Bugfix-23247] Remove references to HTML5 from post entry
  docs/dictionary/command/post.lcdoc
  docs/notes/bugfix-23247.md
Labels: vulcan/reviewed

#7591 [[ tsNet ]] Update pointer
  builder/builder_utilities.livecodescript
Labels: enhancement, vulcan/reviewed

#7586 [[ Bug 22791 ]] Fix error signing Mac standalones when app name contains accents
  docs/notes/bugfix-22791.md
  engine/rsrc/Installer-Info.plist
  engine/rsrc/LiveCode-Info.plist
  engine/rsrc/Standalone-Info.plist
  ide-support/revsaveasstandalone.livecodescript
Labels: bug, vulcan/reviewed

#7553 [[ Bug 23168 ]] Fix memory leak when rendering "good" quality gradients
  docs/notes/bugfix-23168.md
  libgraphics/src/legacygradients.cpp
Labels: bug, vulcan/reviewed

#7502 [[ Bug 23044 ]] Fix crash when deleting current card in closeStack handler
  docs/notes/bugfix-23044.md
  engine/src/stack3.cpp
Labels: bug, vulcan/reviewed

#7419 [[ Bug 22868 ]] Ensure format() accepts negative length
  docs/notes/bugfix-22868.md
  engine/src/exec-strings.cpp
Labels: bug, vulcan/reviewed

#7587 [[ Bug 23240 ]] Fix engine lockup after execution error in modal stack
  docs/notes/bugfix-23240.md
  engine/src/debug.cpp
  engine/src/debug.h
Labels: bug, vulcan/reviewed

#7489 [[ Bug 23016 ]] Update emscripten custom font handling
  docs/notes/bugfix-23016.md
  engine/engine-sources.gypi
  engine/kernel.gyp
  engine/src/customfont.cpp
  engine/src/customfont.h
  engine/src/em-font.cpp
  engine/src/em-font.h
  engine/src/em-fontlist.cpp
  engine/src/em-main.cpp
  engine/src/freetype-font.cpp
  engine/src/freetype-font.h
  engine/src/graphics_util.h
  engine/src/mblandroidfont.cpp
  engine/src/mblandroidtypeface.cpp
  engine/src/mblandroidtypeface.h
  engine/src/skiatypeface.cpp
  engine/src/skiatypeface.h
Labels: bug, vulcan/reviewed

#7387 [[ Bug 21615 ]] Implement HiDPI scaling in emscripten engine
  docs/notes/bugfix-21615.md
  engine/src/em-dc.cpp
  engine/src/em-event.js
  engine/src/em-resolution.cpp
  engine/src/em-stack.cpp
  engine/src/stack.h
Labels: bug, enhancement, vulcan/reviewed

#7588 [[ Bug 22087 ]] Prevent crash when setting the enabledTracks of player to empty
  engine/src/player-platform.cpp
Labels: bug, vulcan/reviewed
