Repository livecode/livecode, pull requests merged in 2021-02, with the labels that each got.

#7514 [[ Bug 23079 ]] Include mergLA in mergExt
  builder/builder_utilities.livecodescript
  docs/notes/bugfix-23079.md
Labels: vulcan/reviewed

#7516 [[ 9.6.2 RC-3 ]] Updated version
  version
Labels: vulcan/reviewed

#7517 [[ Bug 23075 ]] Process events while waiting in a modal session on Macos
  docs/notes/bugfix-23075.md
  engine/src/mac-core.mm
Labels: blocker, bug, vulcan/reviewed

#7513 [[ mergExt ]] Update pointer
  builder/builder_utilities.livecodescript
Labels: vulcan/reviewed

#7519 [Bugfix-14944] Correct text errors in User Guide's XML section
  docs/guides/Processing Text and Data.md
  docs/notes/bugfix-14944.md
Labels: vulcan/reviewed

#7522 [[ tsNet ]] Update pointer
  builder/builder_utilities.livecodescript
Labels: vulcan/reviewed

#7499 [[ Bug 23055 ]] Reset EOF marker when seeking in a file on macOS
  docs/notes/bugfix-23055.md
  engine/src/dskmac.cpp
Labels: bug, vulcan/reviewed

#7515 [[ Bug 16296 ]] Fix crash when restarting location tracker on Android
  docs/notes/bugfix-16296.md
  engine/src/java/com/runrev/android/SensorModule.java
Labels: blocker, bug, vulcan/reviewed

#7523 Merge develop 9.6 15.02.2021
  Installer/package.txt
  Makefile
  builder/builder_utilities.livecodescript
  config.py
  docs/dictionary/function/revDatabaseColumnNamed.lcdoc
  docs/dictionary/function/revOpenDatabase.lcdoc
  docs/guides/Processing Text and Data.md
  docs/notes-base/platforms.md
  docs/notes/bugfix-14944.md
  docs/notes/bugfix-22990.md
  docs/notes/bugfix-23030.md
  docs/notes/bugfix-23050.md
  docs/notes/bugfix-23053.md
  docs/notes/bugfix-23064.md
  docs/notes/bugfix-23067.md
  docs/notes/bugfix-23068.md
  docs/notes/bugfix-23074.md
  docs/notes/bugfix-23075.md
  docs/notes/bugfix-23079.md
  engine/src/mac-core.mm
  extensions/widgets/browser/browser.lcb
  ide-support/revdeploylibraryios.livecodescript
  libbrowser/src/libbrowser_cef.cpp
  prebuilt/fetch-libraries.sh
  prebuilt/scripts/ios.inc
  prebuilt/scripts/platform.inc
  tools/setup_xcode_sdks.py
Labels: vulcan/reviewed

#7494 [[ Bug 22365 ]] Fix Accelerated rendering glitch when multiple stacks are open
  docs/notes/bugfix-22365.md
  engine/src/mblandroiddc.cpp
Labels: bug, vulcan/reviewed

#7524 Merge develop 9.6 15.02.2021 2
  docs/notes/bugfix-16296.md
  docs/notes/bugfix-22365.md
  docs/notes/bugfix-23055.md
  engine/src/dskmac.cpp
  engine/src/java/com/runrev/android/SensorModule.java
  engine/src/mblandroiddc.cpp
Labels: clean merge, vulcan/reviewed

#7525 [[ Bug 23089 ]] Use AbsoluteLayout class to position native layers
  docs/notes/bugfix-23089.md
  engine/src/java/com/runrev/android/Engine.java
Labels: bug, vulcan/reviewed

#7526 Merge develop 9.6 17.02.2021
  docs/notes/bugfix-23089.md
  engine/src/java/com/runrev/android/Engine.java
Labels: vulcan/reviewed

#7529 [[ Bug 23094 ]] Fix android native layer rect relative to parent
  docs/notes/bugfix-23094.md
  engine/src/native-layer-android.cpp
Labels: bug, vulcan/reviewed

#7530 Merge develop 9.6 23.02.2021
  docs/notes/bugfix-23094.md
  engine/src/native-layer-android.cpp
Labels: clean merge, vulcan/reviewed

#7531 [[ Bug 23098 ]] Fix native layers not relayering after object relayer
  docs/notes/bugfix-23098.md
  engine/src/card.cpp
  engine/src/group.cpp
Labels: bug, vulcan/reviewed

#7532 Merge develop 9.6 24.02.2021
  docs/notes/bugfix-23098.md
  engine/src/card.cpp
  engine/src/group.cpp
Labels: clean merge, vulcan/reviewed

#7533 [[ Bug 23100 ]] Ensure android player renders over OpenGL view
  docs/notes/bugfix-23100.md
  engine/src/java/com/runrev/android/nativecontrol/ExtVideoView.java
Labels: bug, vulcan/reviewed

#7534 Merge develop 9.6 25.02.2021
  docs/notes/bugfix-23100.md
  engine/src/java/com/runrev/android/nativecontrol/ExtVideoView.java
Labels: clean merge, vulcan/reviewed
