Repository livecode/livecode, pull requests merged in 2021-04, with the labels that each got.

#7541 [[ Bug 23119 ]] Fix unresponsiveness of engine when scrolling on Big Sur
  docs/notes/bugfix-23119.md
  engine/src/mac-core.mm
  engine/src/mac-internal.h
  engine/src/mac-window.mm
Labels: blocker, bug, vulcan/reviewed

#7545 Merge release 9.6.2 05.04.2021
  docs/notes/bugfix-23085.md
  docs/notes/bugfix-23119.md
  engine/src/mac-core.mm
  engine/src/mac-internal.h
  engine/src/mac-window.mm
Labels: clean merge, vulcan/reviewed

#7540 [[ Bug 21906 ]] Fix copying data from clipboard via IStream objects on Windows
  docs/notes/bugfix-21906.md
  engine/src/w32-clipboard.cpp
Labels: bug, vulcan/reviewed

#7548 [[ Bug 23154 ]] Fix lockup on Big Sur when restoring window after maximizing
  docs/notes/bugfix-23154.md
  engine/src/mac-window.mm
Labels: blocker, bug, vulcan/reviewed

#7549 [Bug-23160] Correct code example in revXMLEvaluateXPath
  docs/dictionary/function/revXMLEvaluateXPath.lcdoc
  docs/notes/bugfix-23160.md
Labels: vulcan/reviewed

#7550 [[ 9.6.2 RC-5 ]] Updated version
  version
Labels: vulcan/reviewed

#7511 [[ Bug 22808 ]] Use default browser to show OAuth2 dialog on Linux
  extensions/script-libraries/oauth2/notes/22808.md
  extensions/script-libraries/oauth2/oauth2.livecodescript
Labels: bug, vulcan/reviewed

#7554 [[ Bug 23172 ]] Fix 100% CPU load when playing unsupported media file on Big Sur
  docs/notes/bugfix-23172.md
  engine/src/mac-av-player.mm
Labels: blocker, bug, vulcan/reviewed

#7542 [[ Bug 23096 ]] Implement translated environment AppleScript workaround
  docs/notes/bugfix-23096.md
  engine/src/dskmac.cpp
Labels: bug, vulcan/reviewed

#7555 [[ 9.6.2 RC-6 ]] Updated version
  version
Labels: vulcan/reviewed

#7552 [[ Bug 23167 ]] Fix memory leak when using arrayEncode in legacy mode
  docs/notes/bugfix-23167.md
  engine/src/foundation-legacy.cpp
Labels: bug, vulcan/reviewed

#7551 [[ Bug 23166 ]] Fix memory leak when parsing visual effect parameters
  docs/notes/bugfix-23166.md
  engine/src/exec-interface.cpp
Labels: bug, vulcan/reviewed

#7504 [Bug 23056] Tree View Widget error when values hidden
  extensions/widgets/treeview/notes/23056.md
  extensions/widgets/treeview/treeview.lcb
Labels: bug, vulcan/reviewed

#7559 [[ Bug 23096 ]] Return compiler error for osascript script errors
  engine/src/dskmac.cpp
Labels: bug, vulcan/reviewed
