Repository livecode/livecode, pull requests merged in 2021-07, with the labels that each got.

#7592 [[ Bug 21615 ]] Fix emscripten release build error
  engine/src/em-event.js
Labels: blocker, bug, vulcan/reviewed

#7594 [[ 9.6.3 RC-2 ]] Updated version
  version
Labels: vulcan/reviewed

#7593 Merge develop 9.6 16 7 2021
  builder/builder_utilities.livecodescript
  docs/dictionary/command/post.lcdoc
  docs/notes/bugfix-21615.md
  docs/notes/bugfix-22791.md
  docs/notes/bugfix-22868.md
  docs/notes/bugfix-23016.md
  docs/notes/bugfix-23044.md
  docs/notes/bugfix-23168.md
  docs/notes/bugfix-23240.md
  docs/notes/bugfix-23247.md
  engine/engine-sources.gypi
  engine/kernel.gyp
  engine/rsrc/Installer-Info.plist
  engine/rsrc/LiveCode-Info.plist
  engine/rsrc/Standalone-Info.plist
  engine/src/customfont.cpp
  engine/src/customfont.h
  engine/src/debug.cpp
  engine/src/debug.h
  engine/src/em-dc.cpp
  engine/src/em-event.js
  engine/src/em-font.cpp
  engine/src/em-font.h
  engine/src/em-fontlist.cpp
  engine/src/em-main.cpp
  engine/src/em-resolution.cpp
  engine/src/em-stack.cpp
  engine/src/exec-strings.cpp
  engine/src/freetype-font.cpp
  engine/src/freetype-font.h
  engine/src/graphics_util.h
  engine/src/mblandroidfont.cpp
  engine/src/mblandroidtypeface.cpp
  engine/src/mblandroidtypeface.h
  engine/src/player-platform.cpp
  engine/src/skiatypeface.cpp
  engine/src/skiatypeface.h
  engine/src/stack.h
  engine/src/stack3.cpp
  ide-support/revsaveasstandalone.livecodescript
  libgraphics/src/legacygradients.cpp
Labels: vulcan/reviewed

#7596 [[ Bug 23038 ]] Fix creation of color profiles on macOS
  docs/notes/bugfix-23038.md
  engine/src/mac-color.mm
Labels: bug, vulcan/reviewed

#7597 [[ 9.6.3 RC-3 ]] Updated version
  version
Labels: vulcan/reviewed

#7598 Merge release 9.6.3 26.07.2021
  docs/notes/bugfix-23038.md
  engine/src/mac-color.mm
Labels: clean merge, vulcan/reviewed

#7601 Merge develop 9.6 26.07.2021 2
  builder/builder_utilities.livecodescript
  docs/dictionary/command/post.lcdoc
  docs/notes/bugfix-21615.md
  docs/notes/bugfix-22791.md
  docs/notes/bugfix-22868.md
  docs/notes/bugfix-23016.md
  docs/notes/bugfix-23038.md
  docs/notes/bugfix-23044.md
  docs/notes/bugfix-23168.md
  docs/notes/bugfix-23240.md
  docs/notes/bugfix-23247.md
  engine/engine-sources.gypi
  engine/kernel.gyp
  engine/rsrc/Installer-Info.plist
  engine/rsrc/LiveCode-Info.plist
  engine/rsrc/Standalone-Info.plist
  engine/src/customfont.cpp
  engine/src/customfont.h
  engine/src/debug.cpp
  engine/src/debug.h
  engine/src/em-dc.cpp
  engine/src/em-event.js
  engine/src/em-font.cpp
  engine/src/em-font.h
  engine/src/em-fontlist.cpp
  engine/src/em-main.cpp
  engine/src/em-resolution.cpp
  engine/src/em-stack.cpp
  engine/src/exec-strings.cpp
  engine/src/freetype-font.cpp
  engine/src/freetype-font.h
  engine/src/graphics_util.h
  engine/src/mac-color.mm
  engine/src/mblandroidfont.cpp
  engine/src/mblandroidtypeface.cpp
  engine/src/mblandroidtypeface.h
  engine/src/player-platform.cpp
  engine/src/skiatypeface.cpp
  engine/src/skiatypeface.h
  engine/src/stack.h
  engine/src/stack3.cpp
  ide-support/revsaveasstandalone.livecodescript
  libgraphics/src/legacygradients.cpp
Labels: vulcan/reviewed

#7602 [[ 9.6.3 ]] Updated version
  version
Labels: vulcan/reviewed
